### ISSUE TITLE
模组更新后无法登陆

### ISSUE THREAD

**Issue by Flamesky1** [LocalizeLimbusCompany/LocalizeLimbusCompany#100]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模组更新后要求安装更新后的字体，但解压安装后无效并依旧提示要求安装更新后的字体

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11423963/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11423964/default.log)

### 截图

![image](https://user-images.githubusercontent.com/132941155/236900857-cb6eff82-865e-43ba-aa7e-4e4cab561440.png)
![image](https://user-images.githubusercontent.com/132941155/236900921-53ccdb92-c092-4302-8b0a-fa58b740db20.png)

**Comment by Bright1192** [comment]
这意味着字体被更新了，你为什么不解压该字体以应用更新呢

**Comment by Flamesky1** [comment]
> 这意味着字体被更新了，你为什么不解压该字体以应用更新呢

就是解压更新后的字体后依然报错
![image](https://user-images.githubusercontent.com/132941155/236903265-96ad93b8-6809-41b9-af18-61b3b4943c2a.png)
