### ISSUE TITLE
更新完5.9字体后字体问题

### ISSUE THREAD

**Issue by Artrioas** [LocalizeLimbusCompany/LocalizeLimbusCompany#101]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

出现三技能左下角结算一会大一会小一会消失的问题

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11428561/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11428562/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11428563/Latest.log)

### 截图

![Z~{Z$CY_8JS)XBPSKTNP9}7](https://user-images.githubusercontent.com/89018819/237027053-d441a16f-0096-4784-b2ba-4874f0ebb306.png)
![IGG7GG15V3JJQ32HNFXRFFN](https://user-images.githubusercontent.com/89018819/237027062-7ddac059-d53a-40ff-9441-ec76cae3c167.png)
![)9VGR@2V{3LF%IG9Y)QPG I](https://user-images.githubusercontent.com/89018819/237027074-598b37ac-34f1-4191-9f81-01f7aa36a50a.png)
![AW3G~8@)L1 EYRHF}BX~NMM](https://user-images.githubusercontent.com/89018819/237027087-3bf34a68-fa25-4236-a69e-2ec73ef3ac25.png)

**Comment by Bright1192** [comment]
哦，这些字体是针对开发版和v0.4.0的，你可以去"行动"里下载并使用开发板

**Comment by Artrioas** [comment]
好的
