### ISSUE TITLE
（疑似的）文本翻译缺失

### ISSUE THREAD

**Issue by plantvsplant** [LocalizeLimbusCompany/LocalizeLimbusCompany#102]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

字体文件版本为0509
事件选择文本
咯口咯口

### 日志文件

该问题无需日志文件

### 截图

![QQ图片20230510124627](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/96964718/3539027c-d5c3-488c-b9c8-5cebe1391f3c)

**Comment by N071** [comment]
感谢反馈，这个字是“哒”
这个问题是由于字库中字体的缺失，是相当常见的问题
您很快就能在之后的更新中见到这个问题被修复
