### ISSUE TITLE
V0.5.0游戏道具描述文本部分显示错误

### ISSUE THREAD

**Issue by Hume-10AEC2** [LocalizeLimbusCompany/LocalizeLimbusCompany#106]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

背包中脑啡肽盒子和两种碎片箱的简要描述里出现了口口

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11455094/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11455095/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11455099/Latest.log)

### 截图

![1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/133257755/14c0e090-8929-42d4-92f4-ab3410693149)
![2](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/133257755/104ae745-47fb-4b1f-b083-d930812a03be)
![3](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/133257755/9582c685-c6e9-4fc7-bf5c-b201c7d1a4fb)

### 还有别的吗？

更新到V0.5.0时直接用的统合包覆盖更新

**Comment by Bright1192** [comment]
开发版已修复https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/actions/workflows/dev.yml
