### ISSUE TITLE
部分道具汉化出现口口字样

### ISSUE THREAD

**Issue by yimu516** [LocalizeLimbusCompany/LocalizeLimbusCompany#107]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

部分道具汉化文本出现口口字样，目前已发现的有“脑啡肽盒子”和“[第一赛季]自我碎片自选箱”
![D$F$PQFGDI8I0W3WFAMKU5A](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/133556530/0210d27b-b3ba-45fb-b1d4-b3c00a77ecf2)
![3FW6CQ4F2C{WZD%01CK%$B4](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/133556530/c9d9f0ab-7c3b-40ba-b221-6993fe014476)

### 日志文件

[MelonLoader_23-03-10_09-18-55.944.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11471182/MelonLoader_23-03-10_09-18-55.944.log)

**Comment by HeartyYF** [comment]
https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/106
duplicated
