### ISSUE TITLE
游戏内汉化切换

### ISSUE THREAD

**Issue by ZengXiaoPi** [LocalizeLimbusCompany/LocalizeLimbusCompany#108]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

RT
建议增加在游戏内切换英文，韩文，日文，中文功能。

**Comment by Bright1192** [comment]
如何简单的卸载模组:
重命名version.dll，例如_version.dll
如何简单的恢复:
重命名回来

**Comment by Bright1192** [comment]
![19e7eb80805c203b](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87061166/6a932326-d125-47a4-a0f1-99b8ebea39e2)
下个版本将会增加
