### ISSUE TITLE
加载不出模组，提示Mod Has Unknown Fatal Error

### ISSUE THREAD

**Issue by deivoglamr** [LocalizeLimbusCompany/LocalizeLimbusCompany#110]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新模组前几天是正常的，突然加载不出汉化模组

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11522087/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11522088/default.log)

### 截图

![SharedScreenshot](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/134138982/68224fdb-402e-4896-91c0-c5ebc59acea9)

### 还有别的吗？

![SharedScreenshot](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/134138982/43f0e5c0-a5b4-4007-875f-d8f30c759b37)

**Comment by Bright1192** [comment]
这个报错看起来有点神秘，要不你试试把模组框架和模组重新装一下

**Comment by deivoglamr** [comment]
> 这个报错看起来有点神秘，要不你试试把模组框架和模组重新装一下
装了之后显示这样...问问是怎么回事
![SharedScreenshot](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/134138982/760b97e9-b916-45e3-a266-16fb1a70a434)

**Comment by Bright1192** [comment]
这个报错说找不到引导程序，我也不知道为什么会这样

**Comment by ZengXiaoPi** [comment]
你可以尝试一下使用最新版的0.6.1
