### ISSUE TITLE
新劇情無中文

### ISSUE THREAD

**Issue by yamiyousanke** [LocalizeLimbusCompany/LocalizeLimbusCompany#114]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我安裝了LLC_MOD_Toolbox，安裝過程中好像也沒有顯示甚麼錯誤。但在打開新劇情(也就是4-28)的時候只出現了英文劇情。
我不太清楚是不是哪裡安裝錯了？

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11708663/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11708664/default.log)
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11708680/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11708681/Player.log)

**Comment by ZengXiaoPi** [comment]
我们还没有发布最新版本的release。请等待更新。

**Comment by Bright1192** [comment]
你需要理解的是:这只是汉化模组，而不是官方中文
这意味着:除非我们对新内容进行更新，否则他们将永远是英文的
