### ISSUE TITLE
模组不生效（v0.5.1）进游戏有弹窗（INTERNAL FAILURE!）MelonLoader日志内容（在其上下文中，该请求的地址无效）

### ISSUE THREAD

**Issue by bugtheworld** [LocalizeLimbusCompany/LocalizeLimbusCompany#115]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入游戏的时候出现一个INTERNAL FAILURE!的弹窗，内容为Failed to Download Cpp2IL（截图请见截图部分）

弹窗点击确定后可以正常进入游戏，也可正常游玩，但是没有汉化，设置中只有原来的三种语言，没有中文选项

游戏目录下的文件结构也在截图中

### 日志文件

由于不确定是什么类型的问题，所以把这三个文件都上传了

这三个文件为同一次游玩后生成的日志文件，且与下方截图为同一次游玩（中/后）的内容

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11711288/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11711290/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11711292/Latest.log)

### 截图

（似乎MelonLoader命令行窗口内容会记录在Latest.log里面，所以相关截图放在了最后）

弹窗截图：
![图片](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/30af0b52-aa95-4fc4-8266-d7cda64017c1)

游戏内Setting界面如下：（语言设置部分）
![图片](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/17a8e133-c9df-4604-aee7-ebdf1de7eb1f)

这是游戏目录下的文件：
![图片](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/88d6cb98-5547-4557-ac7e-cba5398c8c6e)

出现弹窗时的Melonloader命令行窗口内容如下：
![图片](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/97fad6e2-5c3b-41bd-abdc-6dc1cb0a220a)

进入游戏后的Melonloader命令行窗口内容如下：（上一个相关截图末尾开始）
![图片](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/388d32e0-c2c8-4f1a-ba76-9f7f10c10278)

### 还有别的吗？

操作系统Windows 10 21H2，内部版本19044.2604

之前版本的模组均可正常使用

以下为本人进行过的操作：（未按照操作先后顺序排序）

- 将version.dll.disable文件删除
- ./Userdata/MelonPreferences.cfg内容进行修改（使用汉化从False改为True，自动更新从True改为False）
- 貌似是与网址有关的问题，在未挂梯子和挂了梯子的情况下都试了一遍，均会出现该问题
- 先后用模组安装器和github手动安装的方法，均出现了同一问题

**Comment by ZengXiaoPi** [comment]
网络问题，如果实在不行就用统合包吧，下载链接在bilibili专栏。
如果你安装器都不行的话我也给不了解决方案

**Comment by Bright1192** [comment]
我们正好在修复无法访问MelonLoader的RemoteAPI问题,可以使用以下版本的MelonLoader模组框架[`Fuck Contacting RemoteAPI`](https://github.com/LocalizeLimbusCompany/MelonLoader-LLC/suites/13505183665/artifacts/742066334)

**Comment by ZengXiaoPi** [comment]
> 我们正好在修复无法访问MelonLoader的RemoteAPI问题,可以使用以下版本的MelonLoader模组框架[`Fuck Contacting RemoteAPI`](https://github.com/LocalizeLimbusCompany/MelonLoader-LLC/suites/13505183665/artifacts/742066334)

不，这看起来是无法下载cpp2il导致的。即使访问api，MelonLoader也无法找到Limbus Company相关的文件。

**Comment by ZengXiaoPi** [comment]
镜像节点已更新新版本MelonLoader，请重新使用工具箱安装。
