### ISSUE TITLE
为什么「山茶花」会被翻译成「山茶花」而不是「壇香梅」或「三桠乌药」

### ISSUE THREAD

**Issue by LotusVacuity** [LocalizeLimbusCompany/LocalizeLimbusCompany#117]
### 说说你遇到的问题？

![IMG_6842](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/136795617/bb5cb197-ca65-4a29-9b90-058a91d741ef)
![IMG_6843](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/136795617/2682f085-0768-4e2b-ad2a-32589bc6f6c8)

**Comment by HeartyYF** [comment]
首先感谢反馈。

对第一个问题，“山茶”的命名：我想先指出一点，就是三语没有各自选择“有地方特色”的翻译，三语均是正确的，并且指的实际上是相同的东西。我直接将考据粘贴过来：

동백来源是金裕贞的小说《동백꽃》，동백是江原道方言的三桠乌药，因为三桠乌药油过去拿来代替山茶花油使用所以叫这个名，有刺鼻的香味，因此也称“生姜树”，因此文章里老是提到刺鼻的味道。
日文的壇香梅是三桠乌药，也就是《山茶花》里写的那种山茶花。直接把日文汉字牵强附会成中文是完全错误的。
英文的Spicebush指的实际上是Japanese Spicebush，也就是三桠乌药。
《山茶花》写的山茶花并不是一般的山茶花，是因为那边的方言管三桠乌药叫山茶花。
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/17660052/eb24bd83-9340-4eed-8236-5159a6c982eb)
以这张游戏中的图为例，金色的是三桠乌药，红色的是真正的“山茶花”，《山茶花》中的山茶花指的就是金色的这种三桠乌药。

所以最后决定以《山茶花》原书名为参考，选择了山茶这个译名，也能更直观的看出山茶的原型出自哪里。

https://en.wiktionary.org/wiki/%EB%8F%99%EB%B0%B1%EA%BD%83
Wiktionary的结果也支持我们的考究。

下一条回复讨论舍音。

**Comment by N071** [comment]
https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/wiki/Individual-Translation-Code
已收录
