### ISSUE TITLE
汉化补丁工具箱无法正常使用

### ISSUE THREAD

**Issue by avskbvsk** [LocalizeLimbusCompany/LocalizeLimbusCompany#119]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

LLC_MOD_Toolbox可以打开，但点击一键安装就会出现截图所示情况，然后自动关闭工具箱。

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11828238/LLCToolBox_log.txt)

### 截图

![屏幕截图 2023-06-22 110116](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/137367767/7365b966-f4d1-4156-87f4-34937c386117)

### 还有别的吗？

WIN10, NET6.0已安装，杀毒软件已关闭

**Comment by Bright1192** [comment]
尝试使用手动安装

**Comment by avskbvsk** [comment]
手动安装也不行，按照教程解压完打开游戏后，那个西瓜界面的进度条完全不会动，然后如图
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/137367767/e4671f4d-faa8-4e5f-9769-bc9c2329bcb2)

**Comment by HeartyYF** [comment]
网有问题，尝试科学上网或者投诉isp。

**Comment by ZengXiaoPi** [comment]
应当已经在v0.3.3修复。如果还有问题请重新打开此议题。
