### ISSUE TITLE
关于理智值增加条件中的歧义问题

### ISSUE THREAD

**Issue by DDcrow** [LocalizeLimbusCompany/LocalizeLimbusCompany#121]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在人格介绍页面中，理智值的理智值增加条件中，有一条 “若击败友方的敌人之等级高于自身，则会根据等级差增加“ ，以我的理解，此句表达的意思更倾向于 ”当**友方**被击败时，根据击败友方的敌人的等级来进行理智值的增加“，但实际上游戏里的表现为 ”当**敌人**被击败时，根据该敌人的等级进行理智值的增加“。同时我也比较了英文和日文中的描述，发现英文和日文对于该情况的描述也更符合后者所述的情况。所以在此提出反馈，望汉化组能予以解决。

由于捉虫这块似乎没有专门的模板，所以只能写在bug反馈里了。本反馈中所述问题并不会造成游戏的崩溃或者其他严重问题，仅仅只是文字描述中似乎有歧义而已，所以日志文件中大概是不会有错误日志。

下面会附上三语的比较图。

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11847028/Latest.log)

### 截图

![QQ图片20230623174133](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/38368778/83b37169-b679-41d4-9bd2-03bf936e7241)
![QQ图片20230623174136](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/38368778/bb4df8b9-f292-4a28-b552-47a209edcb8b)
![QQ图片20230623174139](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/38368778/2a38597f-2164-4595-b7c2-d283db728b5c)

**Comment by Bright1192** [comment]
实际上,v0.5.2已经修复了这个问题

**Comment by Bright1192** [comment]
希望您之后反馈时
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87061166/7cc76ead-1a01-481f-89d1-fdcc171f0e5b)

**Comment by DDcrow** [comment]
> 希望您之后反馈时 ![image](https://user-images.githubusercontent.com/87061166/248239642-7cc76ead-1a01-481f-89d1-fdcc171f0e5b.png)

您好，我确实在提issue时有查看游戏公告，而在公告中并未详细提及该问题，以及我确实可以在汉化版本为v0.5.2时在游戏内的公告中看到版本为v0.5.3的公告。但我并没有跟标题页面所示的汉化版本号进行比对，并且我昨天在月计完成维护后立马就运行了汉化工具，这可能导致我实际上没获得最新版本的汉化，并错误地认为我使用的汉化版本就是最新的版本。我会在以后提出issue的时候注意这些方面的。
