### ISSUE TITLE
应用程序中发生了未经处理的异常

### ISSUE THREAD

**Issue by ninesun95** [LocalizeLimbusCompany/LocalizeLimbusCompany#123]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.FileNotFoundException: D:\steam\steamapps\common\Limbus Company\Mods/LimbusLocalize.dll
   在 System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   在 LLC_MOD_Toolbox.MainForm.<installButton_Click>d__12.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4515.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
LLC_MOD_Toolbox
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///E:/%E4%B8%8B%E8%BD%BD/LimbusCompanyMod_Toolbox/LLC_MOD_Toolbox.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4550.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
SunnyUI
    程序集版本:3.3.7.1
    Win32 版本:3.3.7.1
    基本代码:file:///E:/%E4%B8%8B%E8%BD%BD/LimbusCompanyMod_Toolbox/SunnyUI.DLL
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4536.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4590.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SunnyUI.Common
    程序集版本:3.3.2.0
    Win32 版本:3.3.2.0
    基本代码:file:///E:/%E4%B8%8B%E8%BD%BD/LimbusCompanyMod_Toolbox/SunnyUI.Common.DLL
----------------------------------------
7z.NET
    程序集版本:1.0.3.0
    Win32 版本:1.0.3.0
    基本代码:file:///E:/%E4%B8%8B%E8%BD%BD/LimbusCompanyMod_Toolbox/7z.NET.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11857104/LLCToolBox_log.txt)

### 截图

![6 ~T}5XNGMQ})V 9$V5R{0X](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/34742357/2ca6ecce-187f-4234-91db-cd1582aea4fc)

### 还有别的吗？

已安装net6.0

**Comment by ninesun95** [comment]
win10系统，使用的0.3.3安装工具

**Comment by Bright1192** [comment]
我们已经定位到该问题，原因是忘记检测路径是否存在，在之后会修复，至于现在 您可以尝试使用032安装工具

**Comment by ZengXiaoPi** [comment]
最新版已紧急修复，请重新下载0.3.3
