### ISSUE TITLE
狐雨ego的名字没翻译，游戏内显示sunshower（v0.5.3）

### ISSUE THREAD

**Issue by bugtheworld** [LocalizeLimbusCompany/LocalizeLimbusCompany#124]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

李箱和奥斯提的狐雨ego名字没翻译

### 日志文件

我觉得这个问题应该不需要日志文件（
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11893597/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11893598/Player.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11893599/Latest.log)

### 截图

当前游戏版本：
![20230628193513_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/1808e0f0-a951-4e0c-ad0c-32f60be90e2b)

游戏内效果：
![20230628193751_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/54277fdf-881f-44d8-a0ce-fe0a5e4ff67a)
![20230628193757_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/4b9ac68e-d342-4b7f-bacf-c5c4455213cc)
![20230628193811_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/c2270189-2079-4af3-afd7-36a07e43184e)
![20230628193819_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/f6a96267-0b63-4b01-8dba-383f94e5259b)

**Comment by Bright1192** [comment]
这个问题可能是有些文件没有正确的覆盖或者没有按照预期下载ota版本，建议你重新下载v0.5.3全量包
