### ISSUE TITLE
对loading画面的文字有疑问

### ISSUE THREAD

**Issue by yubibisame123** [LocalizeLimbusCompany/LocalizeLimbusCompany#125]
### 说说你遇到的问题？

你好，我在loading界面发现了这样的字样：
“仿生钟婊头会梦见电子女仆维吉尔吗？”
请问这是什么意思呢？
是指但丁是婊子吗？

**Comment by Bright1192** [comment]
...这是 剧情里出现过的，字面意思的蔑称
kr: 빨간 시계 대가리
jp: 赤い時計アタマ
en: red timepuss

**Comment by N071** [comment]
首先，正如Bright1192回复你的，“钟婊头”这个翻译来自于英语的一次整活，是有迹可循的。
其次，仿生xxx会梦到电子xxx吗，是一个梗。请你参考[百度百科](https://baike.baidu.com/item/%E4%BB%BF%E7%94%9F%E4%BA%BA%E4%BC%9A%E6%A2%A6%E8%A7%81%E7%94%B5%E5%AD%90%E7%BE%8A%E5%90%97%EF%BC%9F)。

Loading文本的梗比较密集，如果您无法看懂，那么请不要把它看得太重。

**Comment by yubibisame123** [comment]
谢谢你回复我。
首先我很享受这个游戏的汉化文本，它在很大程度上提高了我和很多人的游戏体验，非常感谢你们汉化组的努力。
由于我在日本生活学习了非常长的时间，我在玩游戏的时候用的是日语版本，日语中‘赤い時計アタマ’这句话可以翻译为红色时钟脑袋，或者轻蔑一点说是红色时钟傻瓜脑袋也行。如果英文中这个代称翻译为 red timepuss的话，我会觉得它可能不能与pussy这一代指女性阴部词汇的简写换用（我用的是韦氏辞典）。您能告诉我是哪一处出现了这样的字样吗？我并没有冒犯你们的意思，我只是很想知道这个词具体出现在哪里而已。

**Comment by N071** [comment]
这个翻译出现在S203B内，也就是第二章、第三关的**战前**剧情。
该称呼是英文特色，**并不存在于日韩原文内**。~但这不妨碍我们把他揪出来当梗玩~
这里大概是月计的英翻，真的放飞自我了吧
