### ISSUE TITLE
什么时候出手机版的汉化包和教程

### ISSUE THREAD

**Issue by xiaoshuye147** [LocalizeLimbusCompany/LocalizeLimbusCompany#130]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by N071** [comment]
我们需要找到能够在安卓系统上稳定运行的框架，并以时间精力对其进行适配才能够发布手机版汉化。我们之前尝试过一些框架，但大部分时候我们均无法使用并且稳定性堪忧。

另外，我们的开发者正在尝试实现汉化的其他方法(不依赖MelonLoader)，以期带来更好的使用体验和(可能的)手机适配

**Comment by EnvyNie** [comment]
已经一年过去了，还是希望能有不依赖虚拟机(ourplay、kuyo)的汉化

**Comment by ZengXiaoPi** [comment]
> 已经一年过去了，还是希望能有不依赖虚拟机(ourplay、kuyo)的汉化

短时间内不会考虑制作手机端汉化。
