### ISSUE TITLE
关于已经正确下载所有必备文件，安装完所有文件后，无法汉化（进入游戏后没有汉化提示直接跳过）

### ISSUE THREAD

**Issue by 2663775017** [LocalizeLimbusCompany/LocalizeLimbusCompany#131]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我今天下载了你们这边的安装器 明明已经显示成功安装了，汉化模组依然没有生效（根本没有汉化程序界面就直接进入游戏了），后面根据回复的建议尝试手动安装 ，依然没有改变，是不是因为游戏安装位置的原因，（游戏和安装包全部都在移动硬盘上），但从安装器的定位上并没有出错。

### 日志文件

[LLCToolBox_log.txt](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11980587/LLCToolBox_log.txt)
没有其他的日志产生了

### 截图

![1M(B}6YF(E{7$D9JOCON](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/2d65525a-6b4b-40a9-b3b5-71442965a19c)
![OCFDK}%0H4HKV2_E~6(9KF3](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/f527dab5-01fd-4b93-a27f-40806f95e94a)
![OCFDK}%0H4HKV2_E~6(9KF3](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/a40f9023-85d2-4178-b876-740a050edca8)
![~(M@YC}0 1AH% PDS$(W_BE](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/48174ad8-52e9-4f0b-9124-93bd67eee80a)
![625U~(S` H}T7 V VD@{DI](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/4bcf7835-a686-4f8a-b
![GV UYTUR5K 5HAS6O2@$_VC](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/bdada1a0-ba8c-46c5-9b11-25de677b432b)
815-f6a11abd9ef5)

### 还有别的吗？

操作系统 win10

**Comment by Bright1192** [comment]
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87061166/7e66edf3-cb62-4455-883e-95fe05c9ac3c)
正常来说应该有这些文件
所以.你并没有安装成功

**Comment by 2663775017** [comment]
不应该呀 明明是按照网站上的操作进行的，那现在应该怎么做






静止~、零度de时间
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LocalizeLimbusCompany/LocalizeLimbusCompany"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 晚上6:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 关于已经正确下载所有必备文件，安装完所有文件后，无法汉化（进入游戏后没有汉化提示直接跳过） (Issue #131)





 

 正常来说应该有这些文件
 所以.你并没有安装成功

**Comment by Bright1192** [comment]
将`ML_LLC_v0.6.3.zip`解压到`当前目录`

**Comment by 2663775017** [comment]
依然失败了
&nbsp;


静止~、零度de时间
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月7日(星期五) 晚上7:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 关于已经正确下载所有必备文件，安装完所有文件后，无法汉化（进入游戏后没有汉化提示直接跳过） (Issue #131)





 
将ML_LLC_v0.6.3.zip解压到当前目录

**Comment by 2663775017** [comment]
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/c71ecc65-e153-45e6-9db2-a844e6512190)

**Comment by 2663775017** [comment]
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/52969e41-223b-42f3-9048-508ef0d5ab24)
这些文件在这里
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/135258030/d9e44419-a062-4fda-92da-757443f1ced0)

**Comment by 2663775017** [comment]
感想 重启后成功了 ，现在的问题是 你们这边汉化组更新的话，手动安装的文件该如何更新？
