### ISSUE TITLE
7月6号更新之后全部汉化失效无提示。

### ISSUE THREAD

**Issue by suqiyanshang** [LocalizeLimbusCompany/LocalizeLimbusCompany#136]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

7月6号更新之后全部汉化失效，重装之后也不管用无提示

### 日志文件

[Latest(框架日志).zip](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11994866/Latest.zip)

### 截图

[Desktop.zip](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11994867/Desktop.zip)

### 还有别的吗？

win 11

**Comment by Bright1192** [comment]
使用新版安装器重新安装
