### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by CIEL5** [LocalizeLimbusCompany/LocalizeLimbusCompany#139]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

乱码还有No Support Module Loaded 

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12024579/Latest.log)

### 截图

![Snipaste_2023-07-12_14-34-48](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/139320771/4a0cc34d-aa54-47d2-9e2c-c3052dd11faf)

**Comment by Bright1192** [comment]
看起来你的网络不好，请使用安装器
