### ISSUE TITLE
5.7和5.8问题

### ISSUE THREAD

**Issue by Artrioas** [LocalizeLimbusCompany/LocalizeLimbusCompany#142]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新完5.7和5.8后开始出现汉化缺失情况 退回5.6一切正常

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12049940/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12049941/Player.log)
[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12049942/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12049943/default.log)

### 截图

![}O6CTY8}OBZ{1Y6JZW(E6 N](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/89018819/65dd91fc-2876-49f7-8242-ed8ffc1cd073)
![KKYVJRQX@7)HZ89B)5W%{DV](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/89018819/4c918578-0c71-409a-8248-02e45531a53f)
![CWX9BB3Y__O`AAR 6_AHCVQ](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/89018819/1df1bc43-1fa4-4973-831b-11717c21b5e1)

**Comment by Bright1192** [comment]
请您使用安装器进行安装

**Comment by Artrioas** [comment]
> 请您使用安装器进行安装

直接从github下现在不行了吗？
