### ISSUE TITLE
模组加载器无法初始化/MelonLoader failed to initialize

### ISSUE THREAD

**Issue by XiaHuaXH** [LocalizeLimbusCompany/LocalizeLimbusCompany#143]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏开始运行时直接弹出Internal Failure窗口，窗口内显示Failed to initialize MelonLoader:Load LibraryExW failed。
使用手动安装方法仍未解决，已多次尝试检查游戏文件完整性、重新下载MelonLoader、LimbusLocalize以及字体文件。
已排查网络问题：已尝试更换加速工具（Watt Toolkit、Steamcommunity 302，CFW未尝试，但我想不是这个能解决的），已检查防火墙设置，已尝试暂时关闭杀软，已证实主机能够连接上GitHub。
已尝试重新启动电脑，已尝试将企业版系统更换为专业版（密钥方式）。
已尝试更换汉化模组及附属文件版本，均未解决。
游戏本体在完全删除汉化模组文件后可以正常启动。
两个log（Latest(框架日志).log，Player(游戏日志).log）均未生成，UserLibs未生成，Plugins未生成。

When the game starts running, an Internal Failure window will pop up directly, displaying Failed to initialize MelonLoader: Load LibraryExW failed.
The manual installation method did not solve the problem,Multiple attempts have been made to check the integrity of game files,re-download MelonLoader,LimbusLocalize and font file.
Possibility of the Internet connection causing problems has been checked and excluded: the accelerator has been replaced many times(Watt Toolkit,Steamcommunity 302)(I haven't tried CFW or such ladders yet,but I think it neither can sovle the problem of fail to init the melonlodaer),Firewall settings have been checked and it has been confirmed that the host can connect to GitHub.
The computer has already been restarted,the system version has been changed from business version to professional version(by changing the key).
The version of the mod and the modloader has been changed,neither of them has solved the problem.
The game itself can start normally after completely removing the mod files and melonloader.
Two logs (Latest(框架日志). log, Player(游戏日志). log), UserLibs, and Plugins were not generated even afer running the game.

### 日志文件

如上述，未生成log。
As stated,no log generated.

### 截图

屏幕截图(screenshot)：https://user-images.githubusercontent.com/98738122/255338296-2338dfd7-04e6-4ab6-9d17-c4d2c6b1e0c3.png
文件夹内文件（启动游戏后）(files in the folder (after starting the game)): https://user-images.githubusercontent.com/98738122/255338331-81c61a04-8d26-446b-8dbd-04e46006abfa.png

### 还有别的吗？

操作系统已经在上文提及。
The operating system has already been mentioned earlier.
已查看https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/issues/16，同样未解决。
I've seen the https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/issues/16,it neither has been solved.

**Comment by XiaHuaXH** [comment]
我记得那人把游戏安在C:\Program Files（x86）下Steam的默认安装路径中。虽然系统语言是中文，但这个路径不包含中文吧。
In my impression, it was placed in the default installation path of Steam under C:\ Program Files (x86).In my opinion although the system language is Chinese,this path does not contain Chinese characters, right?

**Comment by ZengXiaoPi** [comment]
已经有多个issue提到此问题，但是我根本不知道具体原因，也无法复现，所以这需要去MelonLoader官方的Github反馈，另外你MelonLoader for llc和官方版的MelonLoader都试了吗？

**Comment by ZengXiaoPi** [comment]
并且在此处不需要使用英语，这是没有必要的。

**Comment by Bright1192** [comment]
> 已经有多个issue提到此问题，但是我根本不知道具体原因，也无法复现，所以这需要去MelonLoader官方的Github反馈

**Comment by fffwww-lang** [comment]
猜测可能跟系统有关（之前是能正常用的），之前因为c盘满了所以重做了一边系统格式化了硬盘然后重新下的游戏和工具包然后就出现了一样的问题，只要用6.0版本的melonloader就能正常使用。

**Comment by XiaHuaXH** [comment]
我尝试过使用虚拟机重装出现问题的系统版本，并且确保路径和出现问题的一样，但都没能复现问题
已经在问题机上尝试使用不同版本的melonloader（过时的和最新的），没能解决
请问能将您的经历讲述得更详细一些吗？

**Comment by XiaHuaXH** [comment]
> 猜测可能跟系统有关（之前是能正常用的），之前因为c盘满了所以重做了一边系统格式化了硬盘然后重新下的游戏和工具包然后就出现了一样的问题，只要用6.0版本的melonloader就能正常使用。
我尝试过使用虚拟机重装出现问题的系统版本，并且确保路径和出现问题的一样，但都没能复现问题
已经在问题机上尝试使用不同版本的melonloader（过时的和最新的），没能解决
请问能将您的经历讲述得更详细一些吗？

**Comment by fffwww-lang** [comment]
我是刚开始win10系统（什么版本不知道用太长时间了）然后重做了一遍系统装的应该是最老的win10,2015发布的，（在这中间我没再下过工具包和游戏）之后因为一些原因有重新装了一个win11，之后用工具包就出现了这个问题，这个问题刚开始是steam点击开始游戏无反应，我就去目录里面打开，提示我缺少vc_runtiem140，这个应该是我是新装的系统应该没什么太大联系，dll下载完之后在打开就会出现这个问题，如果我用6.0版本的melonloader可以正常打开但是汉化文本会出现口口的情况，在我手动下载了字体包也没有解决

**Comment by fffwww-lang** [comment]
我又尝试了删除汉化文件，重新安装发现没有问题了

**Comment by XiaHuaXH** [comment]
谢谢，我通过查找加载器起的依赖项时发现缺少Microsoft Visual C++ 2015-2019 Re-distributable会导致此问题，保险起见，需要下载它的x86和x64版本

**Comment by XiaHuaXH** [comment]
谢谢，我通过查找加载器的依赖项时发现缺少Microsoft Visual C++ 2015-2019 Re-distributable会导致此问题，保险起见，需要下载它的x86和x64版本
