### ISSUE TITLE
汉化包缺少文件

### ISSUE THREAD

**Issue by FrostFish0** [LocalizeLimbusCompany/LocalizeLimbusCompany#144]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

上周版本更新后汉化一直加载不上，删除汉化重装和手动安装试过都没有用一直出现如截图所示的情况，重装游戏也没用

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138496/Latest.log)

### 截图

![屏幕截图 2023-07-22 185556](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140248647/29e2cd53-9286-402a-8c3a-cd67951103be)

**Comment by Bright1192** [comment]
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87061166/ad6d4ef1-edf1-4c27-8fde-a2df21a39c44)
看起来你的杀毒软件并不想让你使用
