### ISSUE TITLE
我安装了汉化包，进入游戏时却没有汉化

### ISSUE THREAD

**Issue by chen74035** [LocalizeLimbusCompany/LocalizeLimbusCompany#145]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我安装了最新的一键汉化模组，正常下载后打开游戏时，游戏内并没有汉化。在此之前我安装了net6.0和7.z。再次使用手动安装后进入游戏还是没有汉化。进入游戏时并没有弹白框报错，也没有黑色的有西瓜的那个界面，也没有日志的那个大白框。我不清楚是出了什么问题，希望您能帮助我解决，谢谢！

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138640/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138641/default.log)
[MelonLoader.zip](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138642/MelonLoader.zip)
压缩后的体积也太大了，，，，

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140317354/4ace4a99-61f0-4cea-82bb-e2f0517713a8)
我没有找到Latest.log的文件

**Comment by Bright1192** [comment]
根据日志，你在尝试使用一个非常久远的版本'v0.2.0'请你根据官网使用安装器或者手动安装最新的版本
