### ISSUE TITLE
更新最新版本后出现文本口口

### ISSUE THREAD

**Issue by noGitHubID** [LocalizeLimbusCompany/LocalizeLimbusCompany#146]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无论将增量更新包还是更新包复制到游戏目录下，再进入游戏都会有部分文字变成口口，但跳转界面后多数口口会变回正常文字，这点与字体或文本缺失导致的口口不太相似。
可能是没有更新上个汉化版本的原因，但理论上应该不是。

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138658/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138660/default.log)

**Comment by Bright1192** [comment]
你可以尝试：
- 手动下载安装字体
- 删除本地化文件夹并重新下载安装模组

**Comment by noGitHubID** [comment]
已解决
