### ISSUE TITLE
安装了最新版游戏内还是没有汉化

### ISSUE THREAD

**Issue by chen74035** [LocalizeLimbusCompany/LocalizeLimbusCompany#147]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我刚刚又检查了一遍，确实是安装了最新模组但是还是不行。没有弹白框报错这些现象，就跟没安模组一样……我也不知道为什么显示的是0.2.0的那个古董版本……求解……

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138728/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12138729/default.log)

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140317354/dd23d4f3-13e1-4829-8268-df95624eb515)

**Comment by ZengXiaoPi** [comment]
如果你不知道为什么，就去用工具箱。
