### ISSUE TITLE
我电脑换硬盘后，游戏安装好补丁后，就报Failed to initialize MelonLoader:LoadLibraryExW failed。常见问题里的方法都试过了，都没奏效。

### ISSUE THREAD

**Issue by JiangHuyouyou173** [LocalizeLimbusCompany/LocalizeLimbusCompany#148]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我电脑换硬盘后，游戏安装好补丁后，就报Failed to initialize MelonLoader:LoadLibraryExW failed。常见问题里的方法都试过了，都没奏效。

### 日志文件

好像都没有

### 截图

![星愿浏览器截图20230724071004](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140354712/d3f86892-9d28-4cad-a7dc-77ead91bf15f)

**Comment by Bright1192** [comment]
无法复现,无法修复,或许你可以关注这个issue https://github.com/LavaGang/MelonLoader/issues/497

**Comment by XiaHuaXH** [comment]
额，我刚才翻microsoft的文档时发现libloaderapi.h里LoadLibraryExW的文档，它的作用是”Loads the specified module into the address space of the calling process. The specified module may cause other modules to be loaded.“（将指定的模块加载到调用进程的地址空间中。指定的模块可能会导致加载其他模块。）里面有这样一句话 “If the function cannot find the module or one of its dependencies, the function fails.” （如果函数找不到模块或其依赖项之一，则该函数将失败。）系统是重装过了吗？还是只换了块硬盘？无论如何，请试试检查有没有缺什么奇怪的模块或者依赖项，比如说Windows控制面板里一般会开的.net framework 3.5和4.8？

**Comment by XiaHuaXH** [comment]
另外，MelonLoader的首页有这个东西
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/98738122/edb85983-9944-442d-9cfc-fe68fc58b1e3)
也就是说需要.NET Framework 3.5 Runtime、.NET Framework 4.7.2 Runtime、.NET Framework 4.8 Runtime、.NET 6.0 Desktop Runtime
、Microsoft Visual C++ 2015-2019 Re-distributable，检查一下都装了吗？

**Comment by ZengXiaoPi** [comment]
那么进行重装系统后部分用户能够使用就能够解释了，如果有新案例，我们会积极引导，查看是否为此问题。

**Comment by XiaHuaXH** [comment]
Winbg有gflags.exe ，可以用来查看引用跟踪。先下载安装https://learn.microsoft.com/zh-cn/windows-hardware/drivers/debugger/debugger-download-tools，然后尝试在游戏根目录下以管理员身份运行cmd，输入
gflags.exe -i 游戏主程序.exe +sls
windbg 游戏主程序.exe
（我是在手机上手打的，可能输错），这可能可以使加载程序能够打印出该进程的dbg消息，并打印失败

**Comment by XiaHuaXH** [comment]
Winbg有gflags.exe ，可以用来查看引用跟踪。先下载安装
https://learn.microsoft.com/zh-cn/windows-hardware/drivers/debugger/debugger-download-tools
然后尝试在游戏根目录下以管理员身份运行cmd，输入
gflags.exe -i 游戏主程序.exe +sls
windbg 游戏主程序.exe
（我是在手机上手打的，可能输错），这可能可以使加载程序能够打印出该进程的dbg消息，并打印失败

**Comment by XiaHuaXH** [comment]
我还找到一个案例，请试试直接在游戏根目录下运行游戏而不是通过steam调用，可能会直接提示缺少的依赖项

**Comment by XiaHuaXH** [comment]
已经解决！确认是缺少Microsoft Visual C++ 2015-2019 Re-distributable x64和x86！！！！

**Comment by XiaHuaXH** [comment]
已经解决一个案例！确认是缺少Microsoft Visual C++ 2015-2019 Re-distributable x64和x86！！！

**Comment by ZengXiaoPi** [comment]
看起来此问题得到了解决方案，将在LLC_Wiki更新后关闭此议案。

**Comment by ZengXiaoPi** [comment]
> 已经解决一个案例！确认是缺少Microsoft Visual C++ 2015-2019 Re-distributable x64和x86！！！

感谢您对LLC的支持，已在LLC Wiki关于此问题的段落上添加您的名字，再次感谢您如此执着追踪此问题。此议题将关闭。

**Comment by JiangHuyouyou173** [comment]
> 已经解决一个案例！确认是缺少Microsoft Visual C++ 2015-2019 Re-distributable x64和x86！！！
一定要是Microsoft Visual C++ 2015-2019 Re-distributable？

**Comment by JiangHuyouyou173** [comment]
> 已经解决一个案例！确认是缺少Microsoft Visual C++ 2015-2019 Re-distributable x64和x86！！！

一定要有Microsoft Visual C++ 2015-2019 Re-distributable？

![星愿浏览器截图20230728194417](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140354712/f1d8df85-260f-407c-b7c6-0a0f8b4744ef)

**Comment by XiaHuaXH** [comment]
> > 已经解决一个案例！确认是缺少Microsoft Visual C++ 2015-2019 Re-distributable x64和x86！！！
> 
> 一定要有Microsoft Visual C++ 2015-2019 Re-distributable？
> 
> ![星愿浏览器截图20230728194417](https://user-images.githubusercontent.com/140354712/256812902-f1d8df85-260f-407c-b7c6-0a0f8b4744ef.png)

![Screenshot_20230728_194425](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/98738122/8fed0fb4-0694-4c94-bb8a-c9efad1f7c02)
这是melonloader首页的依赖项需求，请您自行判断

**Comment by JiangHuyouyou173** [comment]
解决了，谢谢
