### ISSUE TITLE
关于自动更新

### ISSUE THREAD

**Issue by Yicciy** [LocalizeLimbusCompany/LocalizeLimbusCompany#149]
### 说说你遇到的问题？

我更新了汉化模组，将老模组卸载后，手动安装了新模组。我注意到这次文本更新并没有想往常一样弹窗并自动下载压缩包。
想请问一下，更改自动更新的配置文件位置。以下是我的日志文件：
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12144630/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12144631/Player.log)

**Comment by Bright1192** [comment]
https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/releases/tag/v0.5.0
