### ISSUE TITLE
在使用工具箱下载汉化文件时显示“访问Bootstrap.dll路径被拒绝”

### ISSUE THREAD

**Issue by Evan-lob** [LocalizeLimbusCompany/LocalizeLimbusCompany#150]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，这次版本大更新后，我阅读了汉化组2天前的汉化模组更新指引动态，先删除了“Mods/Localize”文件夹，并按照官网上的教程更新了我的工具箱，开始安装。
此时出现了如图一的报错，我尝试参考常见问题的处理方法切换设置，但仍有如图二的报错，我也试过开启加速器，但无济于事。

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12180000/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12180001/default.log)

### 截图

![屏幕截图 2023-07-27 141238](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140688665/4cf2e784-cfb6-42fa-9a3c-863610b7b4cf)
![屏幕截图 2023-07-27 141434](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/140688665/fa339c08-d1b3-41cc-81d6-c563259c6ac6)

**Comment by Bright1192** [comment]
通常来讲这个提示意味着
- 你在运行游戏运行了工具箱，很显然没有办法在文件占用的情况下更新文件
- 你的杀毒软件阻止了这个操作
