### ISSUE TITLE
游戏闪退

### ISSUE THREAD

**Issue by suppereasy** [LocalizeLimbusCompany/LocalizeLimbusCompany#151]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏闪退了，前天还在玩的更新后不行

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12182693/default.log)

**Comment by Bright1192** [comment]
这个log看不出什么，因为你没有上传正确的log
建议你使用安装箱重新安装
若仍然出现此问题请仔细阅读issue上传须知一栏上传正确的文件

**Comment by suppereasy** [comment]
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12184186/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12184187/Player.log)
我上传了新的 现在重新安装后可以启动了。
