### ISSUE TITLE
打开游戏后控制台弹出，并存在游戏白屏，但稍后闪退，无错误弹窗

### ISSUE THREAD

**Issue by MHMS777** [LocalizeLimbusCompany/LocalizeLimbusCompany#155]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用最新模组安装器安装（我之前自己下github装的都没什么事来着）
在“模组常见问题”中有类似情况，但在使用梯子后仍无效

### 日志文件

[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12267510/default.log)
[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12267511/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12267513/Latest.log)

### 截图

![QQ图片20230805224405](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/38040054/fed5d0b0-a765-4141-8539-78841b6f1cee)

**Comment by ZengXiaoPi** [comment]
哦，getfastestnode出问题了，那就没办法了，属于网络问题，手动安装吧，或者安装器把使用MelonLoader For LLC去掉
