### ISSUE TITLE
加载时出现一行红字

### ISSUE THREAD

**Issue by MirageRabbit** [LocalizeLimbusCompany/LocalizeLimbusCompany#156]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

加载时出现一行红字，游戏中似乎没受到影响。

[00:01:55.586] [MelonStartScreen] Failed to find the signature for field m_D3D12WaitForLastPresentationAndGetTimestamp in module. Signature: 48 89 5c 24 08 57 48 81 ec 90 00 00 00 0f 29 b4 24 80 00 00 00 48 8b d9

### 日志文件

[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12293443/default.log)
[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12293445/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12293448/Latest.log)

**Comment by ZengXiaoPi** [comment]
这个bug对实际体验没有任何影响，仅是造成无法使用启动页面
