### ISSUE TITLE
最近4.2安装器更新完之后，打开游戏控制台红字，闪退

### ISSUE THREAD

**Issue by pickleRaink** [LocalizeLimbusCompany/LocalizeLimbusCompany#158]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天看见游戏公告里说下载4.2安装器，下载下来更新后，打不开游戏，控制台里红字报错，然后闪退，检查了一下，好像是BepInEx报错，只有bepinex里面有两个记录的错误日志，真的看不懂，求帮助。

### 日志文件

[ErrorLog.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12318520/ErrorLog.log)
[LogOutput.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12318521/LogOutput.log)

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/141985166/32ca6f8e-951e-4db1-96b4-d268019faa4b)

**Comment by ZengXiaoPi** [comment]
再次尝试。
