### ISSUE TITLE
汉化更新后的问题

### ISSUE THREAD

**Issue by szy2333** [LocalizeLimbusCompany/LocalizeLimbusCompany#159]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

汉化更新后有的文字缺失

### 日志文件

![MB 3 YK$ESDVUQ(1CI$9)9](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/142065926/5957c79a-1eac-4768-8577-ebee241ccc26)

### 截图

![MB 3 YK$ESDVUQ(1CI$9)9](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/142065926/da1ceb50-e647-4640-881b-c54db7e8cd24)

**Comment by ZengXiaoPi** [comment]
使用工具箱

**Comment by N071** [comment]
看起来您没有正常安装字体文件。如果您先前没有使用工具箱，我们推荐您使用工具箱安装汉化。或者，您可以手动安装字体文件。
