### ISSUE TITLE
自动安装汉化补丁后，无法进入游戏

### ISSUE THREAD

**Issue by lagbug51** [LocalizeLimbusCompany/LocalizeLimbusCompany#163]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装了汉化包之后，我将其中的压缩包解压，并将常见问题中的汉化无显示中提供的图片作为参照将游戏目录中的压缩包解压，并将其中的四个文件剪切复制到游戏目录中，使得游戏目录中也不多不少地存在12个文件，之后我打开自己的加速器，随后打开steam，并选择了打开游戏，之后游戏便闪退了，重复了多次，仍未有效果，并且我检查了自己的net6，确实有安装，于是来求助制作组的大佬

### 日志文件

[ErrorLog.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12377307/ErrorLog.log)
[LogOutput.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12377308/LogOutput.log)

### 截图

![屏幕截图 2023-08-18 164401](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/113422049/92c812db-26e0-494f-8611-3d5b89808efb)
![屏幕截图 2023-08-18 164639](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/113422049/cd510d75-b4fb-43fc-b562-12a6c1a7c69d)
![屏幕截图 2023-08-18 165413](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/113422049/d8f31246-1ae4-428f-9cb0-cb882f9628e2)

### 还有别的吗？

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/113422049/a154499d-a8e1-4383-8500-f478edb81d40)

**Comment by Bright1192** [comment]
如果不知道你在做什么请使用BIE_LLC(ver6.0.1)版本,他解决了网络问题和非预期用户行为

**Comment by lagbug51** [comment]
这个版本需要在哪里获取

**Comment by ZengXiaoPi** [comment]
盲猜你在河南。

**Comment by ZengXiaoPi** [comment]
对于任何网络问题，我们都几乎无法给予任何解决方案，这是因为我们**下载方案的局限性**。
~~说白了没钱不然就不会用廉价的下载方案了~~
