### ISSUE TITLE
更新后显示韩文而且无法选择别的文字

### ISSUE THREAD

**Issue by szy2333** [LocalizeLimbusCompany/LocalizeLimbusCompany#167]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

更新后显示韩文而且无法变更别的文字？文字模组已经重新安装过

### 日志文件

无法选择别的文字

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/142065926/92582a30-e1e5-4bcb-8e30-be6d40b59656)

**Comment by szy2333** [comment]
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/142065926/0934ccb0-ad12-4adf-97ec-c1f440a8d332)

**Comment by szy2333** [comment]
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/142065926/99891486-865e-46b8-a8e9-5e2dd18036ac)

**Comment by ZengXiaoPi** [comment]
需要上传日志文件，日志文件位置在你提交issue的时候就应该已经写了。
