### ISSUE TITLE
无法正常进行登录

### ISSUE THREAD

**Issue by difterist** [LocalizeLimbusCompany/LocalizeLimbusCompany#168]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

![CC{YL7}M%C1OF8WMHSO$4WC](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/144010939/fc403346-1700-4cba-ac8d-406b83047278)
![%$)TOJD4`TNE6@M~QJ2T3VE](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/144010939/02825153-112f-4c6e-9eb0-a668a91befb0)

### 日志文件

[Player.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12512505/Player.log)

**Comment by ZengXiaoPi** [comment]
并非汉化补丁问题。
