### ISSUE TITLE
白屏卡死

### ISSUE THREAD

**Issue by liyuu13** [LocalizeLimbusCompany/LocalizeLimbusCompany#169]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在我安裝完成漢化mod之後打開遊戲遊戲會直接白屏卡死，而且無法關閉遊戲，就算是任務管理器也不行

### 日志文件

[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12520259/default.log)
[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12520260/default.log)

**Comment by N071** [comment]
版本过时 此问题已解决
