### ISSUE TITLE
无法运行汉化补丁

### ISSUE THREAD

**Issue by clarthur712** [LocalizeLimbusCompany/LocalizeLimbusCompany#170]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

你好。在今天9月7日边狱巴士的更新之后，我打开游戏，但是汉化补丁的脚本并没有运行。在昨天也就是月计未进行更新前，使用的汉化补丁是最新的，可以运行，并没有任何问题。

当时使用的是v0.4.2版本的工具箱，随后用工具箱的功能删除了汉化补丁，也卸载了该工具箱，并从零协会官网下载了当期最新的版本（即 v0.4.4），使用的节点是**OneDrive For Business**。

把工具箱压缩包解压和运行后，发现工具箱的日志文件里有以下ERROR：
**记录时间：2023-09-07 18:48:37,884 日志级别：ERROR - 描述：出现了问题。
System.NullReferenceException: Object reference not set to an instance of an object.
   at LLC_MOD_Toolbox.MainPage.CheckToolboxUpdate(String version, Boolean IsGithub)**

之后尝试下载汉化，安装器默认从Onedrive For Business下载。下载后发现工具箱日志里有以下INFO：
**记录时间：2023-09-07 19:24:26,367 日志级别：INFO  - 描述：未检测到正确Bepinex**

显示汉化安装完成后，参阅了零协会官网>排除网络问题的综合指引，发现我的游戏的根目录**没有**以下文件和文件夹：
- winhttp.dll
- doorstop_config.ini
- dotnet
- log文件（两个都没有）

同时，**BepInEx**文件夹里**只有Plugin**文件夹。

我尝试卸载并从OneDrive节点重新安装工具箱多次，日志里显示的ERROR都相同。下载汉化后游戏根目录的情况也如同上述。

之后我**转用Las Vegas服务器节点**来下载工具箱，解压后运行工具箱，查看工具箱日志，依旧出现了同样的ERROR描述。
但点击下载汉化后，发现游戏根目录出现了winhttp.dll、doorstop_config.ini和dotnet，BepInEx里也有了config和core。
但是依旧**没有游戏目录日志文件**，运行游戏时也**没有汉化脚本出现**。

### 日志文件

安装汉化后，游戏根目录没有游戏日志.log和框架日志.log日志文件

工具箱日志文件 （OneDrive）：
[Log-20230907.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12548163/Log-20230907.log)

工具箱日志文件 （Las Vegas服务器）：
[Log-20230907.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12548478/Log-20230907.log)

（*两个工具箱文件路径皆为D:\LLC_MOD_Toolbox\Logs）

### 截图

零协会工具箱 v0.4.4 文件 （从OneDrive For Business和美国Las Vegas服务器下载的都相同）：
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87259441/7b14d131-8ab1-46c2-9ca5-57053e26a86c)

安装汉化后的游戏根目录（使用从OneDrive下载的工具箱）：
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87259441/fd2575a3-bf06-4af1-9b86-d793f9ad6fdd)

安装汉化后的游戏根目录（使用从Las Vegas服务器下载的工具箱）：
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/87259441/a5b00d1f-6471-464d-8853-8d4a01ad82b4)

### 还有别的吗？

本人电脑的操作系统为Win 10 (64-bit)

**Comment by ZengXiaoPi** [comment]
这个问题目前只有一个玄学的方法：安装后放置几天，可能会自行修复。

**Comment by clarthur712** [comment]
好的好的，感谢您的回复🙏

**Comment by N071** [comment]
首先，您可以试试我们的帮助页面内的“文件覆盖”方案，通过该方案下载的文件一定是完整可用的。

我明白“等几天”这个玄学的答案听起来确实有点让人哭笑不得，但是大部分人确实是这样的。
我们组内的两位成员，以及**前天**和一周前联系我们的**两位**用户都出现了这个幽灵问题，并**都**在几天过后魔法般的恢复了。
很抱歉我们真的无法复现定位并修复这样奇怪的问题，还请试试看。

**Comment by cothurn** [comment]
我个人之前也遇到了这个问题，但是现在不太记得当时怎么解决的了、
不好意思不能提供更多的信息，只能大概描述一下我现在记得的部分

我印象中当时的问题是toolbox因为莫名的原因没有真的下载BepInEx本体，然后我去https://github.com/LocalizeLimbusCompany/BepInEx_For_LLC
把latest release解压到游戏根目录，再次打开游戏就好了

**Comment by N071** [comment]
> 我个人之前也遇到了这个问题，但是现在不太记得当时怎么解决的了、 不好意思不能提供更多的信息，只能大概描述一下我现在记得的部分
> 
> 我也是用toolbox安装汉化模组之后开启游戏发现什么都没有变，也没有奇奇怪怪的terminal window提示我“你在这个游戏里装了mod” 我印象中当时的问题是toolbox因为莫名的原因没有真的下载BepInEx本体，然后我去https://github.com/LocalizeLimbusCompany/BepInEx_For_LLC 把latest release解压到游戏根目录，再次打开游戏就好了

了解，谢谢您的更多信息，不过我觉得您这里提到的安装问题和我们遇到的此问题表现不一样。即便是通过[文件覆盖流程](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)手动安装的完好文件，也会受此问题影响。

**Comment by ZengXiaoPi** [comment]
在此对此问题的一个解决方案进行补充：
使用管理员模式启动LimbusCompany.exe
