### ISSUE TITLE
开启github自动更新选项后提示模组（字体文件）存在更新，但是已经是最新版

### ISSUE THREAD

**Issue by cothurn** [LocalizeLimbusCompany/LocalizeLimbusCompany#171]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

根据wiki的描述：https://www.zeroasso.top/docs/community/togglefeature 开启 “是否从GitHub自动检查并下载更新”之后，每次进入游戏会收到如下提示：
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/14202194/c1b2006d-1c04-4ddf-918c-b69480f10c1e)
但是游戏文件夹内tmpchinesefont文件已经是最新版：
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/14202194/9afe6a65-d544-48ec-85bc-e7b4994827ee)
不影响使用，但是有点烦。

### 日志文件

两个log我都看了一眼，没看到跟这个问题相关的内容
但是 just in case：
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12555406/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12555407/Player.log)
[LogOutput.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12555414/LogOutput.log)
_顺便提一下github issue模板里写的还是melonloader，记得改一下_

**Comment by Bright1192** [comment]
最新的字体文件修改时间是8月4日 4:02
1. 你的字体文件确实不是最新的
2. 字体文件的更新方法是比对更新的时间戳(中国时区)假如…你的系统提供的时间戳并不是中国时区那么就会…

**Comment by N071** [comment]
注意到您的字体文件的最后编辑时间是2023年8月3日 3:02PM。在我的电脑上，我的字体的最后编辑时间是2023年8月4日 4:02PM。
我们认为这个问题是由于您的电脑时区并非GMT+8导致的。您的文件也许是最新文件，但因时区差别导致了时间戳不同。如Bright所述，我们检查更新的方式其实是对比时间戳。

**Comment by cothurn** [comment]
的确我电脑不是中国时区……
所以“是否从GitHub自动检查并下载更新”这个功能对于有github access的海外人士其实并不好用是么

**Comment by N071** [comment]
~~盲生你发现了华点~~

这个功能实际上属于我们不愿意让大部分人知道的 Legacy Feature，目前是小范围应用。Wiki主要是我写的（我认为最好还是让有能力的人知道这项功能，但似乎其他开发者更愿意雪藏它）。
虽然很抱歉，但我不确定我们的模组作者 Bright 是否有意愿继续改动并支持这项功能。

如果您喜欢摆脱安装器，可以试着用手动安装或者直接[复制我的文件](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)。

**Comment by cothurn** [comment]
> ~盲生你发现了华点~
> 
> 这个功能实际上属于我们不愿意让大部分人知道的 Legacy Feature，目前是小范围应用。Wiki主要是我写的（我认为最好还是让有能力的人知道这项功能，但似乎其他开发者更愿意雪藏它）。 虽然很抱歉，但我不确定我们的模组作者 Bright 是否有意愿继续改动并支持这项功能。
> 
> 如果您喜欢摆脱安装器，可以试着用手动安装或者直接[复制我的文件](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)。

了解，多谢告知
工具箱其实很好用
我想启用这个功能不是为了摆脱工具箱，而是让我可以每次更新之后不用去”欸今天汉化有没有更新？没有更新我几个小时之后再来看“。所以其实如果游戏内能提示“您的汉化mod已过期，请下载最新版”我觉得就很棒了，这样我就知道啊我该去打开工具箱戳一下update button了。
就当是end user的feedback吧
~~话说回来这个问题体感解决起来其实很简单，加一两行code把时间戳都校正到UTC啦，给font文件名价格version number啦就行了
不过可以理解如果这个东西算legacy feature的话的确也没什么支持它的必要
如果我还记得怎么写c#并且知道这东西该怎么compile的话我就自己改了~~

**Comment by Bright1192** [comment]
在下次版本更新我会使其更符合预期

**Comment by Bright1192** [comment]
你可以试试这个
[LLC_Dev.zip](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12556337/BepInEx.zip)
