### ISSUE TITLE
游戏内汉化不生效

### ISSUE THREAD

**Issue by Nolarwho** [LocalizeLimbusCompany/LocalizeLimbusCompany#174]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在安装了汉化模组最新版本进入游戏后控制台不打开而直接进入，游戏无汉化且设置中语言无中文选项

### 日志文件

游戏目录下无日志文件

### 截图

![QQ图片20230912142059](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/144769251/426d590f-ec4a-487a-af5b-ef149a2df454)
![QQ图片20230912142120](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/144769251/2b551b60-02e9-4a4e-836f-b9b115d8d31d)

**Comment by N071** [comment]
- 向我们提供您游戏根目录的截图，让我们确认您的文件安装完整性。
- 若想确保安装完整，可尝试[文件覆盖](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)

**Comment by Nolarwho** [comment]
此外，尝试过文件覆盖，没有作用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月12日(星期二) 晚上10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 游戏内汉化不生效 (Issue #174)





  
向我们提供您游戏根目录的截图，让我们确认您的文件安装完整性。
 
若想确保安装完整，可尝试文件覆盖

**Comment by ZengXiaoPi** [comment]
**向我们提供您游戏根目录的截图，让我们确认您的文件安装完整性。**

**Comment by N071** [comment]
[Issue170](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/170)叙述的情况符合您的状况吗？如果是，请参考Issue 170内的解决方案。
