### ISSUE TITLE
仅游戏内内容汉化不生效，加载页面有正常显示

### ISSUE THREAD

**Issue by miapupu** [LocalizeLimbusCompany/LocalizeLimbusCompany#175]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

今日（9.14）更新后正常启动游戏，发现仅有标题页面左下角的清除数据和加载页面为汉化，游戏内未显示汉化，检查语言设置为中文后尝试重启游戏未果，于是使用工具箱（V0.4.2）进行更新，再次进入之后依旧是仅游戏内未显示汉化。

在这之后我从零协官网下载了v0.4.4的工具箱，尝试使用最新工具箱进行更新，依旧不显示，于是利用工具箱删除了汉化补丁重新安装，未果。在这之后尝试了手动所需文件再通过工具箱安装方式，依旧未果。

在这之后参考了Issue 170内解决方案，即下载零协提供的可正常运行的完整模组文件直接进行覆盖，依旧是游戏内不显示汉化。

### 日志文件

工具箱日志文件
[Log-20230914.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/1260

框架日志文件
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12604688/Latest.log)

### 截图

游戏文件截图，尝试过了文件覆盖
![QQ截图20230914122742](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/106954704/2d424fca-d621-46ae-b8e3-9223a3b4950e)
标题页面，能看到左下是正常显示汉化的，也能看见汉化补丁的版本号确实是最新
![反馈1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/106954704/f97c44e0-0803-403d-a6ec-b525a60fc7a0)
加载页面，这里也是正常显示汉化
![反馈2](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/106954704/b6b280f9-85db-4a48-bb2d-0a6559f98d66)
确认过有中文选项并且勾选了，甚至重启了不止一次游戏做确认
![反馈截图](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/106954704/e29cbe01-6372-47bc-b41e-c2a33b3bd232)
但是游戏内其他内容都没有显示汉化（这里5协小唐的对话就还是英文）
![反馈3](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/106954704/5df896b8-d493-4190-beb8-0aec33bc1d0c)
随便找了个其它页面做示例，干净的仿佛我直接从没汉化的客户端里截出来一样，但我确实打了汉化补丁
![反馈4](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/106954704/41dc9b11-87af-4b15-8627-b2d936741d24)

### 还有别的吗？

我无法确认该问题是否出现的更早，由于某些原因（指找朋友借了博所以一直上的朋友土区帐号），从9.1日开始我一直是使用移动端登录并进行日常的，这期间中该PC上的边狱公司一直保持在8.31更新后的状态未进行任何更改，包括汉化文件在内。

当然我也清楚最后得到的解决方法估计只有“放上几天就好了”的玄学修理法，不过鉴于我这个症状似乎和前两位有点差别（指其它无关紧要的地方汉化补丁都正常运行），anyway...反正不好使的东西放上几天应该都会正常的....大概？

**Comment by Bright1192** [comment]
v0.6.3己修复
