### ISSUE TITLE
无控制台跳出

### ISSUE THREAD

**Issue by studygod12** [LocalizeLimbusCompany/LocalizeLimbusCompany#176]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我使用的汉化补丁版本已为最新版

### 问题描述

无log,是新下的自动下载器，开启游戏后直接进入游戏，无控制台跳出，无汉化

### 日志文件

无

**Comment by N071** [comment]
检查log是我们定位问题的重要途径，很抱歉在无log的情况下，我们很难替您解决问题。
因此，我建议您尝试我们提供的[文件覆盖方案](https://www.zeroasso.top/docs/question#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%96%87%E4%BB%B6%E8%A6%86%E7%9B%96)，这应该能排除掉大部分影响您安装模组的变量。

**Comment by MLCAF** [comment]
[Log-20230914.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12641265/Log-20230914.log)
[Log-20230914.log20230914.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12641266/Log-20230914.log20230914.log)
[Log-20230914.log20230914.log20230914.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12641267/Log-20230914.log20230914.log20230914.log)
[Log-20230917.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12641268/Log-20230917.log)

**Comment by ZengXiaoPi** [comment]
重复 #170
