### ISSUE TITLE
下载汉化包后游戏无法正常运行

### ISSUE THREAD

**Issue by haku-me** [LocalizeLimbusCompany/LocalizeLimbusCompany#180]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

启动游戏后汉化的窗口会跳出来但游戏页面不会打开，汉化窗口在弹出几行代码后也会相继闪退

### 日志文件

[LogOutput.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12847787/LogOutput.log)
[ErrorLog.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12847788/ErrorLog.log)

### 截图

![KD5D~@FLY4PKO%{3VT4`L%X](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/147420951/caccc74e-4f34-4aec-938e-57a6e89c283c)

**Comment by ZengXiaoPi** [comment]
> 根据日志,你缺少`UnityEngine.CoreModule.dll`文件,请重新下载安装
> 
> ```
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
> File name: 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
>    at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr method, IntPtr obj, IntPtr parameters, IntPtr exc)
> ```

但这是为什么呢，这个文件不是Cpp2il解包出来的吗

**Comment by ZengXiaoPi** [comment]
补充：最近有不少这样的案例，启动后卡死，任务管理器也结束不了

**Comment by ZengXiaoPi** [comment]
还是试试解决这个问题吧，重新开启

**Comment by ZengXiaoPi** [comment]
你先尝试一下卸载后重新安装？卸载按钮在设置内

**Comment by ZengXiaoPi** [comment]
在卸载后初次加载应该会加载很长时间（cpp2il），有任何报错红字吗

**Comment by haku-me** [comment]
初次会加载很久，但是没有报错红字

**Comment by haku-me** [comment]
[LogOutput.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12848027/LogOutput.log)

**Comment by ZengXiaoPi** [comment]
ErrorLog？

**Comment by haku-me** [comment]
[ErrorLog.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/12848065/ErrorLog.log)
不好意思

**Comment by ZengXiaoPi** [comment]
```
[Info   :Il2CppInteropGen] Failed to restore 1 fields
``` 
我想是因为这个，但这很明显不在我们的解决范围之内了，无奈离场

**Comment by haku-me** [comment]
好吧，麻烦您了

**Comment by vegedove** [comment]
我也遇到了相同的问题，在我验证游戏完整性后再重装汉化包问题得到了解决。推测可能是之前版本的汉化补丁没删干净导致的

**Comment by mostimabk** [comment]
> 我也遇到了相同的问题，在我验证游戏完整性后再重装汉化包问题得到了解决。推测可能是之前版本的汉化补丁没删干净导致的

兄弟可以具体说说你是怎么解决的吗？这个问题已经困扰我半个多月了。删除重装汉化补丁的时候，你是删除了BeplnEx、dotnet这两个文件夹和doorstop_config.ini、winhttp.dll这两个文件是吗？还是说还有别的文件需要删除？谢谢！

**Comment by mostimabk** [comment]
> > 我也遇到了相同的问题，在我验证游戏完整性后再重装汉化包问题得到了解决。推测可能是之前版本的汉化补丁没删干净导致的
> 
> 兄弟可以具体说说你是怎么解决的吗？这个问题已经困扰我半个多月了。删除重装汉化补丁的时候，你是删除了BeplnEx、dotnet这两个文件夹和doorstop_config.ini、winhttp.dll这两个文件是吗？还是说还有别的文件需要删除？谢谢！

我之前尝试过让另一个朋友把他能用的整个游戏文件夹发给我粘贴上去，但我还是没办法解决这个问题TAT

**Comment by ZengXiaoPi** [comment]
https://www.zeroasso.top/docs/question#%E6%A8%A1%E7%BB%84%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E4%BD%86%E6%89%93%E5%BC%80%E6%B8%B8%E6%88%8F%E6%97%A0%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%BC%B9%E5%87%BA%E4%B8%8D%E5%94%A4%E8%B5%B7bepinex

**Comment by mostimabk** [comment]
> https://www.zeroasso.top/docs/question#%E6%A8%A1%E7%BB%84%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E4%BD%86%E6%89%93%E5%BC%80%E6%B8%B8%E6%88%8F%E6%97%A0%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%BC%B9%E5%87%BA%E4%B8%8D%E5%94%A4%E8%B5%B7bepinex

之前试过了，即使文件覆盖也还是没有解决

**Comment by vegedove** [comment]
> > > 我也遇到了相同的问题，在我验证游戏完整性后再重装汉化包问题得到了解决。推测可能是之前版本的汉化补丁没删干净导致的
> > 
> > 
> > 兄弟可以具体说说你是怎么解决的吗？这个问题已经困扰我半个多月了。删除重装汉化补丁的时候，你是删除了BeplnEx、dotnet这两个文件夹和doorstop_config.ini、winhttp.dll这两个文件是吗？还是说还有别的文件需要删除？谢谢！
> 
> 我之前尝试过让另一个朋友把他能用的整个游戏文件夹发给我粘贴上去，但我还是没办法解决这个问题TAT

除了你说的这几个文件之外还删了之前比较早版本低的几个汉化包，在steam游戏页面右键->验证游戏完整性后应该能得到一个干净的目录，再通过工具箱一键安装即可

**Comment by mostimabk** [comment]
> > > > 我也遇到了相同的问题，在我验证游戏完整性后再重装汉化包问题得到了解决。推测可能是之前版本的汉化补丁没删干净导致的
> > > 
> > > 
> > > 兄弟可以具体说说你是怎么解决的吗？这个问题已经困扰我半个多月了。删除重装汉化补丁的时候，你是删除了BeplnEx、dotnet这两个文件夹和doorstop_config.ini、winhttp.dll这两个文件是吗？还是说还有别的文件需要删除？谢谢！
> > 
> > 
> > 我之前尝试过让另一个朋友把他能用的整个游戏文件夹发给我粘贴上去，但我还是没办法解决这个问题TAT
> 
> 除了你说的这几个文件之外还删了之前比较早版本低的几个汉化包，在steam游戏页面右键->验证游戏完整性后应该能得到一个干净的目录，再通过工具箱一键安装即可

还是不行（笑哭），似乎不是之前版本汉化包的问题（6月份的时候我下过一次汉化包，当时是能用的，但是后来在某次更新当中突然就产生了这个问题，那时候因为别的原因退游了一段时间，现在再重新回坑还是这个问题，还以为是跟你的情况一样），不过还是谢谢了

**Comment by Anchananshan** [comment]
请问这种情况怎么处理
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/171017597/a4b692d3-75e7-4ff0-b904-07afdd281d9b)

**Comment by ZengXiaoPi** [comment]
> 请问这种情况怎么处理 ![image](https://private-user-images.githubusercontent.com/171017597/334332677-a4b692d3-75e7-4ff0-b904-07afdd281d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTQ4MjksIm5iZiI6MTcxNjg5NDUyOSwicGF0aCI6Ii8xNzEwMTc1OTcvMzM0MzMyNjc3LWE0YjY5MmQzLTc1ZTctNGZmMC1iOTA0LTA3YWZkZDI4MWQ5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMTA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTljYjNjYjRjN2ZlODBkMmIzMTYzMWM3ZDNiMDZmNGQ4ZGE3ZTM5Y2MyMDdiNmMzYWM0MzFhZTFlNzRiYzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MJqZMRVsfIduovXoT2LSgkI4Cvqr1jUvgSV9d7dIVC8)

**请新开一个Issue，而不是在已有的Issue中提出问题**
