### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by mostimabk** [LocalizeLimbusCompany/LocalizeLimbusCompany#181]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

开始游戏之后他会跳出一个黑色的框（见下面的截图），过一段时间后这个框就会自行关闭，再次开始游戏也还是这样。我已经尝试过文件覆盖的方法但仍然没有解决

### 日志文件

[ErrorLog.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13052761/ErrorLog.log)
[LogOutput.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13052763/LogOutput.log)

### 截图

![屏幕截图 2023-10-20 173437](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/147811554/c432b938-25e2-4ed1-b6fb-9a28afb19db3)
![屏幕截图 2023-10-20 173512](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/147811554/2b66d8f5-8192-467d-bec9-bb7fc1f762f2)

**Comment by Bright1192** [comment]
你可以参考 #180
