### ISSUE TITLE
关于异想体部位标注的“可破坏和提取部位”

### ISSUE THREAD

**Issue by Xheepey87** [LocalizeLimbusCompany/LocalizeLimbusCompany#183]
### 说说你遇到的问题？

最近给朋友推荐这个游戏，今天打无头鱼的时候他问我“可提取部位”是什么，一时间我也没看懂，转回英文才明白是怎么回事，于是来此反馈一下。

“可破坏和提取部位”的对比（仅英文）如下图所示：

![Snipaste_2023-11-13_10-26-50](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/40490528/7da7ea10-837a-4c4e-9312-55006e0d4e50)

按[英文维基](https://limbuscompany.fandom.com/wiki/Abnormalities)的说法，Destructible是可破坏的，机制是该部位血量归零后伤害类型抗性变为致命，而Severable更类似“破碎/断了”，机制是破坏后不可行动也不能指定为目标，对此进行中的攻击也会停止。似乎Severable一定会跟着Destructible。

总之，个人认为“可破坏”没什么问题，但“可提取”不太能表达机制或含义（未参考其他语言），而且游戏本身也有“提取”这一动作，我那个新入坑的朋友甚至以为这个意思是打败后可以提取ego。

此外有个小问题，“可破坏和提取部位”与单独的“可破坏”不协调（多了/少了“部位”一词）。附“可破坏”的对比（仅英文）：

![Snipaste_2023-11-13_10-28-45](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/40490528/7261561e-c5fc-40f4-aa5f-11f79d79e440)

**Comment by Bright1192** [comment]
感谢您对零协会的关注，可提取部位应该被翻译为"可截除部位"，之前被翻译成"提取"是因为预载时只有韩文且我们不知道它是用在什么地方的
至于多了/少了"部位"一词实际上日文与韩文确实单独指出了部位，而且也有一个单独的"可破坏部位"的词条
