### ISSUE TITLE
模组正常安装，但打开游戏无控制台弹出

### ISSUE THREAD

**Issue by dolldeer** [LocalizeLimbusCompany/LocalizeLimbusCompany#184]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

模组正常安装，但打开游戏无控制台弹出，不唤起BepInEx. 在大概九月之前均可正常使用，现在使用兼容模式启动、等待（约两个月）、文件覆盖均无反应。工具箱版本为v0.6.0。在手动安装界面点击“下载压缩包”按钮显示“应用程序中发生了未经处理的异常”，详细信息如下：
************** 异常文本 **************
System.ComponentModel.Win32Exception (0x80004005): 没有应用程序与此操作的指定文件有关联。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 Sunny.UI.UIControl.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### 日志文件

[Log-20231118.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13395323/Log-20231118.log)

### 截图

![20231118022845](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/151113728/15afd141-38a6-4b3e-9abe-7ef462d71201)

**Comment by ZengXiaoPi** [comment]
尝试使用管理员模式启动
至于为什么点击下载压缩包报错。。。你的电脑有默认浏览器吗
