### ISSUE TITLE
11月23日更新后导致剧情汉化失效

### ISSUE THREAD

**Issue by VictorVvVv** [LocalizeLimbusCompany/LocalizeLimbusCompany#185]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

11月23日更新之后，似乎仅有剧情汉化失效，游戏的其他部分文本均正常，已尝试过重新安装汉化补丁。

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13445843/Player.log)

### 截图

![1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/46399694/3d3d556d-f074-48d7-9a70-104814f00a4e)
![2](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/46399694/51d499a1-a947-46df-bf8c-9eda1ee83797)

**Comment by ZengXiaoPi** [comment]
此问题会在下个版本修复。

**Comment by uselessand** [comment]
呃但是现在又出现了这个问题

**Comment by Bright1192** [comment]
**下个版本**，也许你们阅读理解不太好

**Comment by uselessand** [comment]
呃对不起，我看到这里显示已修复还以为已经好了，很抱歉带来麻烦
&nbsp;


事仙贝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月24日(星期五) 晚上11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 11月23日更新后导致剧情汉化失效 (Issue #185)





 
下个版本，也许你们阅读理解不太好
