### ISSUE TITLE
打开游戏无控制台弹出，无汉化

### ISSUE THREAD

**Issue by yy11y** [LocalizeLimbusCompany/LocalizeLimbusCompany#190]
### 说说你遇到的问题？

上个月的时候打开游戏突然控制台就不弹出了，之前汉化都是正常的。
以为是更新的问题就去下载了最新的工具箱【自动安装】重新安装了汉化模组，然后还是不行，我就用工具箱【手动安装】又安装了一次，依然，试过了文件覆盖还是
于是我清除了工具箱，重装了游戏，这会按照指示完全手动安装了一遍
这是手动安装完的文件目录：
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/152514984/3d1a476a-4420-48b2-b1e2-e7dcedee0639)
这是BepInEx\plugins文件夹内：
![Uploading image.png…]()

重启游戏还是不弹出，我放了十几天没开它打开还是
救救救救呜呜

**Comment by ZengXiaoPi** [comment]
http://zeroasso.top/docs/question

**Comment by yy11y** [comment]
这个我看了！原来是目前除了等也没有别的办法吗……感谢您的回复！！

**Comment by ZengXiaoPi** [comment]
错误的，可以用管理员模式启动一下

**Comment by ZengXiaoPi** [comment]
另外
duplicate of #170

**Comment by yy11y** [comment]
> 错误的，可以用管理员模式启动一下

尝试过了，控制台还是不理我x还是感谢您！！

**Comment by yy11y** [comment]
> 另外 duplicate of #170
全部看完了！非常感谢…！
