### ISSUE TITLE
自动更新（？）获取的压缩包错误

### ISSUE THREAD

**Issue by FallingString** [LocalizeLimbusCompany/LocalizeLimbusCompany#191]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

疑似在使用v0.6.0的零协会工具箱-更改配置-补丁相关-使用自动更新的有关功能时所下载的压缩包无法被正确识别从而无法解压（由于我对于该问题从属于“模组问题”还是“框架问题”并不清楚，所以同时上传了两个日志文件。另外，似乎需要勾选“我使用的汉化补丁版本已为最新版”才能进行反馈，但在问题发生时这与事实不符，特此说明，希望没有干扰你们的工作）

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13536074/Player.log)
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13536075/Latest.log)

### 截图

![屏幕截图 2023-12-02 190357](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/152694837/08724b98-396d-4bc2-b630-dd89776743a0)
![屏幕截图 2023-12-02 190409](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/152694837/d644ecb3-fa07-4c42-b8f0-39a7828cb61f)

### 还有别的吗？

使用的解压软件：BandiZip、7Zip
操作系统：Win11家庭中文版
CPU：AMD Ryzen 9 7940H w/ Radeon 780M Graphics
显卡：AMD Radeon 780M Graphics（驱动程序版本：31.0.14070.6001）
           NVIDIA GeForce RTX 4060 Laptop GPU(驱动程序版本：31.0.15.4601)

**Comment by ZengXiaoPi** [comment]
已修复。
