### ISSUE TITLE
关于镜像地牢中罪人判定时的文本问题。

### ISSUE THREAD

**Issue by silence61** [LocalizeLimbusCompany/LocalizeLimbusCompany#194]
在翻WIKI的时候发现其实罪人对于异想体事件判定时不同的概率会有不同的文本，但模组内对概率高和极高与低和极低时罪人的回应只有一种文本，如以实玛丽在极高概率的情况下文本为“应该可行。如果你的计划不会像艘破烂搁浅的船一样。”但实际上文本应为“问我行不行？别特地问些理所应当的事。”（来自边狱巴士的WIKI），希望零协能够尽快完善这方面问题，感谢全体汉化组人员的付出。

_Originally posted by @silence61 in https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/discussions/193_

**Comment by N071** [comment]
这个Issue的内容似乎被重复发进了Discussion下的Q&A Section。最新回复请移步：[Discussions#193](https://github.com/orgs/LocalizeLimbusCompany/discussions/193#discussioncomment-7829146)

**Comment by N071** [comment]
最新的情况更新在 [Discussions#193](https://github.com/orgs/LocalizeLimbusCompany/discussions/193#discussioncomment-7829146) 处继续，故关闭此Issue。
