### ISSUE TITLE
镜牢饰品翻译捉虫（员工证二级强化应为共鸣而不是完全共鸣）

### ISSUE THREAD

**Issue by bugtheworld** [LocalizeLimbusCompany/LocalizeLimbusCompany#195]
### 说说你遇到的问题？

镜牢3饰品员工证二级强化的翻译疑似有问题，英文中是resonance，中文写成了完全共鸣
![20231215231455_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/98cebbdf-c210-4218-8803-caa93c61a5bd)
![20231215231744_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/74230583/1709f6d5-ba98-4b44-993e-ea3fa496c73b)

**Comment by shixie2860** [comment]
这个问题已在昨天凌晨的校对工作中发现并修正，您能在下个版本的模组中得到已修正后的结果，感谢您的支持与帮助。

**Comment by N071** [comment]
我们在翻译的时候没有注意到二阶升级的条件变化，直接使用了粘贴的文本。总之再次感谢您的指正！
