### ISSUE TITLE
星光节点文本问题

### ISSUE THREAD

**Issue by arc-xing** [LocalizeLimbusCompany/LocalizeLimbusCompany#197]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

星光节点丰功伟绩周围小星光文本问题，有两个节点文本为沉沦相关，实际其中一个应为充能相关

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13798137/Player.log)

### 截图

![9G@@6A))LGE80)A9A15HU}2](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/155238570/63f8c30c-c9f7-476c-9be5-ad9c69e5aa69)
![ZHY5VP@533 $1(M{UG5%MCE](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/155238570/bdef527b-38eb-4530-a148-e331af0d79e2)

**Comment by ZengXiaoPi** [comment]
**请更新到最新版本汉化**
