### ISSUE TITLE
游戏中部分地方显示为韩文

### ISSUE THREAD

**Issue by MisUniStu** [LocalizeLimbusCompany/LocalizeLimbusCompany#198]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

游戏中部分地方显示为韩文
如兔希使用技能过程中的弹药不足提示，以及通行证最左侧的免费/通行证标识

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13800201/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/13800203/Player.log)

### 截图

![QQ截图20231231115905](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/134506939/bd611d11-245a-4391-8811-546c63d743c9)
![QQ截图20231231120905](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/134506939/15dfcbb2-0013-4b7a-a56e-a3f95697aa2a)

**Comment by ZengXiaoPi** [comment]
1. 尝试更新模组
2. 有的地方是月计写死的，比如兔子的子弹耗尽
