### ISSUE TITLE
4-54迷宫里打神备东朗第一回合结束后界面卡住，多次重启无效

### ISSUE THREAD

**Issue by BaeyerVilliger** [LocalizeLimbusCompany/LocalizeLimbusCompany#199]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

只有这一关卡在这里，无法进行只能退出，不论回到存档点还是重新进迷宫都会卡在这里。

### 日志文件

[Uploading Player(游戏日志).log…]()
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14127532/Latest.log)

### 截图

<img width="960" alt="1" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158487717/8ab784bf-faa8-429e-976a-bdab4e1375e1">

**Comment by ZengXiaoPi** [comment]
1. **游戏日志未上传**
2. 按照描述情况，应为游戏Bug。
3. 尝试关闭汉化补丁再次进入游戏测试，若仍有问题请Re-Open此议题。

**Comment by Bright1192** [comment]
请去看月亮计划的最新公告，不要再把月亮的问题当成汉化模组的问题了
从理论上来说汉化模组根本不可能造成这种问题
