### ISSUE TITLE
三号线失物招领处翻译的一处错误

### ISSUE THREAD

**Issue by ParseeVVVIP** [LocalizeLimbusCompany/LocalizeLimbusCompany#200]
### 说说你遇到的问题？

三号线失物招领处40个碎片自选箱下方标注的是第8站，然而此奖励是第九站通过后的奖励。
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/101053728/6957f29a-4000-4c12-bf92-058798c05ed4)
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/101053728/d17c0fa9-4f31-45af-83a8-283f69732959)

**Comment by N071** [comment]
很抱歉我在更新完新版本之后才意识到这里有个issue，这几天有点忙忘了……实在是很抱歉。
**首先，非常感谢您对此错误的提交！！**
我检查了我们的文本，这里的站点错位和之前的重复问题是因为我们在某处填充错位导致的。这个问题已经被我们修复，但因为我的疏忽 ~~到家第一件事只想着赶紧发新版~~ 很可惜这里的修复只能在下个版本里体现了。
实在抱歉。

**Comment by N071** [comment]
~~情况更新：JP原译文出问题了，把我们全带歪了~~
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/128023427/007d01fa-126f-4c08-9578-8b2c6e6072d0)
