### ISSUE TITLE
试图更新汉化补丁时电脑报错

### ISSUE THREAD

**Issue by FourtyThree413** [LocalizeLimbusCompany/LocalizeLimbusCompany#201]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

打开汉化补丁安装包后点击立刻安装/更新，随后便出现了以下Logs中的报错，这个报错窗口出现了两次，随后汉化补丁就自己退出了。
我试着上传报错页面的截图，但是似乎无法上传到Github上，只能先传一下Logs。

### 日志文件

[Log-20240208.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14208184/Log-20240208.log)

**Comment by ZengXiaoPi** [comment]
<s>我可没有北岚那么热心肠所以先让我睡一觉再解决这个问题</s>
刚刚在网上查了，没什么头绪，而且没法复现，总之先让我睡一觉

**Comment by FourtyThree413** [comment]
好的好的，辛苦了w

**Comment by N071** [comment]
您使用了群内获取到的测试版的安装器吗？如果是，还请麻烦您回退至[062稳定版](https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/releases/tag/v0.6.2)使用。Log显示您的崩溃可能与测试版新功能相关。我们(小皮)正在研究此问题。

**Comment by FourtyThree413** [comment]
我在测试版和稳定版都有尝试过，得到的都是同样的报错。也可能是网络问题，我之后试试用手机wifi连看看

**Comment by FourtyThree413** [comment]
我试着用手机wifi连了但还是有同样的报错...因为隔壁暗潮打开启动器也会报类似的错推测应该是跟自动更新之类的功能有关 但是我不懂编程语言所以根本看不懂这个报错问题出在哪....
