### ISSUE TITLE
脑叶公司朱符三技能四破后缺字

### ISSUE THREAD

**Issue by haoge114** [LocalizeLimbusCompany/LocalizeLimbusCompany#202]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在玩游戏的时候发现四破后的脑叶公司朱浮三技能少了个“咒”字，在查找文本的时候发现三破为“破裂符咒”，四破为“破裂符”

### 日志文件

无

### 截图

![Screenshot_2024-02-23-20-32-30-85_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/110206148/cd4d5dee-7f40-4dbf-9205-7d7fb3020443)

**Comment by haoge114** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我使用的汉化补丁版本已为最新版
> 
> ### 问题描述
> 在玩游戏的时候发现四破后的脑叶公司朱符三技能少了个“咒”字，在查找文本的时候发现三破为“破裂符咒”，四破为“破裂符”
> 
> ### 日志文件
> 无
> 
> ### 截图
> ![Screenshot_2024-02-23-20-32-30-85_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/110206148/307321479-cd4d5dee-7f40-4dbf-9205-7d7fb3020443.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTIxNDcsIm5iZiI6MTcwODY5MTg0NywicGF0aCI6Ii8xMTAyMDYxNDgvMzA3MzIxNDc5LWNkNGQ1ZGVlLTdmNDAtNGRiZi05MjA1LTdkN2ZiMzAyMDQ0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMjM3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmEwZDYwMjExYmFhMGE2ZDI0MGY3OTUyMzQ1NGYwYzIzOGEzNGJjYTdjN2M1NjE1MTZmNWY1NTJhOWMwNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RaJOcjfxQAY8go2UIgMaHwohb_cU5lur_IbEH6hKXVQ)
> 
> ### 还有别的吗？
> _No response_

**Comment by N071** [comment]
感谢！这个问题已经被修复，下个版本就会更新~
