### ISSUE TITLE
第四章地牢4D202B和4D304B东郎的语言文本未统一

### ISSUE THREAD

**Issue by haoge114** [LocalizeLimbusCompany/LocalizeLimbusCompany#203]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

4D202B和4D304B中的“동물도 사람이랑 똑같이 아픔을 느낀다는 걸 너도 안다면, 그런 말은 함부로 못 할 걸.”被分别翻译为“如果你知道动物和人一样有痛觉，就不会随便说这种话了。”和“如果你也知道动物能和人一样感受到痛苦的话，应该也不会随意说出那种话了吧。”，我并不清楚应该以哪个文本为准，故上传

### 日志文件

无

### 截图

![Screenshot_2024-03-10-12-52-57-99_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/110206148/d4f0de76-3b02-4770-8e81-5c5a28a09932)
![Screenshot_2024-03-10-12-53-10-81_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/110206148/deb9f52b-7b0c-46ea-ab5b-62b8d14112b9)

**Comment by ZengXiaoPi** [comment]
感谢您的反馈，正在处理。

**Comment by haoge114** [comment]
还有S315B与3D301的이단심문관 1和이단심문관 2，都被分别翻译为“某异端审判官”和“一旁的异端审判官”与“异端审判官1”和“异端审判官2”

**Comment by N071** [comment]
感谢反馈。
> 동물도 사람이랑 똑같이 아픔을 느낀다는 걸 너도 안다면, 그런 말은 함부로 못 할 걸.

此处的翻译不同问题已经修复。

> S315B与3D301的이단심문관 1和이단심문관 2

此处我们参考英文进行翻译。月亮计划偶尔会把带数据标记的条目（比如이단심문관 1、2）放到文件里，但最终**不**对其进行显示。
不过，我们依然暂且按照英文进行较为完整的翻译，而不是也翻译为带数字的“异端审判官1、2”，以防月亮计划**不慎在剧情文本中真的显示了该条目**。
