### ISSUE TITLE
放映室第六章主线剧情内的一处翻译错误

### ISSUE THREAD

**Issue by ParseeVVVIP** [LocalizeLimbusCompany/LocalizeLimbusCompany#205]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

从放映室进入观看剧情时的第三话和第四话均显示为6-3战前剧情
而第四话应是战后剧情

### 日志文件

应该不需要log

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/101053728/aeef4e0d-b8c8-4f07-8b73-d0845c6e0a90)
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/101053728/a9c0a851-67df-44fa-9dbb-400836a9a0bf)

**Comment by ZengXiaoPi** [comment]
问题已反馈。

**Comment by ZengXiaoPi** [comment]
이번에도 네 탓이로군,月亮计划！
（是月亮计划的错）
