### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by CreisYD** [LocalizeLimbusCompany/LocalizeLimbusCompany#206]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

关于第六章第21关剧情中的一个错别字

### 日志文件

这应该。。。不需要日志吧

### 截图

![Image_1711910327437](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/148980908/b7668e6b-e661-4f7a-8518-f5ff42dd5a71)

**Comment by ZengXiaoPi** [comment]
应该已经修了（）下个版本修复
