### ISSUE TITLE
游戏登录界面闪退

### ISSUE THREAD

**Issue by buyaoshuile** [LocalizeLimbusCompany/LocalizeLimbusCompany#207]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

我关闭汉化补丁之后，将游戏内的语言调整为了日语，之后关闭游戏，开启汉化补丁，启动游戏就闪退了，但是我将模组删除并重新安装后就可以正常进入游戏且游戏内语言为中文.此外，删除模组后也可正常进入游戏。

### 日志文件

我并不是很确定是那种问题，所以上传了两个日志。我今天最后一次闪退后就没再尝试登陆，所以问题大概位于最底部。
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14880849/Player.log)
[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14880852/Latest.log)

**Comment by ZengXiaoPi** [comment]
duplicate.of #192
