### ISSUE TITLE
扭曲亨德利半血剧情凯瑟琳人名没翻译

### ISSUE THREAD

**Issue by Jelly-Candy** [LocalizeLimbusCompany/LocalizeLimbusCompany#208]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

扭曲亨德利半血剧情凯瑟琳人名没翻译

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14883786/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14883788/Player.log)

### 截图

![QQ图片20240405183530](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/103652041/8c461c12-fceb-4fff-8ef1-87a624618e59)

**Comment by ZengXiaoPi** [comment]
写死了，修不了
