### ISSUE TITLE
协会人格名称格式统一化

### ISSUE THREAD

**Issue by hgard** [LocalizeLimbusCompany/LocalizeLimbusCompany#209]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

6协科长罗佳与其他科长相比多了个空格，11协希斯克里夫在协会所属区域后面换行而非协会名称后
![20240405204047](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/166131605/9ce1bd68-0834-48bc-8e21-4f22dcc272de)

**Comment by ZengXiaoPi** [comment]
fix
