### ISSUE TITLE
关于 LCB_Chinese_Font.cs 的疑问

### ISSUE THREAD

**Issue by hxdnshx** [LocalizeLimbusCompany/LocalizeLimbusCompany#210]
### 说说你遇到的问题？

注意到 LCB_Chinese_Font 很好地解决了 Unity 游戏中原本使用的字体没有完整支持中文字符集的问题。

于是我尝试以类似的方式应用于其他游戏中，不过发现只有对于以下 API 的 Hook 才是有效的：
```
[HarmonyPatch(typeof(TMP_Text), nameof(TMP_Text.text), MethodType.Setter)]
```

因此，我希望能够获取到在这个项目中，选择 `font` `fontMaterial` 的原因，以及下面的 `TextMeshProLanguageSetter` 与中文支持的关系，这些方面更多的信息，从而得知最优的做法。

**Comment by Bright1192** [comment]
答案当然是"没有关系"，因为这个游戏支持其他语言所以他在切换到其他语言的时候会自然的使用font,fontMaterial的set方法，而TextMeshProLanguageSetter只是这个游戏特有的更新字体的方法罢了
实际上对于只支持其他语言的游戏，因为能在引擎开发时直接设置好字体所以不用再调用相应的set方法(极端一点甚至可以将所有相应的ui都设置好而不调用相应的TMP_Text.text set方法)
对于上述场景显然只有类似于你的[HarmonyPatch(typeof(TMP_Text), nameof(TMP_Text.text), MethodType.Setter/Getter)]才能完成需求，不过这也会显著增加内存开销
