### ISSUE TITLE
只有加载页面有汉化，其余皆无汉化

### ISSUE THREAD

**Issue by KbClownxxx** [LocalizeLimbusCompany/LocalizeLimbusCompany#211]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

只有加载页面和汉化包的公告有汉化，其余都没有汉化

### 日志文件

[Message: Preloader] BepInEx 6.0.1-dev - LimbusCompany
[Message: Preloader] Built from commit 5be339d872201644aa4e408adbccdeb68cccfe7d
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.28f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [LimbusLocalizeMod 0.6.31]
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type LimbusLocalize.LLC_Manager in il2cpp domain
[Message:   BepInEx] Chainloader startup complete
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppSystem.Collections.Generic.Dictionary`2<System.String,LocalizeTextDataRoot`1<TextData_UI>> BgmLyricsJsonDataList.get__lyricsDictionary()'.
   at LimbusLocalize.LCB_Chinese_Font.LoadRemote2(LOCALIZE_LANGUAGE lang)
   at LimbusLocalize.LCB_Chinese_Font.<>c__DisplayClass12_1.<EGOVoiceJsonDataListInit>b__0(LocalizeTextDataRoot`1 data)
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]_LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](IntPtr , IntPtr , Il2CppMethodInfo* )

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/56860845/ee1967ec-d011-4193-9d2a-f4960ccbea91)
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/56860845/37ecc1e4-6df5-4067-bcbe-6ff2a8a0f9fa)

**Comment by N071** [comment]
感谢反馈。此问题已被解决，请等待新版本释放

**Comment by jftygc** [comment]
同遇到此问题，希望能尽快解决😣

**Comment by N071** [comment]
我们计划在准备好翻译文本之后，才进行新版本的释放。若您现在需要使用模组，请尝试[工作流#179](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/actions/runs/8641099731)中的Artifact: [LimbusLocalize_BIE_Dev.7z](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/actions/runs/8641099731/artifacts/1403695212)。
以上是修复后的模组dll文件。您可以使用其置换当前文件。

**Comment by jftygc** [comment]
> 我们计划在准备好翻译文本之后，才进行新版本的释放。若您现在需要使用模组，请尝试[工作流#179](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/actions/runs/8641099731)中的Artifact： [LimbusLocalize_BIE_Dev.7z](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/actions/runs/8641099731/artifacts/1403695212)。 以上是修复后的模组dll文件。您可以使用其置换当前文件。

已解决，感谢🥳
