### ISSUE TITLE
游戏界面和加载界面有汉化但里面没有

### ISSUE THREAD

**Issue by zhenwuyu23** [LocalizeLimbusCompany/LocalizeLimbusCompany#212]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

加载界面有汉化但游戏里面没有汉化

### 日志文件

[Log-20240411.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14944049/Log-20240411.log)

### 截图

[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppSystem.Collections.Generic.Dictionary`2<System.String,LocalizeTextDataRoot`1<TextData_UI>> BgmLyricsJsonDataList.get__lyricsDictionary()'.
   at LimbusLocalize.LCB_Chinese_Font.LoadRemote2(LOCALIZE_LANGUAGE lang)
   at LimbusLocalize.LCB_Chinese_Font.<>c__DisplayClass12_1.<EGOVoiceJsonDataListInit>b__0(LocalizeTextDataRoot`1 data)
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]_LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](IntPtr , IntPtr , Il2CppMethodInfo* )

**Comment by N071** [comment]
请参考https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/211

**Comment by emmlmsjvkjfnkjsnf** [comment]
在提问之前...
 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
 我使用的汉化补丁版本已为最新版
问题描述
只有加载页面和汉化包的公告有汉化，其余都没有汉化

日志文件

[Log-20240411.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14945358/Log-20240411.log)


截图

![屏幕截图 2024-04-11 185846](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/166712003/879b4aed-5696-4812-8cfc-f357e8eea03c)
![屏幕截图 2024-04-11 185832](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/166712003/02c9ce48-0c06-4321-8900-4232adaaac06)

还有别的吗

无

**Comment by N071** [comment]
> 在提问之前... 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况 我使用的汉化补丁版本已为最新版 问题描述 只有加载页面和汉化包的公告有汉化，其余都没有汉化
> 
> 日志文件
> 
> [Log-20240411.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/14945358/Log-20240411.log)
> 
> 截图
> 
> ![屏幕截图 2024-04-11 185846](https://private-user-images.githubusercontent.com/166712003/321608632-879b4aed-5696-4812-8cfc-f357e8eea03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzQzNzksIm5iZiI6MTcxMjgzNDA3OSwicGF0aCI6Ii8xNjY3MTIwMDMvMzIxNjA4NjMyLTg3OWI0YWVkLTU2OTYtNDgxMi04Y2ZjLWYzNTdlOGVlYTAzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMTE0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjk4ZDllNWFjZGFjNzgyMmNjMzczMGEwNzg1ODNmNTZjNmNjMWI5MjY2NTQ5OTU5M2UxMTUzMzhkNmVlZmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K99P9TwTKawFd99FeVJV7KgipdES9X5lQXchTm7BRnk) ![屏幕截图 2024-04-11 185832](https://private-user-images.githubusercontent.com/166712003/321608640-02c9ce48-0c06-4321-8900-4232adaaac06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzQzNzksIm5iZiI6MTcxMjgzNDA3OSwicGF0aCI6Ii8xNjY3MTIwMDMvMzIxNjA4NjQwLTAyYzljZTQ4LTBjMDYtNDMyMS04OTAwLTQyMzJhZGFhYWMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMTE0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2Q5NzViNDQxMjRiOTYwMTdkNWUwNGViODlhNjU2Mjc4YTBkZGVhOGI3NjNlNjg3ODM4ZTQ4MDgzOWVjNzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q_JqYnhHBYCWt6sipNdI3eSqtM9x3461T3ZdOa_2fZ0)
> 
> 还有别的吗
> 
> 无

若无新消息，请勿重复提交相同Issue。在GitHub默认设置以及惯例下，关注此串的所有人都会收到一封邮件。这会挤占注意力。
此问题请参考https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/211
