### ISSUE TITLE
标点符号问题

### ISSUE THREAD

**Issue by SOgz12Z3Ce** [LocalizeLimbusCompany/LocalizeLimbusCompany#216]
### 标点符号不符合规范

但丁笔记内的两处文本似乎不符合标点符号使用规范（GB/T 15834-2011）：

都市 > 收尾人 > 协会 > 六协会 > 记录#3
<img width="621" alt="p1" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/fff61787-a0e0-44fb-bd9e-806a6c22d658">
4.5.3.5：标有引号的并列成分之间、标有书名号的并列成分之间通常不用顿号。[…]

都市 > 异想体 > 记录#2
<img width="602" alt="p2" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/0f47c1d1-4bcd-43d3-a440-60dc4d2821bb">
B.2.1：[…]当引文位于非停顿处或者引号内已使用句末点号时，引号外不用点号。

此外，此字体中的破折号是断开的：
都市 > 巢 > 记录#1
<img width="606" alt="p4" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/adb8c883-4ac0-4c80-9b79-92d51784dca9">
<img width="239" alt="p5" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/f3887982-2198-4396-a1a1-711e8fdbcffe">

**Comment by N071** [comment]
感谢您专业的反馈！问题1、2已经修改。然而，问题3受制于字体的内生性限制，破折号无法链接。
