### ISSUE TITLE
半角括号

### ISSUE THREAD

**Issue by SOgz12Z3Ce** [LocalizeLimbusCompany/LocalizeLimbusCompany#217]
### 说说你遇到的问题？

但丁的笔记中这几处括号疑为半角括号：

都市 > 边狱公司 记录#2
<img width="593" alt="a1" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/252dc19a-7456-4532-88b8-600db626faab">

都市 > 收尾人 记录#1
<img width="634" alt="a3" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/0c3a3383-e2b2-43c5-993c-f76cd458a191">

都市 > 都市的科技 > E.G.O 记录#1
<img width="591" alt="a2" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/a68a1879-027c-4959-8d07-5e247b714ef0">

都市 > 都市的科技 > 人格同步 记录#1
<img width="599" alt="a4" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/7c236355-9859-479d-9459-b5b84adcbadd">

都市 > 都市的科技 > 人格强化 记录#1
<img width="614" alt="a5" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/158081594/586c95f7-5763-4b93-be86-dfbc089669a1">

（上一个Issue恰巧关闭）

**Comment by N071** [comment]
感谢反馈，这些问题已经完成修改。
