### ISSUE TITLE
错误的将采掘翻译成采光

### ISSUE THREAD

**Issue by Jelly-Candy** [LocalizeLimbusCompany/LocalizeLimbusCompany#218]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

错误的将采掘翻译成采光

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15197244/Player.log)

### 截图

![QQ图片20240503153159](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/103652041/2a507fc8-89b4-4051-b660-250ae15432df)
![QQ图片20240503153209](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/103652041/6fbbdaac-03f8-4986-8775-ab55bf668ace)

**Comment by ZengXiaoPi** [comment]
实际上，所谓采掘就应该翻译为采光（）
具体原因别人补充一下

**Comment by N071** [comment]
讨论详见：https://paratranz.cn/projects/6860/issues/18052

**Comment by Jelly-Candy** [comment]
长知识了，最直观感受到翻译的信达雅的一次，大大们辛苦了（
