### ISSUE TITLE
第三次瓦夜战斗结果出现不明口口文学

### ISSUE THREAD

**Issue by Jelly-Candy** [LocalizeLimbusCompany/LocalizeLimbusCompany#219]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

第三次瓦夜战斗结果出现不明口口文学，不知是否为汉化组特意而为

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15198126/Player.log)

### 截图

![QQ图片20240503171911](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/103652041/ceb54fee-706e-41ed-a358-6b2e30f87370)
![QQ图片20240503171920](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/103652041/2c3e4f8d-e57b-4d6f-b012-1941cf1dfa26)

**Comment by N071** [comment]
感谢提醒。这是因为该处文本无法应用我们的中文字库，游戏原字库缺字而出现了方块。我们暂无法解决这个问题。
