### ISSUE TITLE
镜本的魔枪射手事件中第二个选项缺少有ego饰品获取的提示

### ISSUE THREAD

**Issue by superqwea** [LocalizeLimbusCompany/LocalizeLimbusCompany#220]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

汉化没出时，用日文看到是有可以获得ego饰品的提示的，汉化后没有提示

### 日志文件

1

### 截图

![(IB}8BV_3PBVU{OWE4@ 7RB](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/168846348/d35c2b27-9d7e-427a-8fd7-cef09f7b83f6)
![QD }4Z@JJM}T5T97X(1Y`QA](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/168846348/96544ae1-5227-4f6f-a88a-35ee9f50385c)

**Comment by Nephthys137** [comment]
感谢反馈,已修复
