### ISSUE TITLE
纺锤本加成次数显示错误

### ISSUE THREAD

**Issue by duyaMK2** [LocalizeLimbusCompany/LocalizeLimbusCompany#222]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

纺锤本加成次数显示为5/5并且不随战斗次数减少，实际加成次数为3次

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15208554/Player.log)

### 截图

![QQ图片20240504161354](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/73687812/4d16641f-292e-4fdb-95e0-44ff0512fb2e)

**Comment by Nephthys137** [comment]
游戏bug
