### ISSUE TITLE
升阶过人格之后，随机加载图始终锁定在该人格初始立绘

### ISSUE THREAD

**Issue by nukieberry** [LocalizeLimbusCompany/LocalizeLimbusCompany#223]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

上周（更新镜牢4）之前没有发生过类似现象。前几天升阶6协良秀后锁在其初始立绘（而不是新解锁的3阶立绘）上，后来升阶剑箱后同样一直是剑箱初始立绘，再没有出现过别的cg。但今天升阶死兔锁没有变化，依然是箱子。重启游戏、更新模组、主界面清除缓存均无效，没有试过重新安装游戏。希望能修复问题，或者给出清理缓存一类的解决方法。

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15215109/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15215110/Player.log)

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/55907281/9fdeb3b7-c09f-44a0-b1be-9324575e039d)

**Comment by KbClownxxx** [comment]
这个我也有遇到过，看过谁的三破剧情过场就变成他（她）的了

**Comment by Nephthys137** [comment]
显然是游戏bug
