### ISSUE TITLE
读取游戏时闪退

### ISSUE THREAD

**Issue by aree3da** [LocalizeLimbusCompany/LocalizeLimbusCompany#225]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我使用的汉化补丁版本已为最新版

### 问题描述

在今日(5/9)更新后进入游戏，并且在loading读取时闪退
在BepInEx视窗里面有注意到几句warning字眼
已经重新覆盖全量包后还是一样! 谢谢

### 日志文件

[Latest(框架日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15263887/Latest.log)
[Latest(框架日誌).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15263888/Latest.log)
[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15263889/Player.log)
[Player(遊戲日誌).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15263890/Player.log)

### 截图

![Screenshot 2024-05-09 221939](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169376241/6ae41e10-01ca-4021-9be9-9b246c4d4f12)

**Comment by Nephthys137** [comment]
令人遗憾的是,日志上并没有相关错误,所以我无法帮你解决
