### ISSUE TITLE
翻译有误

### ISSUE THREAD

**Issue by WilliamConnor** [LocalizeLimbusCompany/LocalizeLimbusCompany#226]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

镜牢ego饰品合成，合成指南里，2级+3级+3级=4级错误翻译成了2级+2级+3级=4级

### 日志文件

1

### 截图

![20240510142616_1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/84718047/23d35ee6-3b76-43e4-874c-5aef59ada4a5)

**Comment by N071** [comment]
感谢反馈！此处错误已修正
![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/128023427/61f6a8df-3ee0-4967-a31d-ea16ad179312)
