### ISSUE TITLE
这个2+2+3的四级合成应该是错误吧，应该是2+3+3.

### ISSUE THREAD

**Issue by KbClownxxx** [LocalizeLimbusCompany/LocalizeLimbusCompany#227]
### 说说你遇到的问题？

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/56860845/62a7eb35-f88b-4c47-a0c1-a372164815b9)
如图合成四级的第一个公式

**Comment by Nephthys137** [comment]
#226
