### ISSUE TITLE
黎明事务所辛克莱3技能译名错误

### ISSUE THREAD

**Issue by haoge114** [LocalizeLimbusCompany/LocalizeLimbusCompany#228]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

辛泣疾的三技能是“愤怨烙印”，而不是“愤怒烙印”，图书馆wiki与灰机wiki写的都是“愤怨烙印”，而非“愤怒烙印”。这应该是一个bug，可能是译者在翻译的过程中把自己的习惯带进去了(byd图书馆那小字看不清都，我最开始也看成愤怒烙印了，而且愤怒烙印还挺顺口的)。

### 日志文件

无

### 截图

![Screenshot_2024-05-12-13-56-04-49_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/110206148/1d35e42b-af74-4f52-958e-fc67fa84e87a)
![Screenshot_2024-05-12-13-48-34-68_4f8db4b0b9358de58ad463a6c6b8dbdd](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/110206148/9278f3bf-f54c-414c-9bae-7a55c8050144)

### 还有别的吗？

无

**Comment by N071** [comment]
感谢您的反馈！这个问题已经在本周五(10号)进行了更正！更改后的文本在我们下次进行更新时就会应用啦
