### ISSUE TITLE
关于译名“全面战”是否可以译作“全面战法”的咨询

### ISSUE THREAD

**Issue by mucketguct** [LocalizeLimbusCompany/LocalizeLimbusCompany#229]
### 说说你遇到的问题？

非常抱歉在此打扰了，希望在“全面战”的译名上进行以下的咨询。
我个人感觉，“全面战”这一译名确实干练、直接、对于原意的表达很精准，是优秀的翻译。但不知道会不会稍微有点缺少润色，不知道是否可以考虑进行轻微的润色，例如改成“全面战法”或之类的译名。
如有打扰，在此再次致歉。另外如果关于译名的问题应当在“需求建议”栏目中提出，而非在“其他议题”栏目中提出，同样在此抱歉。

**Comment by N071** [comment]
您好，关于您提及“全面战”该译名的问题，我们想作如下反馈。确实会如您所说，三字词不是很符合中文习惯，且缺少润色，但我们经过讨论仍然决定保留，理由如下：
1. 有关韩语原文：众所周知韩文原本是汉谚混写，有许多词本身就是汉语词，这在东亚国家之间是很正常的。而原文“전면 전”对应的汉语字即为“全面 战”，而韩文“전쟁”才是对应的“战争”，这一点在日语翻译上也能体现。
2. 有关英文翻译：众所周知英文翻译不可避免地会在翻译东亚语言时出现偏差，虽然其用的是“war”来表示战争，但其实月计剧情中对于是“战争”还是“战斗”似乎比较模糊，在韩翻老师的考据之下，剧情原文就是“以全面战牵制和有规模的（大规模的）战斗”，而在中文之中对于战争一词有着规模上的要求，都市中协会的大规模行动是否能称得上战争依旧存疑。
3. 关于润色：我们曾经考虑过“战争”“战斗”“作战”等翻译，但不可避免地都会对原文造成扭曲，特别是在我们无法与月亮计划达成官方合作咨询的情况下，作冒昧的增添可能是不好的。对于您给出的“战法”，似乎我们并没有办法确定原文是动词还是名词，也许会可能造成更多不确定。
综上所述，**即便我们组内也确实很希望尽早更改**(四字情结其实还是有的嘛)，但在剧情延伸之前，我们还是愿意先保留直译。
![2085af8596b930a2b626380c6b8dab43_720](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/128023427/4fd84a89-dd09-4ece-a043-547908da1299)

祝您生活愉快

**Comment by mucketguct** [comment]
非常感谢老师的回复！这样一来我也清楚明白了该译名的由来了，老师的解释非常用心，也很易懂，在此感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月13日(星期一) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 关于译名“全面战”是否可以译作“全面战法”的咨询 (Issue #229)














 
您好，关于您提及“全面战”该译名的问题，我们想作如下反馈。确实会如您所说，三字词不是很符合中文习惯，且缺少润色，但我们经过讨论仍然决定保留，理由如下：
  
有关韩语原文：众所周知韩文原本是汉谚混写，有许多词本身就是汉语词，这在东亚国家之间是很正常的。而原文“전면 전”对应的汉语字即为“全面 战”，而韩文“전쟁”才是对应的“战争”，这一点在日语翻译上也能体现。
 
有关英文翻译：众所周知英文翻译不可避免地会在翻译东亚语言时出现偏差，虽然其用的是“war”来表示战争，但其实月计剧情中对于是“战争”还是“战斗”似乎比较模糊，在韩翻老师的考据之下，剧情原文就是“以全面战牵制和有规模的（大规模的）战斗”，而在中文之中对于战争一词有着规模上的要求，都市中协会的大规模行动是否能称得上战争依旧存疑。
 
关于润色：我们曾经考虑过“战争”“战斗”“作战”等翻译，但不可避免地都会对原文造成扭曲，特别是在我们无法与月亮计划达成官方合作咨询的情况下，作冒昧的增添可能是不好的。对于您给出的“战法”，似乎我们并没有办法确定原文是动词还是名词，也许会可能造成更多不确定。
 综上所述，即便我们组内也确实很希望尽早更改(四字情结其实还是有的嘛)，但在剧情延伸之前，我们还是愿意先保留直译。
 2085af8596b930a2b626380c6b8dab43_720.png (view on web)
  
祝您生活愉快

**Comment by ZengXiaoPi** [comment]
问题已解决，关闭议题。
（전면 전 读jeon myeon jeon）
