### ISSUE TITLE
关于镜像迷宫饰品“石版字符”的“版”是否为错别字的咨询

### ISSUE THREAD

**Issue by mucketguct** [LocalizeLimbusCompany/LocalizeLimbusCompany#230]
### 说说你遇到的问题？

您好，我注意到镜像迷宫饰品“**石版**字符”，其名称与其镜像迷宫事件中提到的“石板”，疑似存在冲突，不知道是不是错别字的问题

这是一块罗列着难解字符的**石板**。
虽然无法完全理解，
但还是有几个单词被收入眼底。
审判……定罪……惩戒……
这些相连的词语，若是试图理解，
似乎会为自己招来死亡。
从石板上移开视线，
正好看见那位记录者在飞升前，微微颔首。

![石板1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169634883/e27b7fea-c3c2-4652-8bbe-fb7e825658cf)
![石板2](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169634883/d469f6c9-d7f3-4f4f-825a-27356c071b27)
![石板3](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169634883/c7aeb290-7bf1-456c-9e9e-2a14dc69e248)

如有打扰，在此致歉。

**Comment by Nephthys137** [comment]
您好，该译名并非错别字。“石版”指的是“石版印刷”，特指饰品事件中石板上石版印刷的文字。“石板”即饰品事件中的石板，二者并没有冲突，并不是错别字。感谢您的反馈与理解。
