### ISSUE TITLE
汉化补丁突然失效了

### ISSUE THREAD

**Issue by 4378629** [LocalizeLimbusCompany/LocalizeLimbusCompany#231]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在补丁失效的前一天，我重装了系统，但在重装系统后我游玩了带有最新版本补丁的边狱巴士，一切正常，但我今天睡一觉起来之后汉化补丁就失效了！缓存全清文件全删都重下都不行，依然是失效的。BitLocker加密在重下之前解开了。

### 日志文件

没有，刚刚删完重下，一点没有

### 截图

<img width="813" alt="3e6806cd72df2942b8755ec40748765e" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/170310096/07cf0447-9130-4adf-bd78-f46aad81d944">
<img width="1080" alt="b6694daa56a764cd9c79b53f335c2dbc" src="https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/170310096/7a97aaa4-3601-4c75-b37c-808d6c151c86">

### 还有别的吗？

win10，核显

**Comment by N071** [comment]
麻烦看下，以下符合您的情况吗？
[Zeroasso.top](https://www.zeroasso.top/docs/question#%E6%A8%A1%E7%BB%84%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E4%BD%86%E6%89%93%E5%BC%80%E6%B8%B8%E6%88%8F%E6%97%A0%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%BC%B9%E5%87%BA%E4%B8%8D%E5%94%A4%E8%B5%B7bepinex)
[Issue170](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/170)
