### ISSUE TITLE
关于ego饰品”锈蚀的纪念币“的镜牢事件，“不给它水”选项获取该饰品代价有误的汉化错误

### ISSUE THREAD

**Issue by shuixigua** [LocalizeLimbusCompany/LocalizeLimbusCompany#232]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在选择“不给它水”这一选项，获得锈蚀的纪念币后，现汉化代价为：没有怠惰技能的罪人扣除15生命，但现效果为：不含怠惰技能的罪人减少12点理智

### 日志文件

[Player(游戏日志).log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/15443942/Player.log)

### 截图

截图为获取饰品（战斗后）后的理智截图
![屏幕截图 2024-05-25 223044](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/156179924/28f8e15c-cb86-4594-8e85-ae32592638f6)

**Comment by Nephthys137** [comment]
这个代价和其他相似的内容都是由游戏自动生成拼接并显示的 所以这是游戏bug而不是汉化模组的问题
