### ISSUE TITLE
精灵盛宴镇压成功界面出现口口口

### ISSUE THREAD

**Issue by movimentodiecho** [LocalizeLimbusCompany/LocalizeLimbusCompany#234]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

打完精灵盛宴在镇压成功的界面变成了“口灵盛宴，口口成功”
不知道是模组bug还是在整活

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/15776121/Player.log)

### 截图

![屏幕截图(293)](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/172295752/204ecbfb-1fcc-4ea7-b515-d7dc88559579)

**Comment by N071** [comment]
这里的缺字是因为此处文本无法应用我们的字库导致的。这是一个技术问题，当前还无法解决。总之感谢您的反馈！
