### ISSUE TITLE
关于翻译的语病

### ISSUE THREAD

**Issue by bdg197** [LocalizeLimbusCompany/LocalizeLimbusCompany#236]
### 说说你遇到的问题？

![新建位图图像](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/173176019/9ada79a8-9cc1-44e4-bf0f-e308444c4972)
“凯旋而归”应当是一个明显的语法错误
根据现代汉语词典， “凯旋”意为“胜利归来”

**Comment by bdg197** [comment]
删去“归来”即可

**Comment by N071** [comment]
感谢反馈！此处已经修改，也顺带修改了一些其他地方的相同问题。
