### ISSUE TITLE
关于镜牢四级烧伤饰品“业火残片”部分描述缺失的问题

### ISSUE THREAD

**Issue by shuixigua** [LocalizeLimbusCompany/LocalizeLimbusCompany#237]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

该饰品缺少了类似“使用增加烧伤层数或强度的ego”的前置条件（相比于其他残片，缺少了第一段描述）
下方为对比

### 日志文件

无

### 截图

![屏幕截图 2024-06-20 202904](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/156179924/2edbdcc9-fc93-419e-b72e-ba758cf33a7b)
![屏幕截图 2024-06-20 204438](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/156179924/93f68d9b-2981-43fa-a5e8-90f565cf370e)

**Comment by mucketguct** [comment]
您好，是这样的，经过查证，该问题为月亮计划方面的问题，这一处是原文的描述错误，韩语、英语、日语这三语原文全部在此处缺失了相应的文本。由于我们的汉化不负责帮助纠正原文的描述错误与描述缺失——这是我们之前定下来的翻译方针，非常感谢您的理解——因此我们暂不予以改动，等待月计改动原文之后再进行修改。感谢捉虫~

如果您希望反馈这一原文描述问题的话，也可以通过月亮计划的邮件，向月亮计划进行反馈：[limbussupport@projmoon.com](mailto:limbussupport@projmoon.com)

感谢反馈。

“业火残片”的描述原文链接（如下图一）：https://paratranz.cn/projects/6860/strings?file=889023&anchor=431394823

“魅惑残片”的描述原文链接（如下图二、三）：https://paratranz.cn/projects/6860/strings?file=889023&anchor=431394856

![1](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169634883/4cbba8f8-6311-405b-bea7-71de441c0107)

![2](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169634883/89039e30-bddd-4c09-b473-6911e054b6c8)

![3](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/169634883/8a264e22-bf86-4618-9d54-2cbf09ba2cb3)
