### ISSUE TITLE
锁链选中

### ISSUE THREAD

**Issue by Saicius** [LocalizeLimbusCompany/LocalizeLimbusCompany#238]
### 说说你遇到的问题？

与游戏原本的锁链选中样式与颜色不太一致，希望可以修一下
![1(9V}B 6W9}RV111UBUNOU4](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/163785810/dfd2d84e-0f2b-4470-9481-a8d22f441025)
![7Y61RRFX6BD7%1FDFUPZY Q](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/163785810/795c400b-a164-4f61-8982-056c98924f51)
感谢汉化

**Comment by N071** [comment]
汉化模组不会影响游戏本身的图片素材，因此我们既不会修改，也无法修复此类问题。
另外您的第二张截图是什么时候的？看起来似乎像是早期版本的演示视频。

**Comment by ZengXiaoPi** [comment]
问题应当为月亮计划修改了样式，此问题与汉化模组无关，因为这本身是月亮计划做出的更改。

**Comment by Saicius** [comment]
的确是Steam演示视频中看到的，误以为是汉化时的Bug，(感谢解答
