### ISSUE TITLE
技能翻译问题 李箱 环指

### ISSUE THREAD

**Issue by AugMentElia** [LocalizeLimbusCompany/LocalizeLimbusCompany#239]
### 说说你遇到的问题？

二技能III翻译中没有“（至多重复使用x次）”
IV中正常
![Image_1719799442783](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/174288420/16ba8ec0-b9a5-42c0-ae1e-b21264611efd)
![Image_1719799440647](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/174288420/a294cf35-94ed-4fae-9f61-98808feb7274)

**Comment by ZengXiaoPi** [comment]
因为三破之后环指箱只会重复一次。
