### ISSUE TITLE
游戏闪退

### ISSUE THREAD

**Issue by ImYiFeng** [LocalizeLimbusCompany/LocalizeLimbusCompany#240]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

游戏在ProjectMoon的Logo动画播放完后闪退，使用工具箱关闭模组后游戏可以正常启动

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/16048140/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/16048142/Player.log)

**Comment by ZengXiaoPi** [comment]
没有可用信息。
