### ISSUE TITLE
山茶花EGO的绽放改为冬柏是否有些不妥？

### ISSUE THREAD

**Issue by haoge114** [LocalizeLimbusCompany/LocalizeLimbusCompany#241]
### 说说你遇到的问题？

打游戏的时候看到绽放改成冬柏就感觉怪怪的，而且绽放的韩文原文也是没有更改，前几次更新后就莫名其妙的就变了。译文ParaTranz项目也没有找到关于绽放相关的话题，不是很明白为什么要把冬柏搞特殊，这是怕新玩家误会吗？

**Comment by ZengXiaoPi** [comment]
（来源于Enemies.json）
```
EN : Dongbaek E.G.O::Spicebush
JP : ドンベクE.G.O::壇香梅
KR：동백 E.G.O::동백
```
此处一直没有更改，Dongbaek，동백皆为东柏。
