### ISSUE TITLE
四号线翻译导致的奇怪排版

### ISSUE THREAD

**Issue by Jelly-Candy** [LocalizeLimbusCompany/LocalizeLimbusCompany#242]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

标题仍有残留韩语未删除干净，但似乎已经被翻译了，section XXX排版出现了错位问题

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/16114695/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/16114696/Latest.log)

### 截图

![image](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/103652041/a51a03a4-7755-44ae-995b-fabb74a7e2a0)

**Comment by ZengXiaoPi** [comment]
标题的韩语：代码写死
Section 0X错位：由于此处月计使用了特殊字体，汉化补丁只能应用原版字体，导致错位
两者的共同点是无法修复

**Comment by Jelly-Candy** [comment]
好家伙，月计都写了啥答辩代码
