### ISSUE TITLE
换了beta版工具箱不能使用

### ISSUE THREAD

**Issue by IPME111** [LocalizeLimbusCompany/LocalizeLimbusCompany#243]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

之前可行，换beta版后无法使用

### 日志文件

[Log-20240711.log](https://github.com/user-attachments/files/16179662/Log-20240711.log)

### 截图

![QQ图片20240711231101](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/175331191/3932f80a-b901-43ea-888b-6eef74a4347b)
![QQ图片20240711231055](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/assets/175331191/df6f3789-3dff-4d02-85b6-497a6d3c71c2)

**Comment by IPME111** [comment]
提交错误

**Comment by HollowSAMA** [comment]
同样的问题，想问问目前有解决方案吗

**Comment by IPME111** [comment]
没，今天下了0.644也是这样，估计得等更新正式了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 23:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 换了beta版工具箱不能使用 (Issue #243) |

同样的问题，想问问目前有解决方案吗

**Comment by IPME111** [comment]
急得话可以去看看手动安装，我这边是怕手动和自动出现啥问题，就加上也不影响，就没管



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 23:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 换了beta版工具箱不能使用 (Issue #243) |

同样的问题，想问问目前有解决方案吗

**Comment by IPME111** [comment]
亲测，手动安装可以解决问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 23:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 换了beta版工具箱不能使用 (Issue #243) |

同样的问题，想问问目前有解决方案吗
