### ISSUE TITLE
Beta版本工具箱无法正确找到游戏安装路径

### ISSUE THREAD

**Issue by HollowSAMA** [LocalizeLimbusCompany/LocalizeLimbusCompany#244]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

使用Beta版本工具箱后工具箱无法正确找到游戏路径，点击一键安装即报错退出。

### 日志文件

[Uploading Log-20240724.log…]()

### 截图

![图片](https://github.com/user-attachments/assets/a2e6f8bd-ae22-4af9-9f01-6ae8438e925e)
![图片](https://github.com/user-attachments/assets/e9c2ee2b-fd23-4016-a333-bf276cb98943)

**Comment by ZengXiaoPi** [comment]
下个版本修复。
