### ISSUE TITLE
希斯克利夫凶弹EGO暴击击杀显示为Unknown

### ISSUE THREAD

**Issue by qwsdea** [LocalizeLimbusCompany/LocalizeLimbusCompany#245]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

希斯克利夫凶弹EGO四破时第二硬币暴击击杀显示为Unknown
1~3破显示正常

### 日志文件

对不起这个我填不了

### 截图

![e7dc1969901aec930b37b5faa10aa96](https://github.com/user-attachments/assets/2f268db3-a8f2-4b3d-9041-bb9a1e9ac422)

**Comment by ZengXiaoPi** [comment]
下个版本修复。
