### ISSUE TITLE
Windows 8.1 似乎不能用汉化补丁？

### ISSUE THREAD

**Issue by Sinc-OIer** [LocalizeLimbusCompany/LocalizeLimbusCompany#246]
### 在提问之前…

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决；
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等；
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况；
- [x] 我使用的汉化补丁版本已为最新版。

### 问题描述

~~应该是第一个这么做的人了？~~  
在我的电脑（**Windows 8.1 专业版，64 位操作系统**）中，打开游戏时，并不能唤起 BepInEx，导致汉化补丁无法运行。  
可以保证汉化补丁正常、完整且为最新版本。

由于工具箱不支持 Windows 8.1，于是直接弄了手动安装，通过 OneDrive For Business 渠道下载。  
（我确确实实看到了那句”**汉化模组本体不支持 Windows 7，在 Windows 8 上未被验证**“，所以~~本着求真务实的精神~~去试了一下，勿喷）  
对照了一下零协会官网>排除网络问题的综合指引，根目录没有问题。

然而在打开游戏后并没有控制台的显现，使用兼容模式与管理员模式也无效，多次重启也无效。  
没有**游戏目录日志文件**，运行游戏时也**没有汉化脚本**出现。  
同时，**BepInEx 文件夹内只有 core，patchers，plugins 和 unity-lib 文件夹**。  

### 日志文件

安装汉化后，游戏根目录没有游戏日志文件和框架日志文件。

### 截图

手动安装汉化后的游戏路径及根目录：
![捕获](https://github.com/user-attachments/assets/975ff923-98bb-4a8f-92c0-3ae8f1412ff6)

### 更多信息

电脑：Windows 8.1 专业版，64 位操作系统，核显。

**Comment by ZengXiaoPi** [comment]
并非系统问题。
请查看[此页面](https://zeroasso.top/docs/question#%E6%A8%A1%E7%BB%84%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E4%BD%86%E6%89%93%E5%BC%80%E6%B8%B8%E6%88%8F%E6%97%A0%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%BC%B9%E5%87%BA%E4%B8%8D%E5%94%A4%E8%B5%B7bepinex)寻求解决方案。
