### ISSUE TITLE
部分主线剧情cg和人物语音丢失

### ISSUE THREAD

**Issue by Dr777191** [LocalizeLimbusCompany/LocalizeLimbusCompany#248]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

推主线第五章时，在boss战演出动画结束后，出现剧情cg变成黑屏，且人物没有语音，只有文本框的问题。之前主线中正常显示的cg在这之后也变成了这样。把汉化模组删除过后恢复正常，因此感觉是汉化模组的问题，重新下载没有解决问题。

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/16456415/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/16456416/Player.log)

### 截图

![1973530_10](https://github.com/user-attachments/assets/c6823a78-290d-4188-a9ab-c0c09235ad2a)
![1973530_10](https://github.com/user-attachments/assets/3f444fb1-e095-4189-8b9e-d487ad41fe8b)

5-35剧情的截图，原有cg变成黑屏，只有文本框，没有人物语音

### 还有别的吗？

无

**Comment by Nephthys137** [comment]
下版本修复
