### ISSUE TITLE
使用mod后图片无法加载

### ISSUE THREAD

**Issue by nobeoder** [LocalizeLimbusCompany/LocalizeLimbusCompany#249]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在时间杀人时间中，使用汉化补丁会导致这章节剧情里面的图片无法加载

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/16512943/Latest.log)

### 截图

![20240807001043_1](https://github.com/user-attachments/assets/7efc12eb-9e2b-445f-a574-2cb3c094f474)
![20240807001028_1](https://github.com/user-attachments/assets/0ce2600a-934e-49a7-afb1-cd7c7a940ae1)

**Comment by ZengXiaoPi** [comment]
你在点击`我使用的汉化补丁版本已为最新版`前是否已经确认过？

**Comment by nobeoder** [comment]
我的，8月2号的时候更新了一次，没想到最近MOD更新了，现在已经没有问题了
