### ISSUE TITLE
6.5-29浮士德台词文本中关于“格塞塔”的翻译问题

### ISSUE THREAD

**Issue by sutorie** [LocalizeLimbusCompany/LocalizeLimbusCompany#250]
### 说说你遇到的问题？

对于浮士德的台词：**_既然连接成功了，那么我想立刻就遗漏了进入WARP就会断联的重要情报这一点，对格塞塔的管理员提出抗议。_**
![“格塞塔”翻译问题](https://github.com/user-attachments/assets/0270914e-e61f-41ef-93e2-79063d0ec6b8)
wiki文本显示此处零协将“ゲゼルシャフト/Gesellschaft”译为格塞塔，个人认为有所欠缺，原因如下
1.在德语中gesellschaft拥有社会、公司和伙伴关系等具体含义，可以直译而非音译
2.使用“格塞塔”作为译名容易引起【格塞塔是浮士德所属的组织名】这类误会

希望更改翻译

**Comment by N071** [comment]
老师也看得出来，起初我们使用格塞塔是为了对应韩/日对这个德语单词的音译。虽然感觉有点牵强（毕竟这种理解错误的误会真的怎么都能说通），但我们不完全否认会出现“格塞塔是浮士德所属的组织名”这种误会（所以在后续进行了更改，见后文）。
另外对其进行直译似乎很别扭，Gesellschaft在这里是一个_专有名词_，这意味着其在直译出来的_社会、公司和伙伴关系_的基础含义之上，在边狱公司语境中，以及对于浮士德来说都有特殊意义。因此我们也就不太倾向于使用直译了。直译之后，对现实概念的指向性太过明确，似乎盖过了Gesellschaft在边狱公司当中的特殊意义。

以上这些解释应该也能构成对您的两条建议的回应：
> 1.在德语中gesellschaft拥有社会、公司和伙伴关系等具体含义，可以直译而非音译
> 2.使用“格塞塔”作为译名容易引起【格塞塔是浮士德所属的组织名】这类误会
---
以上这些，是我对我们思考历程的阐述。
最终，我们认为我们将会在保留“Gesellschaft”原文，以及使用音译“格塞塔”当中进行抉择。
就在老师发出这个Issue不久前，我们已将全部格塞塔改为Gesellschaft，更换为保留原文的思路。我们还是觉得“格塞塔”这个音译不够广为人知，容易造成各种各样的误会。
---
如果把话题扯得稍微远一点的话，如果这里不是“Gesellschaft”，而是互联网上大名鼎鼎的“Gestalt”的话，那我们估计会不假思索地采用音译译名“格式塔”，而不是采用原文“Gestalt”。
“格式塔”这三个字因为大量的使用和科普，早就变成了一个通用的、抽象的、专用的符号。和“格式塔”相比，就很容易感受到“格塞塔”这个音译译名显然不够广泛、不够通用、也不够符号化。

所以最后还是打算用原文“Gesellschaft”。
---
感谢您能联系我们！
关于我们目前使用原文的方法，还有什么要提出的疑问或者建议吗？

**Comment by Nephthys137** [comment]
此外wiki上不会频繁的同步更改，[ParaTranz](https://paratranz.cn/projects/6860)上才是可信内容

**Comment by mucketguct** [comment]
非常感谢老师的反馈，另外，边狱公司中文wiki的更新由于更新限制，相对没有那么实时，实时的翻译内容，还请参照我们的paratranz翻译平台上的实时内容：

https://paratranz.cn/projects/6860

总之感谢反馈，祝您在本次间章中玩得开心

**Comment by N071** [comment]
他们说的对。Wiki那边很不容易，是从我们的Paratranz上获取的文本。或许是为了大家能早点看到文本，他们会在我们的翻译施工的同时，也进行Wiki的施工。由于我们的翻译是在不断接受校对和改进的，所以是会出现这样修改滞后的情况。
当前的翻译情况，请参考 https://paratranz.cn/projects/6860

**Comment by sutorie** [comment]
感谢回复，解释得很清晰！在后续剧情解释之前保留原文确实是比较好的做法，零协的大家辛苦了。
昨天看到零协在b站的动态才发现这不是已发布的版本XD，wiki的建设者们也辛苦了，边狱巴士灰机wiki是我见过最实用且美观的wiki之一，感谢大家的付出。
