### ISSUE TITLE
汉化模组下载失败，无法返回服务器429等多项错误。

### ISSUE THREAD

**Issue by Marsky2020** [LocalizeLimbusCompany/LocalizeLimbusCompany#251]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在5月份正常下载使用与更新汉化模组，但今天（8月10日）开始几次使用汉化模组内的自动更新功能连续报错，并且在模组卸载后重装依旧报错，无法下载汉化内容。
已附上报错截图和日志。

### 日志文件

[Log-20240810.log](https://github.com/user-attachments/files/16568770/Log-20240810.log)
[Log-20240810.log20240810.log](https://github.com/user-attachments/files/16568771/Log-20240810.log20240810.log)

### 截图

![屏幕截图 2024-08-10 144829](https://github.com/user-attachments/assets/0f888d98-d350-47ad-bfe4-eb53202aac62)
![屏幕截图 2024-08-10 143727](https://github.com/user-attachments/assets/a2b14a82-3d17-412b-8837-e93a6d96845a)
![屏幕截图 2024-08-10 143635](https://github.com/user-attachments/assets/b644fb09-8b36-417c-91dc-54e3e0d47ef2)

**Comment by ZengXiaoPi** [comment]
暂时不明白为什么会出现这种情况……
