### ISSUE TITLE
游戏白屏后弹窗报错闪退，多次自动安装与手动安装都无法解决

### ISSUE THREAD

**Issue by madnesjeb** [LocalizeLimbusCompany/LocalizeLimbusCompany#254]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

自动安装与手动安装多次都存在下图问题，出现游戏弹窗后游戏白屏，跳出图4，按确定后出现图5，按图5后游戏闪退。

### 日志文件

[24-8-17_11-13-44.log](https://github.com/user-attachments/files/16643342/24-8-17_11-13-44.log)

### 截图

![QQ截图20240816172816](https://github.com/user-attachments/assets/53aa073a-d016-482b-927d-b563428cf71d)
![QQ截图20240816173017](https://github.com/user-attachments/assets/1ea9a87e-7f5d-4deb-918b-7e44ae5823b5)
![QQ截图20240816173038](https://github.com/user-attachments/assets/91de8711-1ecf-4d09-a49e-4c97ceb535ea)
![UBL$ )@BF%WNK9YUB34EURL](https://github.com/user-attachments/assets/757e4158-9937-4b65-b136-867e7eae3e82)
![QQ图片20240817120450](https://github.com/user-attachments/assets/94875dd8-0d54-41a2-8357-b21b6eec8106)

**Comment by ZengXiaoPi** [comment]
网络问题。
