### ISSUE TITLE
关于事件-E式次元短剑的选项三的翻译问题

### ISSUE THREAD

**Issue by YanZengrui** [LocalizeLimbusCompany/LocalizeLimbusCompany#255]
### 说说你遇到的问题？

<img width="1920" alt="微信图片_20240818103532" src="https://github.com/user-attachments/assets/ff746cf5-743e-40be-97f2-fc9c82f04bcc">
<img width="1920" alt="微信图片_20240818103601" src="https://github.com/user-attachments/assets/222eaa15-3a15-4fc1-b6ab-36646405fb54">
<img width="1920" alt="微信图片_20240818104101" src="https://github.com/user-attachments/assets/c372e794-c9bb-4be3-9b92-23ab80eca15c">
如图，该事件的选项三为获得2件充能E.G.O饰品，但汉化显示为1件

**Comment by mucketguct** [comment]
您好，这里是一个三语原文的描述偏差：

英语原文（EN）：Win to gain a Charge E.G.O Gift.
日语原文（JP）：勝利時に充電E.G.O GIFT獲得
韩语原文（KR）：승리 시 충전 E.G.O GIFT 획득

该条目的链接：https://paratranz.cn/projects/6860/strings?id=494344690

此处的三语原文全部笔误，使用了获得1件饰品时的行文（而不是获得2件饰品时的“Win the battle to earn 2 E.G.O Gifts/戦闘勝利時、E.G.O GIFTを2種獲得/전투 승리 시,  E.G.O GIFT 2종 획득”），三语原文都在这里发生了笔误；

我们的翻译方针是不会帮助月亮计划纠正原文的笔误，详情请参照公告“技能描述与实际效果有差异 的处理策略”：

该公告的链接：https://www.zeroasso.top/docs/translate/namearchive

此处的文本较为特殊：从镜像迷宫4开始，在一个镜像迷宫事件中，玩家可以通过不同选择，获得不同数量的饰品（一般是1件或2件），韩语原文与日语原文在这里并没有明确饰品的具体数量，而英语原文在这里明确了饰品的具体数量，汉化中也同样明确了饰品的具体数量，以区分获得1件与2件饰品的选项；

而该条目也是英语原文明确地在饰品数量上发生了笔误，而韩语原文与日语原文尽管是获得1件饰品时的行为，但并没有在原文中明确饰品的数量，这一原文的笔误冲突在过去也曾发生过，该先例解决方案是同步韩语原文与日语原文，同样不明确饰品的数量，即完全按照原文的“胜利后，获得E.G.O饰品。”，对于目前这一争议，现在也同步了这一方案，这一事件选项的描述，目前暂时改为“胜利后，获得充能E.G.O饰品。”，也与日语原文和韩语原文的含义同步。

感谢您的反馈，祝玩得开心
