### ISSUE TITLE
加入了汉化补丁之后游戏错误，进不去了

### ISSUE THREAD

**Issue by AnllinG16** [LocalizeLimbusCompany/LocalizeLimbusCompany#256]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

如题，无论是手动安装还是自动安装都是一样的问题和错误代码
![1JK`1IZQ5NC)%5Q`O6)BXU3](https://github.com/user-attachments/assets/e445790c-4cd8-41cc-aa4b-584a046c2a5d)

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/16663006/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/16663007/Latest.log)

### 截图

![1JK`1IZQ5NC)%5Q`O6)BXU3](https://github.com/user-attachments/assets/da940702-15bb-4c33-b869-d164061655d8)

**Comment by Nephthys137** [comment]
MelonLoader已不再支持
```
[23:39:44.022] ------------------------------
[23:39:44.081] MelonLoader v0.6.3 Open-LLCBeta
[23:39:44.082] OS: Windows 11
[23:39:44.082] Hash Code: E088D1E8B2711946EDCB7EA10A5E0D362838D3AD983D0ACE2784443CC19D2B
[23:39:44.082] ------------------------------
[23:39:44.083] Game Type: Il2cpp
[23:39:44.083] Game Arch: x64
[23:39:44.083] ------------------------------
[23:39:44.083] Core::BasePath = E:\SteamLibrary\steamapps\common\Limbus Company
[23:39:44.083] Game::BasePath = E:\SteamLibrary\steamapps\common\Limbus Company
[23:39:44.083] Game::DataPath = E:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany_Data
[23:39:44.083] Game::ApplicationPath = E:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany.exe
[23:39:44.084] Runtime Type: net6
[23:39:44.355] ------------------------------
[23:39:44.356] Game Name: LimbusCompany
[23:39:44.356] Game Developer: ProjectMoon
[23:39:44.359] Unity Version: 2021.3.28f1
[23:39:44.359] Game Version: 0.1
[23:39:44.359] ------------------------------
```

**Comment by AnllinG16** [comment]
> MelonLoader已不再支持
> 
> ```
> [23:39:44.022] ------------------------------
> [23:39:44.081] MelonLoader v0.6.3 Open-LLCBeta
> [23:39:44.082] OS: Windows 11
> [23:39:44.082] Hash Code: E088D1E8B2711946EDCB7EA10A5E0D362838D3AD983D0ACE2784443CC19D2B
> [23:39:44.082] ------------------------------
> [23:39:44.083] Game Type: Il2cpp
> [23:39:44.083] Game Arch: x64
> [23:39:44.083] ------------------------------
> [23:39:44.083] Core::BasePath = E:\SteamLibrary\steamapps\common\Limbus Company
> [23:39:44.083] Game::BasePath = E:\SteamLibrary\steamapps\common\Limbus Company
> [23:39:44.083] Game::DataPath = E:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany_Data
> [23:39:44.083] Game::ApplicationPath = E:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany.exe
> [23:39:44.084] Runtime Type: net6
> [23:39:44.355] ------------------------------
> [23:39:44.356] Game Name: LimbusCompany
> [23:39:44.356] Game Developer: ProjectMoon
> [23:39:44.359] Unity Version: 2021.3.28f1
> [23:39:44.359] Game Version: 0.1
> [23:39:44.359] ------------------------------
> ```

怎么解决啊，从工具箱那里删了模组重下也不行

**Comment by AnllinG16** [comment]
> > MelonLoader已不再支持
> > ```
> > [23:39:44.022] ------------------------------
> > [23:39:44.081] MelonLoader v0.6.3 Open-LLCBeta
> > [23:39:44.082] OS: Windows 11
> > [23:39:44.082] Hash Code: E088D1E8B2711946EDCB7EA10A5E0D362838D3AD983D0ACE2784443CC19D2B
> > [23:39:44.082] ------------------------------
> > [23:39:44.083] Game Type: Il2cpp
> > [23:39:44.083] Game Arch: x64
> > [23:39:44.083] ------------------------------
> > [23:39:44.083] Core::BasePath = E:\SteamLibrary\steamapps\common\Limbus Company
> > [23:39:44.083] Game::BasePath = E:\SteamLibrary\steamapps\common\Limbus Company
> > [23:39:44.083] Game::DataPath = E:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany_Data
> > [23:39:44.083] Game::ApplicationPath = E:\SteamLibrary\steamapps\common\Limbus Company\LimbusCompany.exe
> > [23:39:44.084] Runtime Type: net6
> > [23:39:44.355] ------------------------------
> > [23:39:44.356] Game Name: LimbusCompany
> > [23:39:44.356] Game Developer: ProjectMoon
> > [23:39:44.359] Unity Version: 2021.3.28f1
> > [23:39:44.359] Game Version: 0.1
> > [23:39:44.359] ------------------------------
> > ```
> 
> 怎么解决啊，从工具箱那里删了模组重下也不行

删了之后可以正常进入，但是一下mod就进不去
