### ISSUE TITLE
语言文本、语音消失

### ISSUE THREAD

**Issue by qingjiansang** [LocalizeLimbusCompany/LocalizeLimbusCompany#257]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

巴士电视语言文本、战斗结束语言文本、语音消失

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/16708468/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/16708471/Player.log)

### 截图

![9cf88fa25415cc9f9df036fce3c4c73c](https://github.com/user-attachments/assets/95696402-2817-4ba6-b824-464394ba7a55)
![2117f70430656a22d574ddca4dd5e827](https://github.com/user-attachments/assets/b302cb37-dee8-4199-94a1-b7d996e37054)

**Comment by ZengXiaoPi** [comment]
https://b23.tv/JeU7XxU
