### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by suMgAl613** [LocalizeLimbusCompany/LocalizeLimbusCompany#258]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

1.应用程序发生异常
2.能唤起BepInex，但是进不了游戏
3.在没有汉化模组的情况下可以打开游戏

### 日志文件

[Uploading Player(游戏日志).log…]()
[Uploading Latest(框架日志).log…]()
Mod Has Unknown Fatal Error!!!
模组部分功能出现致命错误,即将打开GitHub,请根据Issues流程反馈
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)

HarmonyLib.HarmonyException: Patching exception in method null
 ---> System.ArgumentException: Undefined target method for patch method static bool LimbusLocalize.LCB_Chinese_Font::GetTellerName(Il2CppStorySystem.StoryData __instance, string name, Il2Cpp.LOCALIZE_LANGUAGE lang, String& __result)
   at HarmonyLib.PatchClassProcessor.PatchWithAttributes(MethodBase& lastOriginal)
   at HarmonyLib.PatchClassProcessor.Patch()
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.PatchAll(Type type)
   at LimbusLocalize.LCB_LLCMod.OnInitializeMelon()
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)

**Comment by Nephthys137** [comment]
没有正确上传日志,根据你填写的内容 请尝试使用最新版模组
