### ISSUE TITLE
格里高尔初始E.G.O译名

### ISSUE THREAD

**Issue by Zena-M** [LocalizeLimbusCompany/LocalizeLimbusCompany#259]
### 说说你遇到的问题？

格里高尔的初始E.G.O被译为“那一日，突然”,韩文则是“어느날 갑자기”，翻译为“某一日，突然”应该更加精准；因为韩文中对应“那一日”的是“그날”，而对应“某一日”的是“어느날”；一字之差，给人感觉还是很不一样的。

**Comment by N071** [comment]
非常感谢反馈。
我们确认了您的建议，在之后将把 *那一日* 修改为 *某一日*。这个修改会在下一次我们更新模组时实装。

*那一日，突然* 的翻译本身定名较早，且由于文本众多，我们难免会出现此类纰漏。因此，我们非常需要依靠持续接纳社区的建议和意见，来逐渐完善我们的翻译。
再次感谢您帮助我们继续完善翻译。

**Comment by Zena-M** [comment]
那就先感谢零协的各位翻译了！
