### ISSUE TITLE
第四章迷宫最终战，配音与文本错位

### ISSUE THREAD

**Issue by UselessSponge** [LocalizeLimbusCompany/LocalizeLimbusCompany#261]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

![图片](https://github.com/user-attachments/assets/12c81dc9-9e44-4e81-a3d5-d2c3218acf41)
这句话没有正确与语音配对，导致后续文本全部错位

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/16731828/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/16731830/Latest.log)

**Comment by Nephthys137** [comment]
我们将在下个版本尝试定位问题并修复
