### ISSUE TITLE
运行汉化包时遇到问题

### ISSUE THREAD

**Issue by Shen2g** [LocalizeLimbusCompany/LocalizeLimbusCompany#262]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

您好！这边下载完安装包在点击运行时遇到了截图所示的问题，是初次下载安装，不知道该怎么解决！

### 日志文件

不知道是属于什么问题麻烦您看一下...

### 截图

![5f46e9a61806266ed7c28536cde296b2](https://github.com/user-attachments/assets/f856480c-dee3-4f2f-9115-164be382da5d)
![4a7ed18cdaec2d04bd2388f0f1a887c2](https://github.com/user-attachments/assets/917178f2-ca22-46d9-aa2b-cd04cc1c9daf)

**Comment by ZengXiaoPi** [comment]
网络问题，建议在使用能够加速Github的工具后使用Github直连。

**Comment by Shen2g** [comment]
谢谢！！

**Comment by Shen2g** [comment]
![e73093b11c6ba9ec956970bcb11af799](https://github.com/user-attachments/assets/093312df-3f11-4667-930f-d9441fe92f23)
您好 使用watt toolkit加速之后还是显示这个...
