### ISSUE TITLE
汉化无法正常运行

### ISSUE THREAD

**Issue by asdwadwaD-svg** [LocalizeLimbusCompany/LocalizeLimbusCompany#264]
### 说说你遇到的问题？

日志文件
[Message: Preloader] BepInEx 6.0.1-dev - LimbusCompany
[Message: Preloader] Built from commit 5be339d872201644aa4e408adbccdeb68cccfe7d
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.28f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [LimbusLocalizeMod 0.6.49]
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type LimbusLocalize.LLC_Manager in il2cpp domain
[Message:   BepInEx] Chainloader startup complete

**Comment by Nephthys137** [comment]
没有正确的日志，无法解决你的问题
