### ISSUE TITLE
汉化工具箱抽卡功能相关问题

### ISSUE THREAD

**Issue by ParseeVVVIP** [LocalizeLimbusCompany/LocalizeLimbusCompany#265]
### 说说你遇到的问题？

1.使用零协工具箱中的“抽卡模拟器”进行抽卡是，结果中出现空行。
![image](https://github.com/user-attachments/assets/061db203-6c69-441c-9f65-c7f5b7a5d06d)
![image](https://github.com/user-attachments/assets/5f9adb23-9e94-4e3a-845d-326d43cbfa3b)
2.尝试抽卡时可能出现报错
![image](https://github.com/user-attachments/assets/c810468c-6198-462b-99da-7a4807e5d7bc)

**Comment by ZengXiaoPi** [comment]
之后版本将尝试修复。（不过有点难修）
