### ISSUE TITLE
运行游戏几秒钟后就闪退

### ISSUE THREAD

**Issue by QQQQQMY** [LocalizeLimbusCompany/LocalizeLimbusCompany#266]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

运行几秒后白屏状态就会闪退。自动安装出错后用了手动安装有了这个情况。用过了常见问题的手动操作重新安装依然不行。开关加速器/更换网络/重启电脑也使用过也会闪退

### 日志文件

[框架日志.log](https://github.com/user-attachments/files/17017626/default.log)
[游戏日志.log](https://github.com/user-attachments/files/17017627/default.log)
[Latest.log](https://github.com/user-attachments/files/17017630/Latest.log)

### 还有别的吗？

版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2021/‎3/‎23
操作系统内部版本	19045.4894
体验	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by QQQQQMY** [comment]
winhttp.dll, doorstop_config.ini, BepInEx, dotnet四个文件删除后游戏可以正常运行

**Comment by Nephthys137** [comment]
然而,你上传的日志表示你使用的是MelonLoader,他现在已经不支持了;所以无法解决你的问题

**Comment by QQQQQMY** [comment]
“然而”之前没有了吗😭😭😭所以只能换台电脑再玩了吗😭😭😭
