### ISSUE TITLE
剑契组 李箱 语音翻译问题

### ISSUE THREAD

**Issue by antiuts** [LocalizeLimbusCompany/LocalizeLimbusCompany#267]
### 说说你遇到的问题？

剑契组李箱的晚间问候英译为“I do not enjoy the moonlight”，应该是不喜欢月光吧？翻译确实“我深爱月光
![Image_1726507378665](https://github.com/user-attachments/assets/a6e56a37-ed0c-4ffb-8252-76b2103cc720)
”
![{@87J@QTF P0A3KN@FZ CRB](https://github.com/user-attachments/assets/73589339-44d3-4ec2-bdea-5af4d3d5cf68)

**Comment by mucketguct** [comment]
非常感谢您的反馈！这里确实意思反啦，现已修正啦，该修复会在下次模组更新中同步，感谢反馈，祝玩得开心啦
