### ISSUE TITLE
镜牢更换技能游戏卡死闪退

### ISSUE THREAD

**Issue by wannianlaoxianyu** [LocalizeLimbusCompany/LocalizeLimbusCompany#268]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在服务器维修之前正在打镜牢，维护时战斗已经结束了。维修结束后，进入第四次层的开局商店后更换技能时游戏卡死闪退

### 日志文件

[Player(游戏日志) - 副本.log](https://github.com/user-attachments/files/17053185/Player.-.log)

### 截图

https://github.com/user-attachments/assets/f05077bd-9eb1-46a3-8423-a7c7cdbf64f1

**Comment by N071** [comment]
此问题是游戏本身问题，参见月亮计划今日公告。
