### ISSUE TITLE
发现 以实玛利 新 EGO 往昔 存在一处笔误

### ISSUE THREAD

**Issue by leemars** [LocalizeLimbusCompany/LocalizeLimbusCompany#270]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/commit/4853b313924901f97d7d36d22a7dd8e396d3c87f#diff-894669332363fa48583aefee8a80a1eb0ee5aa7fbc0d232e39fbd32741911694R371

这里多余的 `ck]` 应该是笔误

### 日志文件

无

### 截图

![image](https://github.com/user-attachments/assets/96c59cd2-b3dc-483c-8c15-e52275774e5a)

**Comment by mucketguct** [comment]
您好，非常感谢反馈，此处笔误现已完成修改啦，会在下一次模组更新中同步此修复，祝玩得开心啦
