### ISSUE TITLE
切换语言之后在加载中闪退

### ISSUE THREAD

**Issue by ldldbak** [LocalizeLimbusCompany/LocalizeLimbusCompany#271]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在游戏里面切换成日文之后，在安装模组的情况下再进入游戏时在登入界面之前会闪退，只能卸掉之后重新安装。

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/17172057/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/17172058/Player.log)

### 截图

![捕获1](https://github.com/user-attachments/assets/efa82152-ae61-4777-b05e-f797b3bdea40)

**Comment by ZengXiaoPi** [comment]
老问题了，建议用工具箱的关闭模组功能
