### ISSUE TITLE
请问一下现在是没有从所有已到达进度中随机选择载入CG这个功能了吗？

### ISSUE THREAD

**Issue by ThereisJulinas** [LocalizeLimbusCompany/LocalizeLimbusCompany#274]
### 说说你遇到的问题？

如题，我在打开Com.Bright.LocalizeLimbusCompany.cfg这个文件后发现没有RandomAllLoadCG = true这一行，现在是删除了这个功能吗？

**Comment by ZengXiaoPi** [comment]
月计修改了载入CG相关代码，且新代码难以修改。
