### ISSUE TITLE
安装完后还是因为，汉化不起作用，但设置里面也有中文选项。

### ISSUE THREAD

**Issue by xuhuiqi-123** [LocalizeLimbusCompany/LocalizeLimbusCompany#275]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我使用的汉化补丁版本已为最新版

### 问题描述

我目前不知道自己是否使用的事最新版汉化补丁，如果又最新的汉化补丁请告诉我，谢谢

### 日志文件

无

### 截图

![微信图片_20241002115410](https://github.com/user-attachments/assets/9e341f23-e471-421c-aa85-35b0a726b313)

1. 
![微信图片_20241002115410](https://github.com/user-attachments/assets/cc5499a6-e761-4686-a4cc-611bd25a5393)

### 还有别的吗？

无

**Comment by ZengXiaoPi** [comment]
新版本已修复，请等待更新。
