### ISSUE TITLE
主页没有汉化但是加载界面有

### ISSUE THREAD

**Issue by meimo26** [LocalizeLimbusCompany/LocalizeLimbusCompany#277]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

打扰了（我不知道我是不是发错了，并没有用过Github）
我下了新汉化之后不知道为什么主页就没有汉化了，但是开屏和加载界面有汉化，我不懂电脑看不出来是什么问题

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/17219771/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/17219772/Player.log)

### 截图

![d46194e431ad180c7db55c9b32429375](https://github.com/user-attachments/assets/45cb0cbb-5c13-4df9-b828-2882e58d2ffb)
![99ba70df6f16656c9728140a004cef51](https://github.com/user-attachments/assets/2eda8916-33f3-4967-92a2-60b244b0082c)
![c2c6f57c3d841d136a564fd8caf8c864](https://github.com/user-attachments/assets/2e88d106-609a-45d2-b1fa-7ebc588b4dcd)
![1676c0d05536b66c60eef539410f4a22](https://github.com/user-attachments/assets/93a58ef4-5c48-4ed4-bbdf-ad581862afa6)

**Comment by ZengXiaoPi** [comment]
重复 #275
