### ISSUE TITLE
游戏内汉化补丁未落实

### ISSUE THREAD

**Issue by loxing-114** [LocalizeLimbusCompany/LocalizeLimbusCompany#279]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

1：游戏主界面汉化正常，进入游戏后汉化未落实【全是英文】且控制台爆红字
2：频繁出现汉化未落实的情况【打开游戏后控制台未跟随启动】

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/17226645/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/17226646/Player.log)

### 截图

![屏幕截图 2024-10-02 163421](https://github.com/user-attachments/assets/9a8453da-78dc-4c9a-8e34-f384bae6ef8c)

### 还有别的吗？

系统：win10 64位
处理器:i5-9400 CPU
显卡：1050ti

**Comment by ZengXiaoPi** [comment]
#275

**Comment by loxing-114** [comment]
请问还没处理吗

**Comment by ZengXiaoPi** [comment]
`新版本已修复，请等待更新。`
希望你真的打开#275看了。

**Comment by loxing-114** [comment]
对不起大大
