### ISSUE TITLE
更新补丁后汉化缺失且进入剧情后游戏卡死

### ISSUE THREAD

**Issue by Charger987** [LocalizeLimbusCompany/LocalizeLimbusCompany#280]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

本次更新后我同步更新了汉化补丁，但在进入游戏后出现严重问题。除了仅在加载界面有汉化之外，当我尝试进入4.5-1阅读剧情时游戏直接卡死在剧情页面，剧情没有显示且无法跳过剧情，只能关闭游戏。多次尝试后再次尝试进入游戏更是直接闪退，而卸载补丁后所有问题得到解决。

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/17228790/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/17228801/Latest.log)

### 截图

![image](https://github.com/user-attachments/assets/af49eb23-4fac-44c2-acd1-8f31621d9992)
![image](https://github.com/user-attachments/assets/7685cb6b-1639-4bcd-b0f2-bb77967f1793)

**Comment by ZengXiaoPi** [comment]
重复 #275
