### ISSUE TITLE
战斗中角色详情页面  鼠标放在体力条上的明细里  有多处口口口

### ISSUE THREAD

**Issue by qingfeng6897** [LocalizeLimbusCompany/LocalizeLimbusCompany#281]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

战斗中角色详情页面  鼠标放在体力条上的明细里  有多处口口口

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/17268472/Player.log)

### 截图

![QQ_1728198559669](https://github.com/user-attachments/assets/6920e581-c9ce-4fcd-a407-d4f270cbd530)

**Comment by Nephthys137** [comment]
看起来月亮又整了活,我在想有没有必要单独修复

**Comment by N071** [comment]
感谢反馈。目前额外看了一下这部分文本的情况，这里是因为无法统一的应用我们提供的简体中文字体导致的，但我们当前还是不计划单独对其进行处理。类似的情况在之前也发生过，往往出现于比较隐蔽处的字体，情况也比较多变。为了尽量减少以后可能出现的问题，在这部分较少用到之处的文本目前就不单独做对策了。

**Comment by qingfeng6897** [comment]
> 感谢反馈。目前额外看了一下这部分文本的情况，这里是因为无法统一的应用我们提供的简体中文字体导致的，但我们当前还是不计划单独对其进行处理。类似的情况在之前也发生过，往往出现于比较隐蔽处的字体，情况也比较多变。为了尽量减少以后可能出现的问题，在这部分较少用到之处的文本目前就不单独做对策了。

没事有帮助就行
