### ISSUE TITLE
关于Cinq北部默尔索三技能的翻译

### ISSUE THREAD

**Issue by Tirelent** [LocalizeLimbusCompany/LocalizeLimbusCompany#285]
### 说说你遇到的问题？

经查证，日译サリュ ー和英译Salut均对应法语单词salut。搜索后可知salut是一句语气比较随意、可用于任何时间的招呼语，并非英文salute之意（致敬）。结合设定，个人猜测应该是在向直播的观众问好，可根据这点修改翻译

**Comment by mucketguct** [comment]
您好，非常感谢您的反馈！这里其实是这样的啦：

首先是Salut一词的释义啦，以下内容是salut一词的中文-法语释义，在这里引用2则法汉词典的释义，可以作为参考：



WordReference的释义（https://www.wordreference.com/frzh/salut）：

1. 拯救， 解救; 得救， 安全； 拯救者

2. 致意， 致敬， 敬礼

3. 向你致敬（表示敬意、赞赏）；
[俗] 你好；再见（用以问候或告别）

4. 礼节， 仪式

5. [宗]（灵魂）得救； 永福；（天主）夜课



法语助手-法汉词典的释义（https://www.wordreference.com/frzh/salut）：

1、（非正式用语）  喂, 嗨, 你好

2、（军队）敬礼

3、救助者（救助途径）；解救者（解决方法）

4、（宗教）得救，灵魂得救，救赎

5、拯救，救助

6、（非正式用语）回见，走了

7、（非正式用语）再见

8、（俚语）你好



可以见得，Salut一词确实可以作为招呼语使用，但在翻译中没有采用这一含义，是因为这一含义以非正式场合的俚语形式为主啦；

由于Cinq协会的决斗氛围，这里比较可能采用的是更正式的、军队用语的“敬礼；致敬；向您致敬”这一含义啦；

也因此，才选用了“向您致敬”这一释义，在表现“致敬”这一主要含义的基础上，也尽可能希望表现这个词潇洒倜傥、非正式用语的一面啦。

其实我们也有猜测，这里也确实有可能，在使用剧情中用于直播的，非正式用语的招呼语的含义，但另一个在这里使用“向您致敬”的主要原因是，Cinq协会堂吉诃德人格的三技能，技能名称同样是Salut啦。由于Cinq堂吉诃德并没有直播相关的业务，以及原文相同时尽可能保证译文相同的翻译方针，这里还是猜测，Salut更有可能是Cinq协会内部通用的正式用语啦（当然也确实依然带有非正式用语的潇洒啦），总之也还是因为这些原因，保留“向您致敬”啦。

非常感谢反馈！老师的想法也很有见解，祝您玩得开心啦——

**Comment by N071** [comment]
另外不论是英文的Salute，还是法文的Salut，究其根本应该都源自拉丁语中的Salus(健康、平安)。（这俩家伙长得像是有原因的）
Salut和Salute在实际的使用中已经几乎脱离了其Salus的原本含义，已经变得像我们日常使用的诸如“幸福安康”、“恭喜发财”这类招呼语一样，显得符号化和口语化。
所以它本质上就是一句问候语，原本的意思其实显得……不那么重要。因此老师若是把这句Salut理解成向观众问好，也并非不可行。不过我们在这里倾向于认为是向对面前的对手问好(致敬)的这种场景。
