### ISSUE TITLE
关于圣愚队长技能，以及两个t社员工名字的翻译问题

### ISSUE THREAD

**Issue by Carameleoncookie** [LocalizeLimbusCompany/LocalizeLimbusCompany#286]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

t公司的两个征收人员分别是射杀和压制，但是他们的名字貌似安反了，射杀的人员没有枪，反倒是压制的人有
![Screenshot_2024-10-15-09-09-16-251_com microsoft emmx](https://github.com/user-attachments/assets/45098c39-4103-4efd-b0c7-e60f88a71678)
![Screenshot_2024-10-15-09-09-11-759_com microsoft emmx](https://github.com/user-attachments/assets/65be76ed-44fb-4159-a961-74edd9182b4c)

### 有什么好的想法？

不知道日本和韩语原本是什么样的，但在英语里的“can't use that weapon”指的应该指的是发明还是半成品，还没到用的时候，结合罪孽资源是怠惰，应该是这样吧

也许可以翻译成“时候未到”或者“还不能用那个武器”比较合适。
![Screenshot_2024-10-15-08-28-15-952_tv danmaku bili](https://github.com/user-attachments/assets/717ebfd4-229d-4109-a7cd-cfe74e48a5cc)

**Comment by mucketguct** [comment]
您好，感谢您的反馈！这边的具体情况其实是这样的啦：

关于这两位T公司员工，名字确实比较有可能反了，我们一开始也发现了这个问题；

但遗憾的是，在游戏中检查后，发现这边比较有可能是月计的一个程序bug，译文与月计三语原文的对应都没有问题，比较有可能是月计在游戏中实装时，装反了名字；

尽管这里比较有可能是月计装反了名字，但鉴于这种可能性没有特别能够100%确定，我们也还是优先遵循三语原文啦，以免月计在这里表面上装反了人名，但实际上是以后剧情中的伏笔之类的，感谢您的理解；以下是这两处文本的链接，可以参考：

https://paratranz.cn/projects/6860/strings?id=467430244
https://paratranz.cn/projects/6860/strings?id=467430246

关于这类月亮计划的程序bug问题，也可以考虑通过月亮计划的官方邮箱进行反馈啦，也祝您顺利啦：

limbussupport@projmoon.com

关于技能“你那武器报废了吧？”，这一处技能名称的三语原文是这样的啦：

EN（英文文本）：Can't Use That Weapon Now
JP（日文文本）：その武器使えなくなるぞ？
KR（韩文文本）：그 무기 못쓸걸?

没错，此处的JP和KR在句尾都使用了问号，整个句子是反问语气，这里确实是一处英文文本的笔误啦，漏掉了那个关键的问号；按照JP与KR文本来理解的话，有可能言下之意是罪人们的武器粗陋，不能与圣愚自研的武器相比，之类的意思。以下是此处文本的链接，可以参考：

https://paratranz.cn/projects/6860/strings?id=467430435

总之感谢反馈，也祝玩得开心啦——
