### ISSUE TITLE
汉化模组的脏字是否有点过于保守

### ISSUE THREAD

**Issue by haoge114** [LocalizeLimbusCompany/LocalizeLimbusCompany#287]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

汉化模组有很多例如蠢货，白痴，傻子等现实生活中不常用的脏话，我们应该选取那些现实生活中更加常用的脏话，毕竟这些脏话咱们本身就很少使用了(毕竟咱们的脏话比别的国家脏话多多了)。就感觉译者有些过于拘束了，搞的有点文明了？有一种和现实生活的割裂感，有点不太真实的感觉。这毕竟是一款R18+的游戏，出现脏话是非常正常的，反而没有出现脏话才是一件非常奇怪的事情，毕竟在都市这种环境下骂人也是再正常不过的事情了

**Comment by N071** [comment]
我们认为目前对这些文本的处理是适宜，且能忠实反应原文语气程度的，我们不愿对其进行更加深的处理了。
实际上，其他语言当中的俚语和亵渎，其语气远可以更加严重。不过我们并没有在原文中读到更过分的说法，因此我们认为目前的程度相对来说已经比较合适了。
