### ISSUE TITLE
想知道苍白之物的那些摩斯密码都对应了什么

### ISSUE THREAD

**Issue by Carameleoncookie** [LocalizeLimbusCompany/LocalizeLimbusCompany#288]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

看到有人说这是韩语摩斯密码，不知道该怎么翻译啊

**Comment by N071** [comment]
- 这里是翻译模组的Issue，Issue被用来反馈问题，而**不是**剧情讨论区
  - 在这里进行维护的大多是开发者，很难直接为您解答剧情考据上的疑问
  - 如果您对此类问题感兴趣的话，建议到评论区或者贴吧询问
- 我们在模组中决定不对这些摩斯电码进行翻译（和其他语言一样不做更改），是为保留原文意图
- 幸运的是，我们曾对此进行过分析
  - 这个分析在Wiki上就能找得到，请你参考以下链接：[链接](https://limbuscompany.huijiwiki.com/wiki/%E7%AB%A0%E8%8A%82V_%E5%AE%9A%E4%B9%89%E4%B8%BA%E6%81%B6#%E8%80%83%E6%8D%AE)
