### ISSUE TITLE
关于提取“概率详情”页中存在语句不通顺的句子的问题。

### ISSUE THREAD

**Issue by Sephira-Vanitas** [LocalizeLimbusCompany/LocalizeLimbusCompany#290]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

如图所示，最后一行“平分概率这一概率”出现语句不通顺的问题，根据想要表达的意思，建议删除前一“概率”，使原句变为“平分这一概率”

### 日志文件

提取界面的“概率详情”页面中存在的语句问题

### 截图

![psc](https://github.com/user-attachments/assets/8b7cd4df-45c6-40f8-a5d8-50c563e13971)

**Comment by Nephthys137** [comment]
感谢反馈,新版本会一并修复
