### ISSUE TITLE
中文模组和其他语言冲突

### ISSUE THREAD

**Issue by KunMNX** [LocalizeLimbusCompany/LocalizeLimbusCompany#291]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

中文mod使用后无法正常切换其他语言，若在中文mod打开情况下，本人的边狱巴士会出现登录界面出现后快速闪退问题，需要关闭mod后才能使用其他语言游玩

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/17437526/Player.log)

**Comment by ZengXiaoPi** [comment]
重复议题。
请使用工具箱的`关闭模组`功能

**Comment by mucketguct** [comment]
如果先在游戏中切换了语言，随后因此遇到闪退问题的话，可以先使用工具箱卸载并重新安装一次模组，即可解决此问题；

后续如果需要切换模组的话，直接在工具箱的“设置”栏中，使用“关闭模组”功能，再进入游戏切换语言，即可避免闪退问题
