### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by morty-909** [LocalizeLimbusCompany/LocalizeLimbusCompany#292]
### 说说你遇到的问题？

第一张是汉化更新以后50级纽本的蛙蛙左右眼名字都变成躯干，40的没变.第二张Loading是更新前截的，所以不知道更新之后改没改，如果按照顺序应该是沉沦在呼吸前面（另外是真的有人会看Loading的）
![屏幕截图 2024-10-19 104509](https://github.com/user-attachments/assets/37b1ce75-0d85-49e5-810e-fbc0ec8ab0d3)
![屏幕截图 2024-10-19 140027](https://github.com/user-attachments/assets/ebafc778-299e-4cb3-9052-10f3a59f8239)

**Comment by mucketguct** [comment]
您好，非常感谢反馈！这边我们也注意到了；目前这一情况疑似是月计在本周更新中新增的程序bug，所导致的文本错位bug；

可以先等等看下周一月亮计划的公告内容，有可能会说明对此问题的修复，总之可以先等下周一公告再看看啦，总之也感谢反馈啦
