### ISSUE TITLE
请问血魔们的debuff“衰老”是更符合本意的吗？

### ISSUE THREAD

**Issue by Carameleoncookie** [LocalizeLimbusCompany/LocalizeLimbusCompany#294]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为不懂韩语和日语，特来询问一下。因为英语中可以翻译成“凋零”或者“衰弱”，而血魔们的样貌貌似还没什么老化的样子，即使是理发师伤痕累累的脸，也没有什么老化的感觉。

**Comment by ZengXiaoPi** [comment]
```
EN :
Withered
JP :
老衰
KR：
노쇠
```
这是原文，因为边狱是韩国游戏，所以优先看韩文`노쇠`，这个词在韩文中意义即为“衰老”
日文中，`老衰`也可以很轻松的找到对应的释意，仍然是“衰老”
鉴于韩文和日文都使用的是“衰老”，且Withered在英语中更多指的是植物的凋谢，也可以引申至衰老这个意思，所以此处选择翻译为“衰老”，如果您有别的意见可以Reopen这个issue。

**Comment by N071** [comment]
另外提醒一下，后续有关剧情内容的疑问，还请移步其他地方解决。Issue是解决问题的地方，大概需要您做较为全面的了解之后，再**负责任地**提出问题。对于与原文相关的疑问，还希望您能先自行查证对照，以减少我们双方所做的重复工作。
这件事我在[Issue288](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/288)当中就已经申明过。
