### ISSUE TITLE
关于技能名称

### ISSUE THREAD

**Issue by Carameleoncookie** [LocalizeLimbusCompany/LocalizeLimbusCompany#295]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

感觉人格的三个技能的字数如果可以的话，能一致比较好。就像是n辛的技能，会感觉很顺畅。有些技能，比如十罗的技能“知识的重量”可以缩节成“知识之重”；有些技能比如六良的“全面战”，在其他两个技能是四字的情况下会有些突兀，可以变成“全面战斗”这样就会提升一些观感。当然，有些完全没法改变的技能只能保留，比如圣愚宝子哥的二技能，不必强求。当然一切的一切要看零协会，有没有这方面的意向，我也可以协助帮忙

**Comment by N071** [comment]
嗯……在偏向四个字走的基础上，我们其实不太愿意对自己的字数做太多限制了。字数上的限制往往会得出比较奇怪的结果（比如美味多之这种）。所以从整体上来讲，我们目前对技能翻译的**字数规定是比较自由的**，最开始大概不会考虑字数情况，只是输出了自己觉得比较贴切喜欢的翻译。

接下来是您这边提到的两个例子：

“知识的重量”在节奏上其实是对应“苦痛的启蒙”。
~~从我个人感觉上来讲，“知识之重”里的“zhi”有点太多了（~~

全面战这边的话是个特殊情况，我们对其有单独讨论过。这里的原文：
All-out War - 全面戦争 - 전면전
从韩语出发的角度，我们将전면전翻译成了全面战，同样也是三个音节。虽然不管是战争、战斗、战法什么的都很接近啦，我们还是觉得日语的全面战争稍微差一点（“战争”两个字不如“战”一个字）。这里主要表达的是一种六协会的战法战术，而不是一场战争。
打个比方：
我们习惯说歼灭战，而不说歼灭战争；
我们习惯说遭遇战，而不说遭遇战斗；
我们习惯说游击战，而不说游击战术；
我们习惯说地道战，而不说地道战法；
等等。
对于这里的全面战，我们也是一样的思路。
> 六协会向来如此，先以全面战的形式牵制对方的行动，再由科长级别的人物消灭对方的首领，从而在大规模的战斗中取得成功。
