### ISSUE TITLE
BOSS对决时没有特效字幕

### ISSUE THREAD

**Issue by zcx2cx** [LocalizeLimbusCompany/LocalizeLimbusCompany#299]
### 说说你遇到的问题？

就是飘在天上的那个特效字幕，只有拼点的时候会出现。其余时间的剧情boss战不会出现，安装第七章汉化之前的汉化文件都可以显示。第七章之后就不行了

**Comment by ZengXiaoPi** [comment]
请提供日志，截图。

**Comment by zcx2cx** [comment]
游戏的截图暂时没有 我没有体力了。。
![fad524df68c64f2105ecb88edbfc62b3](https://github.com/user-attachments/assets/948dab20-e4e3-4fd7-b52a-36e2dc7b364c)

**Comment by ZengXiaoPi** [comment]
无法复现+无有效游戏日志
