### ISSUE TITLE
5-36神备亚哈战第二、三阶段歌词缺失

### ISSUE THREAD

**Issue by yixinyun** [LocalizeLimbusCompany/LocalizeLimbusCompany#300]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

零协你好！
我在进行以实玛丽单人神备亚哈战时发现二、三阶段的屏幕滚动歌词消失。其中：准备阶段（连线阶段）一定不会出现歌词，拼点阶段及攻击动画阶段有一定概率出现歌词（个人体感三阶段出现概率比二阶段高很多，且拼点结束后进入攻击动画时出现歌词的概率最高，但因为测试次数很少不一定具备参考价值）
为确保不是偶然情况我有尝试过关闭游戏重启、用工具箱点击安装补丁确保时最新版本、增加队伍人数、更换人格等操作，依旧出现上述歌词问题。（不知道会不会有帮助所以单纯提一下，以实玛丽更换成亚哈人格时特殊开场台词正常触发）
抱歉因为对程序方面不擅长，我不太确定这个是否是普遍情况，上传的日志文件也不能确定正确（没找到MelonLoader对不起T T），如果有需要补充的信息或上传的文件我会尽可能补上。谢谢你们的汉化！

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/17573923/Latest.log)

### 截图

![20241030210654_1](https://github.com/user-attachments/assets/d13623cd-c096-4044-8778-64cd02de2fd7)
![20241030211408_1](https://github.com/user-attachments/assets/8df69f41-58c9-4e85-9458-1c838936542b)
![20241030211855_1](https://github.com/user-attachments/assets/2ec636b8-032e-4885-9c74-1657974477f9)
![20241030212112_1](https://github.com/user-attachments/assets/5b07b0c7-4261-4378-aaa9-28fd2ed3fe2a)
![20241030212147_1](https://github.com/user-attachments/assets/613d6174-ad83-49f9-8753-1051d335dbc9)
![20241030213500_1](https://github.com/user-attachments/assets/95142831-4acf-4df9-b406-14080380b55a)
![20241030213751_1](https://github.com/user-attachments/assets/85a42cd9-ded1-4423-ab3b-af791533ef67)

**Comment by N071** [comment]
感谢反馈。我们目前其实不太确定这是否是汉化模组导致的问题，从目前的状况来看，我们的模组对游戏的影响其实是有限的，往往是保守地进行更改和解决问题。
正常来讲，只要有一处歌词能够正确显示，其他的歌词是不太应该被吞掉的。显示逻辑毕竟都是同一种，没什么区别。

游戏原本的体验是，歌词应当是只有在BGM出现人声时才会同步出现，没有人声的时候是没有对应歌词字幕的，您确定不是这方面的原因吗？
如果不是，我们可能还得再观察一下这个情况，并且要再对比一下原版体验才能试着找出问题。

**Comment by yixinyun** [comment]
只有出现人声时才会同步出现歌词这点，我确认过了，我在第二、第三阶段的拼点准备（连线）阶段等到mili唱到循环处都没有发现过一句歌词。今天又测试了三次依旧是老样子。
另外关于这个疑似bug，今天测试下来还有几个发现：1、6-48（还是49？就是第六章最后一关）歌词显示一直正常；2、镜牢中的克罗默和亚哈也有不显示歌词的问题，所以应该不是主线地牢的问题；3、之前说的拼点及攻击动画阶段出现歌词，目前很大可能是只有在使用三技能的时候才会出现歌词，即三技能的拼点动画与攻击动画阶段所有歌词正常显示，但其他时候均不出现。
在临发送这篇补充评论时看到B站有一个神父虫单人困难镜牢亚哈的视频，发现也有歌词不出现的问题，但因为选择的语言是日语，所以看下来应该是yj的问题，而不是汉化补丁的问题了。（另外感觉上面所说的3的可能性更大了）总之辛苦你们了，谢谢！
