### ISSUE TITLE
求助，进不去游戏  这样子   il2cpp_runtime_invoke detour failed: hook error

### ISSUE THREAD

**Issue by 3264084688** [LocalizeLimbusCompany/LocalizeLimbusCompany#303]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

安装完工具箱，无论工具箱安装还是手动安装，都无法进游戏

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/17790357/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/17790358/Player.log)

### 截图

<img width="736" alt="屏幕截图 2024-11-17 181507" src="https://github.com/user-attachments/assets/000ac796-c447-49e2-8159-0ddf2e15ef93">

### 还有别的吗？

win11

**Comment by ZengXiaoPi** [comment]
你是从哪里搞来0.5.x的古董的？

**Comment by 3264084688** [comment]
> 你是从哪里搞来0.5.x的古董的？

我下的0.6.58的也是显示的这个哎

**Comment by N071** [comment]
> > 你是从哪里搞来0.5.x的古董的？
> 
> 我下的0.6.58的也是显示的这个哎

你的模组版本严重过时，你大概不可能是从我们提供的正常渠道获取的模组。你可以告诉我们你是在哪里获取到版本如此落后的模组的吗？

**Comment by 3264084688** [comment]
> 你是从哪里搞来0.5.x的古董的？

怎么办嘞

**Comment by N071** [comment]
> > > > 你是从哪里搞来0.5.x的古董的？
> > > 
> > > 
> > > 我下的0.6.58的也是显示的这个哎
> > 
> > 
> > 你的模组版本严重过时，你大概不可能是从我们提供的正常渠道获取的模组。你可以告诉我们你是在哪里获取到版本如此落后的模组的吗？
> 
> 啊，我从零协会给的链接下的啊

什么链接？蓝奏云？百度云吗？
我们目前正常启用且正在维护的下载链接，里面根本没有这么老的模组

**Comment by 3264084688** [comment]
> > > > > 你是从哪里搞来0.5.x的古董的？
> > > > 
> > > > 
> > > > 我下的0.6.58的也是显示的这个哎
> > > 
> > > 
> > > 你的模组版本严重过时，你大概不可能是从我们提供的正常渠道获取的模组。你可以告诉我们你是在哪里获取到版本如此落后的模组的吗？
> > 
> > 
> > 啊，我从零协会给的链接下的啊
> 
> 什么链接？蓝奏云？百度云吗？ 我们目前正常启用且正在维护的下载链接，里面根本没有这么老的模组
> 
> 能把链接贴出来我看一下吗

https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/303#issuecomment-2481261410

**Comment by N071** [comment]
你给的链接好像不太正常？不知道为什么是指向这个issue的链接

**Comment by 3264084688** [comment]
> > > > > 你是从哪里搞来0.5.x的古董的？
> > > > 
> > > > 
> > > > 我下的0.6.58的也是显示的这个哎
> > > 
> > > 
> > > 你的模组版本严重过时，你大概不可能是从我们提供的正常渠道获取的模组。你可以告诉我们你是在哪里获取到版本如此落后的模组的吗？
> > 
> > 
> > 啊，我从零协会给的链接下的啊
> 
> 什么链接？蓝奏云？百度云吗？ 我们目前正常启用且正在维护的下载链接，里面根本没有这么老的模组
> 
> 能把链接贴出来我看一下吗
[https://www.zeroasso.top/docs/install/install](url)

**Comment by N071** [comment]
对的，这个链接是我们的官网链接，然后你是按的哪个下载按钮？

**Comment by 3264084688** [comment]
> 对的，这个链接是我们的官网链接，然后你是按的哪个下载按钮？

我刚才第二个刚下载试了一遍，还是这样的

**Comment by 3264084688** [comment]
> 对的，这个链接是我们的官网链接，然后你是按的哪个下载按钮？

之前是第一个OneDrive，现在是第二个GitHub，进游戏还是这样

**Comment by N071** [comment]
“第二个”是哪个？我不知道你在说什么啊（（
我可以确定的告诉你的是，我们的下载站上根本不存在这么老的(0.5.x)版本的模组。除非你是进入了GitHub下载页面，然后下载了非常非常老的版本。
我们现在的最新版是0.6.57，而你的模组停留在0.5.4

**Comment by N071** [comment]
你下载的0.6.58是“字体文件”版本，而不是模组框架。你的模组框架严重过时了，请你删掉现在这个模组框架，然后下载最新的BepInEx框架。

**Comment by N071** [comment]
你不能用安装器进行安装吗？手动安装对你来说好像不太方便。

**Comment by 3264084688** [comment]
> 你不能用安装器进行安装吗？手动安装对你来说好像不太方便。

我刚开始就是自动安装，但是就是这样的，我给的截图就是自动安装的，后面才转手动的

**Comment by N071** [comment]
> > 你不能用安装器进行安装吗？手动安装对你来说好像不太方便。
> 
> 我刚开始就是自动安装，但是就是这样的，我给的截图就是自动安装的，后面才转手动的

……不太可能。你的安装器是从哪里获取的，也是从我们的正式渠道中获取的吗？

**Comment by N071** [comment]
总之你应该都下载最新版本的东西。无论是最新版本的安装器，或者是最新版本的模组框架+字体文件+模组本体

**Comment by 3264084688** [comment]
> > > 你不能用安装器进行安装吗？手动安装对你来说好像不太方便。
> > 
> > 
> > 我刚开始就是自动安装，但是就是这样的，我给的截图就是自动安装的，后面才转手动的
> 
> ……不太可能。你的安装器是从哪里获取的，也是从我们的正式渠道中获取的吗？

对啊，因为最开始推荐不就是自动安装，我真不骗兄弟，骗兄弟我死完的

**Comment by N071** [comment]
最新版框架：https://github.com/LocalizeLimbusCompany/BepInEx_For_LLC/releases/tag/v6.0.1-LLC
最新版字体文件：https://github.com/LocalizeLimbusCompany/LLC_ChineseFontAsset/releases/tag/241025
最新版模组本体：https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/releases/tag/v0.6.58

**Comment by ZengXiaoPi** [comment]
我来吧。
当前版本的工具箱已经去除了卸载Melonloader汉化补丁的功能，与之相对应的，除了已经过期的工具箱与Archived的Melonloader For LLC仓库，没有地方能下载MelonLoader

**Comment by N071** [comment]
> 最新版框架：https://github.com/LocalizeLimbusCompany/BepInEx_For_LLC/releases/tag/v6.0.1-LLC 最新版字体文件：https://github.com/LocalizeLimbusCompany/LLC_ChineseFontAsset/releases/tag/241025 最新版模组本体：https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/releases/tag/v0.6.58

我不是说你骗我啦，但是你这个情况真的有点让我摸不着头脑。现在你把之前下载的东西都删干净，然后用上面三个链接再试试。

**Comment by ZengXiaoPi** [comment]
你目前的边狱公司目录同时存在Melonloader和BepInEx，由于某种原因，MelonLoader会被优先加载，所以你的汉化补丁即使更新到最新版也无法加载，因为目前的汉化补丁基于BepInEx

**Comment by ZengXiaoPi** [comment]
所以你需要删除Melonloader的文件和目录，具体我已经忘了有哪些了，你可以截图一下边狱公司目录，这样我方便看

**Comment by N071** [comment]
> 你目前的边狱公司目录同时存在Melonloader和BepInEx，由于某种原因，MelonLoader会被优先加载，所以你的汉化补丁即使更新到最新版也无法加载，因为目前的汉化补丁基于BepInEx

这个的意思就是你在安装新版本之前，需要把旧版本删光。要不然残留的东西会导致你出现这样的问题。

**Comment by N071** [comment]
如果你搞不清楚哪些是模组文件，哪些是游戏本身的文件了：
就把整个游戏的根目录（模组文件连同游戏文件一起全都）删了，然后从Steam验证游戏文件完整性，重新下载一遍游戏文件。

**Comment by 3264084688** [comment]
<img width="760" alt="屏幕截图 2024-11-17 212720" src="https://github.com/user-attachments/assets/a2f11ad2-6c21-4b58-86a0-0a62df3a4b18">

<img width="753" alt="屏幕截图 2024-11-17 212702" src="https://github.com/user-attachments/assets/721f479f-ce9a-4ecd-b0ae-432058ef4d85">

**Comment by 3264084688** [comment]
我删掉了之前安装的，是这样的吧

**Comment by N071** [comment]
> <img alt="屏幕截图 2024-11-17 212720" width="760" src="https://private-user-images.githubusercontent.com/188755660/386962200-a2f11ad2-6c21-4b58-86a0-0a62df3a4b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA0MDIsIm5iZiI6MTczMTg1MDEwMiwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyMjAwLWEyZjExYWQyLTZjMjEtNGI1OC04NmEwLTBhNjJkZjNhNGIxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTI2ODUyZjAwNTFiODEzNjc0Yjg4NjNlMmEwOTA5ZWVhOWMzMGI0YjNhOGJkNjZhOTIyMjVhMzZmZjhiZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xbv0baCHY8ptGETAp_jXTy6yumzyi7LTAf_zI9mSjbw"> <img alt="屏幕截图 2024-11-17 212702" width="753" src="https://private-user-images.githubusercontent.com/188755660/386962182-721f479f-ce9a-4ecd-b0ae-432058ef4d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA0MDIsIm5iZiI6MTczMTg1MDEwMiwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyMTgyLTcyMWY0NzlmLWNlOWEtNGVjZC1iMGFlLTQzMjA1OGVmNGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGNkM2QxMmUwMWMwMWMyNGQxMTgzM2U1MWJjYjk5MDEzODg2YjJmYzk5Y2MwZTAzMDViMTFlZWI2OWQ0NTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s3BARTIywKkSYoxEvSg_r93LyfAeUY5BiJw_YmWgAbA">

垃圾文件过多。按照我说的删干净重新下载吧。正确安装的样子，参考这个链接里的图片：https://www.zeroasso.top/docs/install/install#%E5%AE%8C%E6%88%90

**Comment by ZengXiaoPi** [comment]
敢问你的工具箱是什么版本？

**Comment by 3264084688** [comment]
> 敢问你的工具箱是什么版本？

自动安装给的OneDrive链接，我也不知道什么版本

**Comment by 3264084688** [comment]
> > <img alt="屏幕截图 2024-11-17 212720" width="760" src="https://private-user-images.githubusercontent.com/188755660/386962200-a2f11ad2-6c21-4b58-86a0-0a62df3a4b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA0MDIsIm5iZiI6MTczMTg1MDEwMiwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyMjAwLWEyZjExYWQyLTZjMjEtNGI1OC04NmEwLTBhNjJkZjNhNGIxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTI2ODUyZjAwNTFiODEzNjc0Yjg4NjNlMmEwOTA5ZWVhOWMzMGI0YjNhOGJkNjZhOTIyMjVhMzZmZjhiZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xbv0baCHY8ptGETAp_jXTy6yumzyi7LTAf_zI9mSjbw"> <img alt="屏幕截图 2024-11-17 212702" width="753" src="https://private-user-images.githubusercontent.com/188755660/386962182-721f479f-ce9a-4ecd-b0ae-432058ef4d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA0MDIsIm5iZiI6MTczMTg1MDEwMiwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyMTgyLTcyMWY0NzlmLWNlOWEtNGVjZC1iMGFlLTQzMjA1OGVmNGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGNkM2QxMmUwMWMwMWMyNGQxMTgzM2U1MWJjYjk5MDEzODg2YjJmYzk5Y2MwZTAzMDViMTFlZWI2OWQ0NTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s3BARTIywKkSYoxEvSg_r93LyfAeUY5BiJw_YmWgAbA">
> 
> 垃圾文件过多。按照我说的删干净重新下载吧。正确安装的样子，参考这个链接里的图片：https://www.zeroasso.top/docs/install/install#%E5%AE%8C%E6%88%90

其他的全删掉？

**Comment by ZengXiaoPi** [comment]
不可能，OD只有最新版，你打开截图我看看

**Comment by N071** [comment]
我感觉你没有按照安装页面内的指引进行操作，而且残留了很多清朝时期的文件。请你认真读完其中的内容，并仔细对比其中提供的文件体系。如果你的文件体系不符合文档站里展示的内容，那就证明你的操作有误。

无关的旧版本文件和垃圾，当然要删干净。

**Comment by 3264084688** [comment]
> 不可能，OD只有最新版，你打开截图我看看

<img width="714" alt="image" src="https://github.com/user-attachments/assets/072b8c36-9bfd-4e16-abad-c4cb2aacaba9">

**Comment by N071** [comment]
> > 不可能，OD只有最新版，你打开截图我看看
> 
> <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/188755660/386962529-072b8c36-9bfd-4e16-abad-c4cb2aacaba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA3MDksIm5iZiI6MTczMTg1MDQwOSwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyNTI5LTA3MmI4YzM2LTliZmQtNGUxNi1hYmFkLWM0Y2IyYWFjYWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE5ZTQwYzY5MmQ5OGMxYTA5MGJlNjUzNGMwZGMwNjEwZjU5ZGRiY2RmOTYxNmY1NjBjMzBlMGE1ODU3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OQMXJlz72834MvfYxRYqgegIah31OmrTmUAUQ62rnZY">

这确实是最新版。你不能通过这个来安装模组吗？

**Comment by ZengXiaoPi** [comment]
你这就是新版啊，怎么可能安装到MelonLoader的，代码我都重构三四次了
总之你先按北岚说的，删一遍垃圾文件吧

**Comment by 3264084688** [comment]
> > > 不可能，OD只有最新版，你打开截图我看看
> > 
> > 
> > <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/188755660/386962529-072b8c36-9bfd-4e16-abad-c4cb2aacaba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA3MDksIm5iZiI6MTczMTg1MDQwOSwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyNTI5LTA3MmI4YzM2LTliZmQtNGUxNi1hYmFkLWM0Y2IyYWFjYWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE5ZTQwYzY5MmQ5OGMxYTA5MGJlNjUzNGMwZGMwNjEwZjU5ZGRiY2RmOTYxNmY1NjBjMzBlMGE1ODU3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OQMXJlz72834MvfYxRYqgegIah31OmrTmUAUQ62rnZY">
> 
> 这确实是最新版。你不能通过这个来安装模组吗？

我最开始就是通过这个安装的嘞，有可能是以前我玩的时候加了汉化没有删是吗？

**Comment by N071** [comment]
我看你的文件夹里有些东西都是2023年7月的了，那些已经严重过时。先把无关的文件全删掉再说。而且我建议你按照我说的，把整个文件夹全清空，然后从Steam检测游戏文件完整性重新下载。

不要过于自信，你一个个挑着删，很可能出问题。

**Comment by 3264084688** [comment]
> > > 不可能，OD只有最新版，你打开截图我看看
> > 
> > 
> > <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/188755660/386962529-072b8c36-9bfd-4e16-abad-c4cb2aacaba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA3MDksIm5iZiI6MTczMTg1MDQwOSwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyNTI5LTA3MmI4YzM2LTliZmQtNGUxNi1hYmFkLWM0Y2IyYWFjYWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE5ZTQwYzY5MmQ5OGMxYTA5MGJlNjUzNGMwZGMwNjEwZjU5ZGRiY2RmOTYxNmY1NjBjMzBlMGE1ODU3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OQMXJlz72834MvfYxRYqgegIah31OmrTmUAUQ62rnZY">
> 
> 这确实是最新版。你不能通过这个来安装模组吗？

我最开始就是通过这个安装的嘞，有可能是以前我玩的时候加了汉化没有删是吗？

**Comment by 3264084688** [comment]
> > > 不可能，OD只有最新版，你打开截图我看看
> > 
> > 
> > <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/188755660/386962529-072b8c36-9bfd-4e16-abad-c4cb2aacaba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA3MDksIm5iZiI6MTczMTg1MDQwOSwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyNTI5LTA3MmI4YzM2LTliZmQtNGUxNi1hYmFkLWM0Y2IyYWFjYWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE5ZTQwYzY5MmQ5OGMxYTA5MGJlNjUzNGMwZGMwNjEwZjU5ZGRiY2RmOTYxNmY1NjBjMzBlMGE1ODU3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OQMXJlz72834MvfYxRYqgegIah31OmrTmUAUQ62rnZY">
> 
> 这确实是最新版。你不能通过这个来安装模组吗
我最开始就是通过这个安装的嘞，有可能是以前我玩的时候加了汉化没有删是吗？

**Comment by 3264084688** [comment]
> 我看你的文件夹里有些东西都是2023年7月的了，那些已经严重过时。先把无关的文件全删掉再说。而且我建议你按照我说的，把整个文件夹全清空，然后从Steam检测游戏文件完整性重新下载。
> 
> 不要过于自信，你一个个挑着删，很可能出问题。

我现在就是这样的，全删了
<img width="512" alt="{12C556A7-61BF-4B8E-979F-5AAF5550B07C}" src="https://github.com/user-attachments/assets/d5bef637-1493-446d-bbc6-792c74d1c11d">

**Comment by ZengXiaoPi** [comment]
> > > > 不可能，OD只有最新版，你打开截图我看看
> > > 
> > > 
> > > <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/188755660/386962529-072b8c36-9bfd-4e16-abad-c4cb2aacaba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA3MDksIm5iZiI6MTczMTg1MDQwOSwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyNTI5LTA3MmI4YzM2LTliZmQtNGUxNi1hYmFkLWM0Y2IyYWFjYWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE5ZTQwYzY5MmQ5OGMxYTA5MGJlNjUzNGMwZGMwNjEwZjU5ZGRiY2RmOTYxNmY1NjBjMzBlMGE1ODU3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OQMXJlz72834MvfYxRYqgegIah31OmrTmUAUQ62rnZY">
> > 
> > 
> > 这确实是最新版。你不能通过这个来安装模组吗？
> 
> 我最开始就是通过这个安装的嘞，有可能是以前我玩的时候加了汉化没有删是吗？

有可能，总之你先把根目录删了然后检查完整性吧

**Comment by N071** [comment]
对的，这能保证你完全清除旧版本文件。然后请你从自动安装开始：https://www.zeroasso.top/docs/install/autoinstall
重新进行模组的安装。

这个Issue到此结束了，对于这个问题我们能帮你的真的不多。基础的指引已经在文档站上写清楚了，我们说再多其实也是对于那上面内容的重复罢了。

**Comment by 3264084688** [comment]
> 对的，这能保证你完全清除旧版本文件。然后请你从自动安装开始：https://www.zeroasso.top/docs/install/autoinstall 重新进行模组的安装。
> 
> 这个Issue到此结束了，对于这个问题我们能帮你的真的不多。基础的指引已经在文档站上写清楚了，我们说再多其实也是对于那上面内容的重复罢了。

我感觉应该欧克了，太感谢兄弟们了

**Comment by 3264084688** [comment]
> > > > > 不可能，OD只有最新版，你打开截图我看看
> > > > 
> > > > 
> > > > <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/188755660/386962529-072b8c36-9bfd-4e16-abad-c4cb2aacaba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTA3MDksIm5iZiI6MTczMTg1MDQwOSwicGF0aCI6Ii8xODg3NTU2NjAvMzg2OTYyNTI5LTA3MmI4YzM2LTliZmQtNGUxNi1hYmFkLWM0Y2IyYWFjYWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMzMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE5ZTQwYzY5MmQ5OGMxYTA5MGJlNjUzNGMwZGMwNjEwZjU5ZGRiY2RmOTYxNmY1NjBjMzBlMGE1ODU3NzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OQMXJlz72834MvfYxRYqgegIah31OmrTmUAUQ62rnZY">
> > > 
> > > 
> > > 这确实是最新版。你不能通过这个来安装模组吗？
> > 
> > 
> > 我最开始就是通过这个安装的嘞，有可能是以前我玩的时候加了汉化没有删是吗？
> 
> 有可能，总之你先把根目录删了然后检查完整性吧
谢谢兄弟了，太感谢了

**Comment by N071** [comment]
> > 对的，这能保证你完全清除旧版本文件。然后请你从自动安装开始：https://www.zeroasso.top/docs/install/autoinstall 重新进行模组的安装。
> > 这个Issue到此结束了，对于这个问题我们能帮你的真的不多。基础的指引已经在文档站上写清楚了，我们说再多其实也是对于那上面内容的重复罢了。
> 
> 太感谢兄弟了，我进去了

看得出来你应该是很久之前玩过，然后咸鱼了一段时间，旧版本没删的情况下回坑了。我们的模组一直在开发当中，加之月计也一直在更新，所以经常会有旧版本已经根本用不了了的情况出现。以后也是先删干净老文件，再下载最新版才是稳妥之举。

总之没问题就好。
