### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by Rabi-Alna** [LocalizeLimbusCompany/LocalizeLimbusCompany#305]
### 说说你遇到的问题？

首先感谢翻译组的努力
我是最近才入坑的，关于补丁还不是很了解。
请问一下这个更新是如何更新的？是需要手动下载最新的汉化文件进行文件覆盖，还是说需要提前清空翻译文件后再安装最新版？（之前玩的某些游戏的mod更新不支持直接根目录覆盖）

**Comment by mucketguct** [comment]
您好，感谢反馈，关于模组的自动更新，详情可以参考置顶动态下的置顶评论，也祝玩得开心：

如果需要更新模组的话，只需要在每次最新版模组更新时（每次最新版模组更新时，会发布动态通知啦），在看到模组更新动态后，进入工具箱，点击“开始安装”按钮，一般加载5-10秒，即可完成自动更新啦，无需重复安装工具箱，也无需清空模组文件的啦
