### ISSUE TITLE
無法運行遊戲。

### ISSUE THREAD

**Issue by bora0105** [LocalizeLimbusCompany/LocalizeLimbusCompany#307]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

無法運行遊戲。

![螢幕擷取畫面 2024-11-30 202249](https://github.com/user-attachments/assets/fbe83085-c75f-4051-9821-7a99638d5468)

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/17965382/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/17965383/Player.log)

### 截图

![螢幕擷取畫面 2024-11-30 202249](https://github.com/user-attachments/assets/bd26f1a9-c180-43bf-870a-acab6b2740bc)

![螢幕擷取畫面 2024-11-30 203256](https://github.com/user-attachments/assets/9ed78493-a43b-4ec1-bdda-987c86d2e853)

### 还有别的吗？

處理器	12th Gen Intel(R) Core(TM) i5-12450H   2.50 GHz
已安裝記憶體(RAM)	8.00 GB 
系統類型	64 位元作業系統，x64 型處理器
版本	Windows 11 家用版
版本	23H2

**Comment by N071** [comment]
请考虑回退模组版本至0.6.58及以前。请您参考：https://www.bilibili.com/opus/1005273018765672486
