### ISSUE TITLE
steam端加载汉化程序后进入游戏封面点击后黑屏

### ISSUE THREAD

**Issue by APM0767** [LocalizeLimbusCompany/LocalizeLimbusCompany#308]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

加载汉化程序后进入游戏封面点击后黑屏，但鼠标点击后有正常光环反馈

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/17965941/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/17965942/Latest.log)

**Comment by ZengXiaoPi** [comment]
`[Warning:Il2CppInterop] Failed to init IL2CPP patch backend for static FMOD.Studio.EventInstance VoiceGenerator::CreateVoiceInstance(string path, bool isSpecial), using normal patch handlers: Exception has been thrown by the target of an invocation.`
疑似是这个问题，但汉化补丁并没有动这个方法
尝试检查游戏完整性或重新安装模组
