### ISSUE TITLE
关于翻译后的“命定之战”动画是否可以添加原拉丁字母动画的切换

### ISSUE THREAD

**Issue by shuixigua** [LocalizeLimbusCompany/LocalizeLimbusCompany#309]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![屏幕截图 2024-12-02 161205](https://github.com/user-attachments/assets/ab426969-0780-4db9-9aeb-e0aaa9b3b0b9)
个人感觉还是原本的动画更有一种压迫力（看不懂）

### 有什么好的想法？

觉得可以和头顶气泡等功能放在一起，在特殊功能中可以自行修改是否启用翻译前的动画

**Comment by Nephthys137** [comment]
否
