### ISSUE TITLE
这里的翻译好生硬啊

### ISSUE THREAD

**Issue by Alicepro** [LocalizeLimbusCompany/LocalizeLimbusCompany#311]
### 说说你遇到的问题？

![bug](https://github.com/user-attachments/assets/59fb75e6-2948-478d-b6b7-16456abe2bb4)
这怎么读怎么别扭啊

**Comment by Alicepro** [comment]
位置：第五章5-35战前

**Comment by Alicepro** [comment]
游去换成游走了或许更通顺？

**Comment by ZengXiaoPi** [comment]
已修改为：
`其他苏醒的鲸都已经游向了诱饵撒播的方向！`
感谢反馈。
