### ISSUE TITLE
steam端加载0.6.59版本汉化后加载界面后黑屏

### ISSUE THREAD

**Issue by APM0767** [LocalizeLimbusCompany/LocalizeLimbusCompany#312]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

steam端加载0.6.59版本汉化后加载界面后黑屏，状态与#308以及#310相同，尝试把BepInEx\plugins\LLC\LimbusLocalize_BIE.dll 更换成0.6.58版本的相同文件后可以0.6.58版本的汉化进度进入游戏。

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/17978229/Player.log)
[Latest(框架日志).log](https://github.com/user-attachments/files/17978232/Latest.log)

**Comment by APM0767** [comment]
![微信图片_20241202210745](https://github.com/user-attachments/assets/3a3d07f4-f6b7-4b72-8570-e60af189806e)
镜牢之类的文内容翻译进度同步到0.6.59了。
![微信截图_20241202211007](https://github.com/user-attachments/assets/d5ab26cd-39a5-4144-8fad-9cf5a04b5b5c)
但这种部分的依然是未翻译，我忘记类似的部分以前是否翻译过。

**Comment by ZengXiaoPi** [comment]
> ![微信图片_20241202210745](https://private-user-images.githubusercontent.com/190200808/391554893-3a3d07f4-f6b7-4b72-8570-e60af189806e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDU1NjEsIm5iZiI6MTczMzE0NTI2MSwicGF0aCI6Ii8xOTAyMDA4MDgvMzkxNTU0ODkzLTNhM2QwN2Y0LWY2YjctNGI3Mi04NTcwLWU2MGFmMTg5ODA2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxMzE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Zjk0YjY4YWI1NGNkZjlhZmM2YzI4ZmZiMzg1NzgyOGI3MmIyNTU0NzU5ZGRhZjI5ZDE0MzE2N2YwN2I5YjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EPq78v_sqY-jk9miAtS33Ct5g0duo2YWyz0S4h0Dj2U) 镜牢之类的文内容翻译进度同步到0.6.59了。 ![微信截图_20241202211007](https://private-user-images.githubusercontent.com/190200808/391555737-d5ab26cd-39a5-4144-8fad-9cf5a04b5b5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDU1NjEsIm5iZiI6MTczMzE0NTI2MSwicGF0aCI6Ii8xOTAyMDA4MDgvMzkxNTU1NzM3LWQ1YWIyNmNkLTM5YTUtNDE0NC04ZmFkLTljZjVhMDRiNWI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxMzE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmEwZWNhYjc1OGE5MjViYWY2YjM0MjMwNTc5ZTc4MTYxZjRmZjFlYzk3OTkzNGQ4MmUyNDU4NDY5MGU0ZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0EAkgetOpEZGZJsBJL8IWfIPaJgBEiNTL5bBQD2lnVI) 但这种部分的依然是未翻译，我忘记类似的部分以前是否翻译过。

1. 这是图片资源，逐个替换对于翻译量要求不高，但对于**程序**和**美术**会造成**极大负担**。
2. 零协会从未翻译过此类banner资源。

**Comment by APM0767** [comment]
[Latest(框架日志).log](https://github.com/user-attachments/files/17978552/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/17978553/Player.log)
这是使用了0.6.58版本BepInEx\plugins\LLC\LimbusLocalize_BIE.dll 之后能正常游戏的日志。

**Comment by Nephthys137** [comment]
![image](https://github.com/user-attachments/assets/e3ca5193-f679-420e-8893-af48dc6d75bd)
令人遗憾,你无法初始化FMOD.Studio;这是游戏的问题,通常出现在网络波动中;表现为在登录界面无法载入音乐、没有罪人喊标题、无法进入游戏;
而你因为未知的原因暂时绕过了这个问题,这并不意味着问题不存在,所以汉化尝试读取FMOD.Studio时他崩溃了
