### ISSUE TITLE
疑似汉化补丁生效中会导致游戏内购无法呼出Steam购买界面

### ISSUE THREAD

**Issue by KaichengJiang** [LocalizeLimbusCompany/LocalizeLimbusCompany#313]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

前一次游戏内购买时间为：国内2024年11月29日5:19 （英国2024年11月28日21:19）在开启汉化模组的情况下游戏内购买正常

首次发现该问题时间：国内2024年12月4日8时左右 （英国0点左右），在两个时间点之间没有对操作系统做出任何改动，更新等

1. 在开启汉化模组的情况下，游戏内点击购买商品，在显示CONNECTING后不会呼出Steam（英区）购买界面，随后CONNECTING消失，游戏运行正常

2. 尝试清除游戏内所有缓存重新运行，该问题依然存在

3. 退出游戏和Steam，在Steam关闭状态直接运行LimbusCompany.exe，汉化模组不会生效，游戏使用默认英文。在模组未启动情况下，游戏内可以正常购买商品并呼出Steam购买界面

4. 退出游戏和Steam，随后启动Steam，并在Steam内启动游戏，汉化模组生效，游戏内购买无法呼出Steam界面（同1）

由于汉化模组运行正常，没有尝试卸载模组并重装。但在提交日志之前特意进行了多次购买操作（无法呼出Steam页面），不清楚是否会在日志中有相关记录

由于汉化模组关闭情况下可以正常进行游戏内购，该反馈仅供参考

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/18001538/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/18001539/Player.log)

### 截图

汉化模组生效情况下，游戏内购买任意礼包/狂气，显示CONNECTING，但不会呼出Steam购买界面，随后CONNECTING消失，游戏运行正常

**Comment by Nephthys137** [comment]
该问题未能成功复现,日志中也没有相关错误
鉴定为月亮抽风,资源/环境不完整
