### ISSUE TITLE
替換UI上的文本破壞其設計美感

### ISSUE THREAD

**Issue by Must4rd-hsv** [LocalizeLimbusCompany/LocalizeLimbusCompany#314]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

遊戲原始的UI字型是配合UI本身外型設計的，使用翻譯模組替換文本後對設計語言造成嚴重破壞。

### 有什么好的想法？

希望可以提供在(至少主畫面和戰鬥介面)不替換原始字形及文本的選項。

**Comment by mucketguct** [comment]
您好，感谢您的反馈；目前暂时没有这方面的改动意向，但还是感谢您的反馈，也祝玩得开心啦
