### ISSUE TITLE
一个关于12.2困难镜5更新公告的问题

### ISSUE THREAD

**Issue by gongmiaocai** [LocalizeLimbusCompany/LocalizeLimbusCompany#315]
### 说说你遇到的问题？

<img width="414" alt="搜狗高速浏览器截图20241206172950" src="https://github.com/user-attachments/assets/48a3595f-af86-45ef-889b-100ec912f97c">
<img width="571" alt="搜狗高速浏览器截图20241206172655" src="https://github.com/user-attachments/assets/49fc5ea0-e3c5-4b9e-a334-0d65030c46e0">
如图，翻译的公告遗漏了“with weekly bonuses”，导致有些人误解为困难难度下的常规通关经验比普通难度高，有一定歧义。并且原公告有一段特别说明了无周奖励时普通与困难收益没有区别，这一段也遗失了。

**Comment by mucketguct** [comment]
您好，感谢反馈！目前确认为，应该是月计在周一的一次无通知公告更改中，二次修改了这一页公告的内容啦（如下图）：

无通知更改前的公告：

![1](https://github.com/user-attachments/assets/43f6bbeb-03ee-4f49-814a-404e282dd52a)
![2](https://github.com/user-attachments/assets/d9a1d74c-2b31-4049-a67f-db6fafea6324)

无通知更改后的公告：

![３](https://github.com/user-attachments/assets/7a0f198f-3d0d-4bf5-892c-7f5c8ba2a2e5)
![４](https://github.com/user-attachments/assets/b91a6ed2-6f9f-465a-abaf-f85d58444444)

目前已经在对无通知更改后的公告进行翻译啦，预计会发布动态通知的，也非常感谢反馈，祝玩得开心——

**Comment by gongmiaocai** [comment]
感谢回复，结果最后还是小金的锅、、、

**Comment by mucketguct** [comment]
没事的！非常感谢啦——
