### ISSUE TITLE
主界面的汉化公告按钮的感叹号标记怎么也点不掉

### ISSUE THREAD

**Issue by Alicepro** [LocalizeLimbusCompany/LocalizeLimbusCompany#318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

具体见截图，这个感叹号使用包括但不限于打开界面和来回切换等方式，都无法消去

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/18045984/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/18045985/Player.log)

### 截图

![06f5edb2-f562-4c8c-9dc4-cb1d52dd65c4](https://github.com/user-attachments/assets/2e8d6231-5664-4133-b886-26f60ad97f9a)
![d4dc8369-3730-4ed8-bb3f-82d60675ca2a](https://github.com/user-attachments/assets/5ae8056d-e97a-48ee-99dc-05b92072c9d3)

**Comment by N071** [comment]
因为公告自动生成方法自本周起受到调整，故本周出现一些问题。因为每次只会保留两条更新公告，因此需要到下次更新，公告再次生成时观察具体情况再做修复。
