### ISSUE TITLE
游戏教程翻译部分，关于完全共鸣的教程翻译是否可以更精确一些

### ISSUE THREAD

**Issue by Alicepro** [LocalizeLimbusCompany/LocalizeLimbusCompany#320]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前中文下没有很清晰的写出完全共鸣需要连续才能触发，但是日语文本中应该是强调了需要连续才能触发完全共鸣效果，在这块容易导致新手歧义？具体见截图
![20241207111337_1](https://github.com/user-attachments/assets/593906e1-f63e-44cc-b199-254079c76a1b)
![20241207111342_1](https://github.com/user-attachments/assets/fc934544-5ea3-4056-8098-eefb58106b19)
![20241207112057_1](https://github.com/user-attachments/assets/b45f6dc1-84cb-4e2d-beaf-4d52bfe4ba6e)
![20241207112105_1](https://github.com/user-attachments/assets/8817ec3d-12ed-49da-a8a4-76a9062d358d)

### 有什么好的想法？

完全共鸣效果描述的界面里面，"三个及以上相同属性"改为"连续三个及以上相同属性"或许会更清晰一些？

**Comment by N071** [comment]
感谢，此处文本已经补全
