### ISSUE TITLE
v0.6.59后游戏黑屏

### ISSUE THREAD

**Issue by anyan0908** [LocalizeLimbusCompany/LocalizeLimbusCompany#321]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

自v0.6.59后安装补丁游戏黑屏

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/18046307/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/18046308/Player.log)

### 截图

![68651203-661b-4b2f-bcce-8f0e1311ee35](https://github.com/user-attachments/assets/57c7a586-e9a9-4005-8fc6-9e26f982dc02)
![3edcafa9-1287-4bc5-8288-ff96fe33754c](https://github.com/user-attachments/assets/2658dd66-9d15-47da-a71d-6bd99ef8582d)

### 还有别的吗？

上次更新后出现的，之前一直好好的，本人从未使用其他mod或者脚本。

**Comment by Nephthys137** [comment]
```
SystemNotInitializedException: [FMOD] Initialization failed : Output forced to NO SOUND mode : ERR_OUTPUT_INIT : Error initializing output device.
  at FMODUnity.RuntimeManager.get_Instance () [0x00000] in <00000000000000000000000000000000>:0 
  at FMODUnity.RuntimeManager.PathToGUID (System.String path) [0x00000] in <00000000000000000000000000000000>:0 
  at FMODUnity.RuntimeManager.CreateInstance (System.String path) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceGenerator..cctor () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'VoiceGenerator' threw an exception.
```
还是FMOD.Studio无法载入;未来会特别修复该问题

**Comment by N071** [comment]
曾出现过类似问题。请跟随以下步骤尝试：
1. **彻底删除**而**不是禁用**汉化模组。
2. 重新启动游戏，确认游戏可以在无汉化模组情况下正常启动。若游戏本身出现问题，则删除重装游戏。
3. 安装汉化模组

**Comment by anyan0908** [comment]
删除汉化补丁，删除游戏，关闭汉化和删除缓存都试过啦还是这样，无汉化模组情况下可以正常使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月8日(周日) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] v0.6.59后游戏黑屏 (Issue #321)




 
曾出现过类似问题。请跟随以下步骤尝试：
  
彻底删除而不是禁用汉化模组。
 
重新启动游戏，确认游戏可以在无汉化模组情况下正常启动。若游戏本身出现问题，则删除重装游戏。
 
安装汉化模组

**Comment by Nephthys137** [comment]
[BepInEx.zip](https://github.com/user-attachments/files/18054160/BepInEx.zip)
由于无法复现问题,请您使用该文件内容替换模组;然后将运行-退出后日志再次上传

**Comment by anyan0908** [comment]
阿立
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LocalizeLimbusCompany/LocalizeLimbusCompany"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月8日(星期天) 晚上10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] v0.6.59后游戏黑屏 (Issue #321)





 
曾出现过类似问题。请跟随以下步骤尝试：
  
彻底删除而不是禁用汉化模组。
 
重新启动游戏，确认游戏可以在无汉化模组情况下正常启动。若游戏本身出现问题，则删除重装游戏。
 
安装汉化模组

**Comment by anyan0908** [comment]
.64版本后还是有该问题，以上日志是替换后的。


阿立
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LocalizeLimbusCompany/LocalizeLimbusCompany"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月9日(星期一) 上午6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] v0.6.59后游戏黑屏 (Issue #321)





 
BepInEx.zip
 由于无法复现问题,请您使用该文件内容替换模组;然后将运行-退出后日志再次上传
