### ISSUE TITLE
战斗语音头顶气泡功能，对7协会浮士德人格的3技能（猜测原因为：其为包含多句语音技能）不生效

### ISSUE THREAD

**Issue by Dewcat** [LocalizeLimbusCompany/LocalizeLimbusCompany#323]
### 说说你遇到的问题？

其他单句语音对应的文本气泡都可以正常显示，可能是因为7协会浮士德的3技能有多句语音导致的？
目前问题在7协会浮士德的3技能上稳定复现，但是受限于持有人格数过少，无法在其他多句语音技能上测试。
烦请汉化组关注一下这个问题。

**Comment by Nephthys137** [comment]
该气泡功能会自动匹配并展示人格语音的翻译
这意味着：如果一句语音没有出现在人格语音中那么他就不会被展示
很显然的，技能语音和特殊条件下触发的语音并不包含在人格语音之中
