### ISSUE TITLE
游戏启动后控制台报错，游戏中无中文选项

### ISSUE THREAD

**Issue by lyyyf340** [LocalizeLimbusCompany/LocalizeLimbusCompany#324]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

在12月12日更新后，打开游戏就会报错，删除并重现安装了四次仍旧报错

### 日志文件

[Latest(框架日志).log](https://github.com/user-attachments/files/18108577/Latest.log)
[Player(游戏日志).log](https://github.com/user-attachments/files/18108578/Player.log)

### 截图

![屏幕截图 2024-12-12 165240](https://github.com/user-attachments/assets/2dc0640d-e424-4477-87c4-7475be3c7c3d)

**Comment by mucketguct** [comment]
您好，今天在更新后发生的此类汉化失效状况，是因为月亮计划在本次更新中大改了文本的显示逻辑，导致模组文本目前暂时无法正常显示，目前正在尝试修复中啦，详情可以参见今天上午发布的最新动态啦--

**Comment by N071** [comment]
请关注我们的B站账号，如果模组更新后出现问题我们会提供消息。

在发Issue之前请务必确认我们是否已经有提前告知，这样能**节省所有人的时间和生命**。
