### ISSUE TITLE
模组安装后未生效

### ISSUE THREAD

**Issue by wuyue20050426** [LocalizeLimbusCompany/LocalizeLimbusCompany#325]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我使用的汉化补丁版本已为最新版

### 问题描述

安装模组完成后控制台出现如下红字：[Error  :LimbusLocalizeMod] Mod Has Unknown Fatal Error!!!
妯＄粍閮ㄥ垎鍔熻兘鍑虹幇鑷村懡閿欒,鍗冲皢鎵撳紑GitHub,璇锋牴鎹甀ssues娴佺▼鍙嶉
[Error  :LimbusLocalizeMod] HarmonyLib.HarmonyException: Patching exception in method null
 ---> System.ArgumentException: Undefined target method for patch method static void LimbusLocalize.ChineseFont::LoadRemote(LOCALIZE_LANGUAGE& lang)
   at HarmonyLib.PatchClassProcessor.PatchWithAttributes(MethodBase& lastOriginal)
   at HarmonyLib.PatchClassProcessor.Patch()
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.PatchAll(Type type)
   at LimbusLocalize.LLCMod.Load()

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/18112620/Player.log)

### 还有别的吗？

win11系统，工具箱、文件覆盖两种安装方式均尝试过，完全清除模组后重新安装并没有解决，也尝试了重新安装NET8.0，目前未尝试重新安装游戏（因为网络环境不好，需要花费非常长时间）

**Comment by N071** [comment]
https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/324#issuecomment-2538529722

请节省大家的时间

**Comment by wuyue20050426** [comment]
对了，先前迫不得已清理过Appdata文件夹，手法不是很熟练，可能造成了某些损伤。
