### ISSUE TITLE
第七章翻译出现的重复文本等若干错误

### ISSUE THREAD

**Issue by Natcache** [LocalizeLimbusCompany/LocalizeLimbusCompany#326]
### 在提问之前...

- [X] 我反馈的问题在零协会 BiliBili 动态没有相应近期公告
- [X] 我反馈的问题不属于已关闭/已解决的其它 Issue
- [X] 我使用的模组版本为最新版
- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等

### 问题描述

昨日观看某主播攻略第七章地牢时发现的问题：
1. 放映室中的第43话末尾出现两段文本重复出现两遍的现象（已在自己的账号上确认）；
2. 桑丘（Boss）的技能“堂吉诃德派硬血2式-血甲”被更名为“堂吉诃德派硬血2式-硬血”（因个人原因没有在自己的账号上确认）；
未确认桑丘（Boss）的buff状态“血甲”是否同样被更名为“硬血”。

其中问题2我无法确认是游戏文本本身的更改还是汉化出现的错误。

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/18132303/Player.log)

### 截图

以下是问题1的截图：
![屏幕截图 2024-12-14 055615](https://github.com/user-attachments/assets/5dddff87-0b0c-401b-82b4-e5be4cbdf0b9)
![屏幕截图 2024-12-14 055626](https://github.com/user-attachments/assets/b4bf30fd-c54c-420f-8a1f-836a4b540b02)

**Comment by Nephthys137** [comment]
1. 该剧情出现了重复的id,所以自动填充时重复id被填入同一内容
2. ![image](https://github.com/user-attachments/assets/9881f496-f950-49ae-a92c-0900aa54dd57)
