### ISSUE TITLE
控制台加载时出现大堆白字并强制退出

### ISSUE THREAD

**Issue by wtekh** [LocalizeLimbusCompany/LocalizeLimbusCompany#42]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

控制台加载时出现一大堆白字,之后强制退出,没有出现player.log文件,latest.log文件不刷新

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11182412/Latest.log)

### 截图

![QQ截图20230408111309](https://user-images.githubusercontent.com/112922267/230700946-e975d52e-1960-4e7b-8454-35bd0d0fbe82.png)
![QQ截图20230408105923](https://user-images.githubusercontent.com/112922267/230700948-358bfe1a-f320-4c96-a66c-a6a17422c3f2.png)

### 还有别的吗？

试过0.5版本的melonloader是可以加载的,只是会提示版本过低,也许问题在于0.6版本的melonloader但不知道具体是什么问题

**Comment by Bright1192** [comment]
删除MelonLoader文件夹重新安装0.6.1再试一次

**Comment by xxrlplysnff** [comment]
![QQ截图20230408224626](https://user-images.githubusercontent.com/130234021/230727578-edd85326-07f2-43a9-82a6-b7912ecf77f8.png)

![QQ截图20230408224650](https://user-images.githubusercontent.com/130234021/230727584-eeef5c6f-5def-426e-b74a-304c06b429e2.png)
零协汉化，您好。我在下解压汉化包后，打开游戏就会出现这个弹窗。我附上了截图和游戏所在文件夹的截图，期待您的解答。

**Comment by wtekh** [comment]
> 删除MelonLoader文件夹重新安装0.6.1再试一次

重新安装也是一样的问题

**Comment by Bright1192** [comment]
提供一下 游戏目录\MelonLoader文件夹中的 Latest.log

**Comment by Bright1192** [comment]
哦提供了，我看看
