### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by xxrlplysnff** [LocalizeLimbusCompany/LocalizeLimbusCompany#44]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

零协汉化组您好，我在将汉化包解压至游戏所在文件夹后，如截图所示无法打开游戏。按照最新专栏中所指向的安装视频，无视频中所示的beplnex文件夹。我已将这两部分截图在下面出示，期待您的解答，谢谢

### 日志文件

似乎并没有找到，抱歉

### 截图

![QQ截图20230408224626](https://user-images.githubusercontent.com/130234021/230727868-ddb47d95-61f6-441e-8c27-bb3ddc6bf80e.png)
![QQ截图20230408224650](https://user-images.githubusercontent.com/130234021/230727876-ce636170-a995-4cbe-984a-5a14932747cd.png)

**Comment by Bright1192** [comment]
按照提示来看很显然你没有安装net6.0，从项目的read me安装
