### ISSUE TITLE
开启时跳出failed to download unitydependencies进入后汉化全消失

### ISSUE THREAD

**Issue by eheh7762** [LocalizeLimbusCompany/LocalizeLimbusCompany#48]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开游戏时弹出failed to download unitydependencies（如图），同时有大量红色代码跳出（如图），进入游戏后汉化全部消失，感谢大佬修复！

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11189755/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11189757/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11189759/Latest.log)

### 截图

![微信图片_20230410181009](https://user-images.githubusercontent.com/130357911/230881770-ab003aaf-e85f-476f-a14e-8e635cf03fc1.png)
![微信图片_20230410180902](https://user-images.githubusercontent.com/130357911/230881809-5d28adb0-b76a-4174-892b-7a9f3ca70da6.png)
![微信图片_20230410180907](https://user-images.githubusercontent.com/130357911/230881848-a6427418-66e6-449f-9239-66c627af4d8e.png)

### 还有别的吗？

win10 64x 笔记本电脑 手机热点上网

**Comment by Bright1192** [comment]
在首次使用或游戏更新后首次使用框架会下载适配文件,如果你网络波动或无法访问GitHub就会这样

**Comment by eheh7762** [comment]
请问如何解决呢？感谢！

**Comment by Bright1192** [comment]
使用电脑梯子或加速器，比如说Steam++

**Comment by eheh7762** [comment]
好的谢谢！

**Comment by eheh7762** [comment]
实测有用！steam++好用！现在steam++改名叫watt toolkit了，在微软商城可下载，希望能帮助大家！
