### ISSUE TITLE
克勒默战中歌词字幕异常

### ISSUE THREAD

**Issue by Karyut** [LocalizeLimbusCompany/LocalizeLimbusCompany#52]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一阶段中，歌词字幕光效异常
二阶段中，歌词字幕变为乱码

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11220795/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11220796/default.log)

### 截图

![8N9O%_CHV$QPQ6H2C}GH9$K](https://user-images.githubusercontent.com/130625095/231723871-59d441b8-a480-4795-9190-7ca137a00ec9.png)
![_62WQ1I4MP N$6`X` MN$UA](https://user-images.githubusercontent.com/130625095/231723895-21c4d1aa-1d9e-4157-999b-3f94041d142a.png)

**Comment by Bright1192** [comment]
修复
