### ISSUE TITLE
各种数字文本大小异常

### ISSUE THREAD

**Issue by Karyut** [LocalizeLimbusCompany/LocalizeLimbusCompany#55]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

镜牢的升级中，等级数字文本过大
伤害显示数字文本过小
判定结果数字文本过小

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11227589/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11227590/default.log)

### 截图

![image](https://user-images.githubusercontent.com/130625095/231910085-f96a3c0f-33ce-4894-9dfa-2b1dce0d9336.png)
![image](https://user-images.githubusercontent.com/130625095/231910234-41ab751a-8bc8-4cdd-83ea-1ce386ff4623.png)
![image](https://user-images.githubusercontent.com/130625095/231911035-bdf9bcf6-0a9f-404a-ad4d-06503e90f424.png)

**Comment by Bright1192** [comment]
过大已被修复,过小不会被修复

**Comment by Karyut** [comment]
![image](https://user-images.githubusercontent.com/130625095/232177446-3234fb63-3732-4f8e-aba2-f4a08dc5b84f.png)
追加：人格升级界面字体大小过大

**Comment by Bright1192** [comment]
这个问题我已经在公告想法释放中多次提及了 #57 您是一个都不看啊

**Comment by Karyut** [comment]
发出去才想起来有更新了（


&nbsp;


苍之狩人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 上午10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LocalizeLimbusCompany/LocalizeLimbusCompany] 各种数字文本大小异常 (Issue #55)





 
这个问题我已经在公告想法释放中多次提及了 #57 您是一个都不看啊
