### ISSUE TITLE
镜牢升级时，字体大小问题

### ISSUE THREAD

**Issue by KbClownxxx** [LocalizeLimbusCompany/LocalizeLimbusCompany#56]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

镜牢升级时，等级、体力字体大小

### 日志文件

[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11228116/default.log)
[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11228118/default.log)

### 截图

![image](https://user-images.githubusercontent.com/56860845/231923766-a2ea5854-5e4d-47cb-b044-d43b49ea98ce.png)
![image](https://user-images.githubusercontent.com/56860845/231923877-3593ae75-003c-44de-a6ac-c76a381f68c2.png)

**Comment by Bright1192** [comment]
好吧,为了避免有人重复提出这个问题我会发个公告

**Comment by KbClownxxx** [comment]
![image](https://user-images.githubusercontent.com/56860845/231928330-25eb95e3-8236-4173-8dc3-06d1e926e405.png)
这里面的也会有问题

**Comment by Bright1192** [comment]
> 为了避免有人重复提出这个问题

v0.1.9.1已经修复了这个问题,请去[下载这个](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/releases/download/v0.1.9/LimbusLocalize_OTA_v0.1.9.1.rar)和[v230413中文字体](https://github.com/LocalizeLimbusCompany/LLC_ChineseFontAsset/releases/download/230413/tmpchinesefont_230413.7z)
