### ISSUE TITLE
紧急公告:白眼(battleye)扫内存反外挂

### ISSUE THREAD

**Issue by Bright1192** [LocalizeLimbusCompany/LocalizeLimbusCompany#66]
月亮计划将在下个Steam版本增加白眼(battleye)扫内存反外挂，而汉化模组理论上动了内存所以可能会被检测到，如果害怕封号请停止使用
### Discussed in https://github.com/orgs/LocalizeLimbusCompany/discussions/65

<div type='discussions-op-text'>

<sup>Originally posted by **ZengXiaoPi** April 17, 2023</sup>
1. 目前最保险的办法是卸载MelonLoader及mod，办法为重命名**version.dll**或直接删除
2. 一旦被封禁不仅仅代表账号被封禁，被封禁后整个设备将无法游玩使用此技术的游戏，需要更换硬盘
3. ~~这货真的是眼线+爪牙。。。~~
欢迎补充以及提出解决方法。</div>

**Comment by ZengXiaoPi** [comment]
建议：在ReadMe中增加提示
虽然很无可奈何，但面对可能存在的风险应先提前做好措施

**Comment by Bright1192** [comment]
[特别公告:月亮计划 声明 不会对汉化模组封号](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/69)
