### ISSUE TITLE
更新后进入地狱厨房剧情时，播放一小段剧情后就会屏幕变暗并卡住，但可以跳过剧情直接进入战斗，回放时仍然是这个情况。

### ISSUE THREAD

**Issue by noGitHubID** [LocalizeLimbusCompany/LocalizeLimbusCompany#72]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

此外字体方面仍然有一些不痛不痒的小问题，比如占两格的上引号。

### 日志文件

[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11279602/default.log)

**Comment by Bright1192** [comment]
已更新
