### ISSUE TITLE
将下载的汉化包解压进游戏之后无法打开游戏

### ISSUE THREAD

**Issue by lucarioax** [LocalizeLimbusCompany/LocalizeLimbusCompany#77]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在b站专栏下载的汉化版解压后，在steam点开进入游戏，弹窗都没有弹出，游戏也没有弹出，就关闭了，没有打开

### 日志文件

没有（）

**Comment by Bright1192** [comment]
没有日志的话我建议你去占卜一下看看有没有办法解决
