### ISSUE TITLE
解压完汉化包之后打不开游戏

### ISSUE THREAD

**Issue by lucarioax** [LocalizeLimbusCompany/LocalizeLimbusCompany#79]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在b站下载的汉化包，解压到目录后，打不开游戏，这次上传了log，能帮忙看下么

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11295320/Latest.log)

**Comment by Bright1192** [comment]
看不出什么，没有任何报错，所以我帮不到你
