### ISSUE TITLE
浮士德N公司人格和三星李箱戰鬥時 3技能無法選定 + 當使用時，第三枚硬幣會無法攻擊

### ISSUE THREAD

**Issue by benvon666** [LocalizeLimbusCompany/LocalizeLimbusCompany#80]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

浮士德N公司人格和三星李箱戰鬥時3技能無法選定(僅在異想體戰鬥發生) +當使用時，第三枚硬幣會無法攻擊(對人和異想體都會)
只能退出戰鬥作結

### 日志文件

[游戏日志.zip](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11296369/default.zip)

### 截图

![螢幕擷取畫面 2023-04-21 213103](https://user-images.githubusercontent.com/131463755/233652675-fc704c5d-6867-44ab-a4ed-027f8d35c6ef.jpg)
![螢幕擷取畫面 2023-04-21 213316](https://user-images.githubusercontent.com/131463755/233652708-3319028b-ae01-4cfe-ad0b-ca74eef6faa5.jpg)
![image](https://user-images.githubusercontent.com/131463755/233655032-d6992c89-b67d-45f1-98ee-5251d48a53a5.png)
![image](https://user-images.githubusercontent.com/131463755/233653667-ffa53115-7880-490a-95a2-90291924e963.png)

### 还有别的吗？

用v0.1.9.9.1補丁

**Comment by Bright1192** [comment]
这是游戏的bug
