### ISSUE TITLE
新版本bug

### ISSUE THREAD

**Issue by lingxuan-cc** [LocalizeLimbusCompany/LocalizeLimbusCompany#82]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装模组后无法打开游戏或是无法以汉化版打开游戏

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11300313/Latest.log)
[Player.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11300314/Player.log)

**Comment by lingxuan-cc** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> 
> ### 问题描述
> 安装模组后无法打开游戏或是无法以汉化版打开游戏
> 
> ### 日志文件
> [Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11300313/Latest.log) [Player.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11300314/Player.log)
> 
> ### 截图
> _No response_
> 
> ### 还有别的吗？
> _No r
![屏幕截图(81)](https://user-images.githubusercontent.com/131510289/233763899-21b18592-ec95-476d-ac85-486e32e39037.png)
补充一下截图esponse_

**Comment by Bright1192** [comment]
在新版本更新后模组框架需要自动从github上下载一些必要的组件，这个弹窗意味着你无法访问，请尝试使用梯子
