### ISSUE TITLE
使用問題

### ISSUE THREAD

**Issue by yamiyousanke** [LocalizeLimbusCompany/LocalizeLimbusCompany#85]
### 说说你遇到的问题？

您好：
我在試著使用時按照了教學解壓縮了需要下載的文件到資料夾中，但在執行遊戲後沒有發生任何變化，它就像之前一樣執行，沒有像教學影片那樣啟動時有一串log，同樣也沒有輸出log檔。
![未命名](https://user-images.githubusercontent.com/131605722/233850008-d23141a3-6317-4e04-9391-126eed195ee7.png)
這是我資料夾目前的檔案，請問我是哪個步驟做錯了嗎？
謝謝。

**Comment by Bright1192** [comment]
你应该从Releases下载而不是Code
