### ISSUE TITLE
打开后出现弹窗，继续进入游戏后没有汉化内容

### ISSUE THREAD

**Issue by xushixiangsheng** [LocalizeLimbusCompany/LocalizeLimbusCompany#87]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

都按照步骤做好了，文件里的东西一一对应都是有的。但双击后出现一个西瓜图标并弹窗显示INTERNAL FAILURE!failed to download unityDependencies！怎么办呢！

### 日志文件

[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11359313/Latest.log)

### 截图

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/127958834/235306402-64fc5b24-727e-4703-8b07-a5f1f7077e09.png">

**Comment by Bright1192** [comment]
在首次使用或者更新游戏后首次使用需要连接github下载适配文件这个弹窗则意味着你无法访问github，请使用梯子或者能加速github的加速器，例如Steam++
另外因为某些原因你必须使用开发版的版本，不然字体会成为口口

**Comment by xushixiangsheng** [comment]
> 在首次使用或者更新游戏后首次使用需要连接github下载适配文件这个弹窗则意味着你无法访问github，请使用梯子或者能加速github的加速器，例如Steam++ 另外因为某些原因你必须使用开发版的版本，不然字体会成为口口

好的！谢谢(･ω･)ﾉ

**Comment by xushixiangsheng** [comment]
> 在首次使用或者更新游戏后首次使用需要连接github下载适配文件这个弹窗则意味着你无法访问github，请使用梯子或者能加速github的加速器，例如Steam++ 另外因为某些原因你必须使用开发版的版本，不然字体会成为口口

要下载什么适配文件？开发版的版本是哪个？

**Comment by Bright1192** [comment]
下载适配文件是开启游戏后自动进行的
开发版是https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/suites/12569161667/artifacts/671975743

**Comment by xushixiangsheng** [comment]
> 下载适配文件是开启游戏后自动进行的 开发版是https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/suites/12569161667/artifacts/671975743

好的！！谢谢！！(*^▽^*)
