### ISSUE TITLE
0.2.0方块字问题

### ISSUE THREAD

**Issue by getpain** [LocalizeLimbusCompany/LocalizeLimbusCompany#89]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

0.2.0汉化版本，原本可以正常使用的，某天突然出现了全文方块字问题，安装器或直接解压安装包均无果，
.NET 6.0安装了，字体文件重新安装替换也没用

唯一的跳错是这个
[15:58:51.353] [LimbusLocalizeMod] Mod Has Unknown Fatal Error!!!
System.NullReferenceException: Object reference not set to an instance of an object.
   at LimbusLocalize.LimbusLocalizeMod.OnInitializeMelon() in D:\a\LocalizeLimbusCompany\LocalizeLimbusCompany\src\LimbusLocalize.cs:line 43

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11360837/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11360838/default.log)

**Comment by Bright1192** [comment]
#87
