### ISSUE TITLE
#89相同问题但是

### ISSUE THREAD

**Issue by W1nstt0n** [LocalizeLimbusCompany/LocalizeLimbusCompany#90]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照#87的方式做了，但是蹦出来这个

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11364120/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11364121/default.log)

### 截图

![QQ图片20230501152645](https://user-images.githubusercontent.com/132254004/235422748-92ee7f5b-66c3-4331-b1c8-a228912b46af.png)

**Comment by Bright1192** [comment]
因为这是开发版最新的释放暂且没有发布，你可以点击其他区域关闭
