### ISSUE TITLE
无法进入提示初始化失败

### ISSUE THREAD

**Issue by ZeMeTianTianBuNengYongZhongWen** [LocalizeLimbusCompany/LocalizeLimbusCompany#92]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

正常下载解压到边狱文件夹了，可提示说初始化失败了

### 日志文件

()

### 截图

![QQ图片20230501211011](https://user-images.githubusercontent.com/132273521/235455969-30f0e152-6402-4176-9e07-a6e06254d851.png)
![QQ图片20230501211015](https://user-images.githubusercontent.com/132273521/235456029-38b32ea3-aa6d-46c9-b53b-5690d5ad309b.png)

**Comment by Bright1192** [comment]
![image](https://user-images.githubusercontent.com/87061166/235457035-227ca724-d29d-487c-851b-c09aef8b2bce.png)

**Comment by ZeMeTianTianBuNengYongZhongWen** [comment]
[MelonLoader_23-03-10_09-18-55.944.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11365605/MelonLoader_23-03-10_09-18-55.944.log)
是这些吗

**Comment by Bright1192** [comment]
从报错上来看你至少犯了三处错误，第一是没有使用060或更高版本的模组框架，第二是没有安装net6.0，第3不看其他人的反馈，请确保您正确的看了并做了每一个步骤
#90

**Comment by ZengXiaoPi** [comment]
确保没有别的问题，请你也一并检查一下有没有装字体文件

**Comment by ZeMeTianTianBuNengYongZhongWen** [comment]
好的，十分感谢，给你们带来麻烦十分抱歉
