### ISSUE TITLE
人物错乱

### ISSUE THREAD

**Issue by die1001** [LocalizeLimbusCompany/LocalizeLimbusCompany#93]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我使用最新版的汉化时，打副本有概率出现这样的问题，我多次重启之后又好了

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11372856/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11372857/default.log)

### 截图

![20230502200138_1](https://user-images.githubusercontent.com/132359102/235661602-8c838d35-b9d3-4cfd-94cd-e603c6ca6053.jpg)

**Comment by Bright1192** [comment]
这是游戏的经典bug，和模组无关
