### ISSUE TITLE
2天前显示需安装新版游戏客户端但无从下手，无法进入游戏

### ISSUE THREAD

**Issue by xushixiangsheng** [LocalizeLimbusCompany/LocalizeLimbusCompany#95]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这两天打开游戏后一直显示需要安装新版游戏客户端，可我看了很多次steam安装页面，没有更新键。怎么办才好，求助！

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11402388/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11402389/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11402390/Latest.log)

### 截图

<img width="1080" alt="屏幕截图 2023-05-05 074750" src="https://user-images.githubusercontent.com/127958834/236353039-f8c03daa-8f83-4fb7-8ab1-1b601dd539c4.png">
<img width="1080" alt="屏幕截图 2023-05-05 074718" src="https://user-images.githubusercontent.com/127958834/236353116-6333f154-f128-4a04-81e6-708df7784098.png">

**Comment by Bright1192** [comment]
这是steam的问题，你可以尝试重启steam

**Comment by xushixiangsheng** [comment]
<img width="733" alt="屏幕截图 2023-05-05 081202" src="https://user-images.githubusercontent.com/127958834/236355443-fd73f322-3962-42d8-9da3-04167112c5e8.png">
但是它闪退了o(╥﹏╥)o
