### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by xushixiangsheng** [LocalizeLimbusCompany/LocalizeLimbusCompany#96]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我来提供log了(OoO)求助o(╥﹏╥)o

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11402494/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11402495/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11402496/Latest.log)

### 截图

<img width="733" alt="屏幕截图 2023-05-05 081202" src="https://user-images.githubusercontent.com/127958834/236356317-da34ff7c-1758-4571-8687-cd532fcdce84.png">

**Comment by Bright1192** [comment]
System.IO.IOException: 该进程无法访问该文件，因为它正被另一个进程使用。
