### ISSUE TITLE
无法进游戏

### ISSUE THREAD

**Issue by die1001** [LocalizeLimbusCompany/LocalizeLimbusCompany#97]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用3.0汉化时报了 Has update tmpchinesefont_230506 open download path & quit game 的错误，我将Mods下的tmpchinesefont.dll文件换回下载好游戏时的文件就解决了

### 日志文件

[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11413994/default.log)
[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11413995/default.log)

### 截图

![Uploading image.png…]()

**Comment by die1001** [comment]
![Uploading 20230507132841_1.jpg…]()

**Comment by die1001** [comment]
![20230507132841_1](https://user-images.githubusercontent.com/132359102/236659580-0314db93-33ab-412e-b281-a294a62ae90a.jpg)

**Comment by die1001** [comment]
等等，好像没用，我发现其实在旁边点一下就好了，我是sb

**Comment by Bright1192** [comment]
...我不知道该说什么好，这个弹窗的意图是告知你字体或者模组更新了，然后你应该点击OK把压缩包解压到弹出的目录
难道这个意图非常的让人费解吗
