### ISSUE TITLE
建议增加公告机翻功能

### ISSUE THREAD

**Issue by ImYiFeng** [LocalizeLimbusCompany/LocalizeLimbusCompany#98]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

游戏内英语公告阅读较为困难

### 有什么好的想法？

增加公告自动翻译功能，可以调用谷歌、有道等翻译API，对公告进行翻译，附于公告原文下方，虽然机翻没法做到完全准确，但也便于理解

**Comment by HeartyYF** [comment]
题外话：
https://space.bilibili.com/1247764479/dynamic
零协会动态会实时同步并总结月计公告内容，关注零协会喵，关注零协会谢谢喵

**Comment by N071** [comment]
- 我们曾经试过在Paratranz上对翻译组员开放公告翻译（作为低优先级任务），但目前已经因为产能问题取消。
- 我们有专门的公告翻译组，不过我们考虑到月计大段的修bug以及叠加等意义不大的文字，我们并非愿意从前至后翻译公告的全部内容。
- 机翻对公告内绝大部分的专有名词以及特殊句式翻译并不准确。
- 作为汉化组，我们倾向于避免使用机翻。
