### ISSUE TITLE
黑屏，恢复后游戏未响应

### ISSUE THREAD

**Issue by plantvsplant** [LocalizeLimbusCompany/LocalizeLimbusCompany#99]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2023年5月9日约1:53，挑战一号线无我入定时进入约第9个回合，第二个小怪被108层强化秒杀后出现黑屏，而后恢复时游戏显示无响应，翻译mod无法响应，背景音乐仍然进行播放，同时steam出现暂时无法访问游戏库的问题，QQ等其他应用软件自动关闭

### 日志文件

[游戏日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11423821/default.log)
[框架日志.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11423822/default.log)
[Latest.log](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/files/11423829/Latest.log)

### 截图

![20230509015110_1](https://user-images.githubusercontent.com/96964718/236898086-71f8f5b0-3a54-418a-8be3-316579796ad7.jpg)

### 还有别的吗？

Windows10
DELL G15 5510

**Comment by Bright1192** [comment]
日志中没有任何有效相关信息，所以无法得知该问题是如何出现的

**Comment by Bright1192** [comment]
去打了一下1号线的无我入定，没有复现该问题

**Comment by plantvsplant** [comment]
QWQ
